### ISSUE TITLE
Comment cumuler 2 actions ?

### ISSUE THREAD

**Issue by korelyann** [Aymkdn/assistant-freebox-cloud#10]
Bonjour,
J'ai suivi ton tuto pour commander la freebox revolution avec Google Assistant mais lorsque je lui fais allumer la box, elle s'allume bien mais attend la commande "OK".
J'ai bien trouvé la fonctionnalité dans la liste mais je ne vois pas comment lui faire exécuter l'allumage de la box puis "OK" en une seule requête.
Je te remercie par avance de ton aide.

**Comment by Aymkdn** [comment]
Il faut faire cette succession de commandes :
 - `power`
 - `wait7000`
  - `tv`

**Comment by korelyann** [comment]
Merci pour ta réponse. 
Vocalement ou dans une requête ? 

Je découvre IFTTT depuis 2 jours. 

⁣Télécharger BlueMail pour Android ​

Le 17 mars 2019 à 12:50, à 12:50, Aymeric <notifications@github.com> a écrit:

**Comment by Aymkdn** [comment]
Dan une seule commande. Tu peux utiliser la partie "commande personnalisée" du site Web

![Screenshot_20190317-124919__01](https://user-images.githubusercontent.com/946315/54490319-10d22a00-48b5-11e9-9352-fbe1d19e8632.jpg)

**Comment by korelyann** [comment]
Un grand merci. Cela fonctionne nickel ! 

⁣Télécharger BlueMail pour Android ​

Le 17 mars 2019 à 13:03, à 13:03, Aymeric <notifications@github.com> a écrit:
