### ISSUE TITLE
Touche AV

### ISSUE THREAD

**Issue by ERICRAC** [Aymkdn/assistant-freebox-cloud#100]
Salut,
Tout d'abord un grand merci car ce dev marche très bien.
Pourrais-tu gérer la touche AV de la télécommande (en haut à gauche). En effet mon réseau HDMI démarre le freebox player, la TV et l'ampli. Malheureusement ce dernier prend la main sur la TV et je doit faire un 'AV' pour revenir sur le player. J'aurais ainsi pu programme uné séquence via IFTTT (https://assistant.kodono.info/freebox) !
D'avance merci

**Comment by Aymkdn** [comment]
Je ne sais pas si un tel code existe dans l'API…

Ce que tu peux faire : 
  1. Regarde le point 7. https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Trouver-pourquoi-cela-ne-fonctionne-pas#7-test-en-local qui explique comment tester localement
  2. Ensuite essaie deux `key` : d'abord `key=tv`, puis `key=av`, et vois le résultat produit

Si aucun de ces deux codes ne fonctionnent, alors l'AV n'est pas disponible et je ne peux donc pas t'aider !

**Comment by ERICRAC** [comment]
tv et av ou aux ne fonctionnent pas en (révolution V6)!
J'ai trouvé une bidouille en appelant plusieurs fois "home"  après power ainsi la box reprend la main sur l'ampli.
Après différente lecture AV n'est pas documenté et pas implémenté par free
merci
