### ISSUE TITLE
Obligation d'éteindre 2 fois

### ISSUE THREAD

**Issue by bgfootspi** [Aymkdn/assistant-freebox-cloud#101]
Bonjour,
Quand je regarde un film ou autre sur ma révolution, 
Je dis "Alexa, éteins la tv."
Là, la box s'éteint et se rallume de suite en mode TV sans que la tv ne détecte un arrêt. 
Si je dis une seconde fois "Alexa, éteins la tv"
Là, ça éteint la box et la tv via la commande CEC. 
Une idée ?

**Comment by Aymkdn** [comment]
Est-ce que tu as une télé connectée déjà reconnu par Alexa ? Ça pourrait interférer.

Tu peux plutôt dire "Alexa, éteins la Freebox" plutôt que "éteins la TV", ce qui pourrait mieux marcher ?!

**Comment by bgfootspi** [comment]
Non, rien d'autre.
Et quand je dis : éteins la Freebox, il ne l'a reconnaît pas. Mais je crois
avoir changé le nom...

**Comment by Aymkdn** [comment]
Sans ton adresse mail je ne peux pas regarder ton compte. Tu peux changer le nom de la Freebox via le site https://assistant.kodono.info/freebox

**Comment by Aymkdn** [comment]
Pas de réponse, donc je clos ce ticket.

**Comment by bgfootspi** [comment]
Mon mail est resté en brouillon... Grrrr
Bref.
Mon mail : sbuffe@gmail.com

J'ai renommé comme demandé en Freebox au lieu de TV.

Rappel du problème :
La tv tourne depuis un moment
Je dis : Alexa, éteins la Freebox
La Freebox s'éteint mais se relance de suite et la tv ne s'éteint pas.
Une fois la Freebox revenue sur la tv, je re-dis : Alexa , éteins la
Freebox
Et la, la Freebox et la tv s'éteignent correctement.

Ma TV est une sharp 4k de 2015.
Le CEC est actif et fonctionne sans problème avec la télécommande.

**Comment by Aymkdn** [comment]
> J'ai renommé comme demandé en Freebox au lieu de TV.

Il faut le renommer dans l'application Alexa : dans "Appareils" > "Tous les appareils", assures-toi qu'il s'appelle bien Freebox.

Ensuite, j'ai regardé tes logs et je ne vois pas trace de demande pour éteindre la Freebox. Je vois que tu lui as demandé d'allumer la Freebox à plusieurs reprises, mais pas de l'éteindre…

Je t'invite à venir me parler sur le tchat (disponible sur https://assistant.kodono.info/freebox/). J'y suis en général de 9h à 19h en ce moment (avec une pause le midi), afin qu'on fasse des tests en direct.
