### ISSUE TITLE
Netflix via google home 

### ISSUE THREAD

**Issue by Arno276** [Aymkdn/assistant-freebox-cloud#104]
Bonjour, est il possible de créer une commande , pour pouvoir choisir un contenu netflix dans la freebox revolution , via le google home  .... 
Et bravo pour le travail fait !!!

**Comment by Aymkdn** [comment]
Bonjour,

Non, on ne peut pas aller jusque là malheureusement 😅 Le mieux qu'on puisse faire et d'ouvrir Netflix et c'est tout…

Merci pour les encouragements !
