### ISSUE TITLE
Allumer la Freebox

### ISSUE THREAD

**Issue by Xtoff06** [Aymkdn/assistant-freebox-cloud#105]
Bonjour,
je viens d'installer votre programme 
je trouve ça génial :)

parcontre j'ai un problème, quand je dit a google d'allumer la Freebox 
il l'allume bien mais reste sur la page d'accueil
j'ai essayai de cocher Freebox tv et mon bouquet 
les 2 ne fonctionne pas 

Merci beaucoup 

Cordialement 
Christophe

**Comment by Aymkdn** [comment]
Il y'a deux commandes vocales :
- Allume la Freebox
- allume la Freebox et zappe sur

C'est donc la deuxième qu'il faut dire.

**Comment by Xtoff06** [comment]
Effectivement il y a un petit temps de latence mais ça fonctionne avec la la commande "allume et zap"

Du coup on ne peut pas donc juste dire « ok google allume la Freebox » 
et que ça s’allume sur la dernière chaine regardé comme si on clic sur ok 

Une fois que j’ai la Freebox allumé sur le menu home 
Il y a t’il une commande pour aller sur  Freebox tv

Si je dit "zap sur X" il reste sur le menu Home  

Merci pour cette réponse rapide 

Christophe

**Comment by Aymkdn** [comment]
> Du coup on ne peut pas donc juste dire « ok google allume la Freebox »
> et que ça s’allume sur la dernière chaine regardé comme si on clic sur ok

Si, il faut utiliser `power,tv` au lieu de juste `power` dans la commande qui est envoyée. D'ailleurs je viens de modifier le site pour utiliser cette commande-là pour « Allume la Freebox » car ce n'est pas la première fois que les gens sont perturbés avec ça !

> Une fois que j’ai la Freebox allumé sur le menu home
> Il y a t’il une commande pour aller sur  Freebox tv

Pas de commande vocale pré-définie, mais en commande à envoyer c'est `tv` (je t'invite à [aller voir les autres commandes](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-personnalis%C3%A9es)).

> Si je dit "zap sur X" il reste sur le menu Home

Oui car il n'est pas (encore) assez intelligent pour savoir où il se trouve. Je travaille sur une nouvelle version qui corrigera ce problème (voir [cet autre issue](https://github.com/Aymkdn/assistant-freebox-cloud/issues/70)).

Je t'invite à répondre directement sur https://github.com/Aymkdn/assistant-freebox-cloud/issues/105 (plutôt que par email).

**Comment by Xtoff06** [comment]
Parfait 
Merci Beaucoup 
c'est top
