### ISSUE TITLE
changement de chaine Freebox avec Alexa

### ISSUE THREAD

**Issue by Xtoff06** [Aymkdn/assistant-freebox-cloud#106]
Bonjour,

Je n'arrive pas a trouver quelle phrase mettre dans "say a specific phrase" de l'IFTTT de Alexa 
puisque le "$" n'est pas accepté

et l'url doit finir que par "zappe" ?

Merci

**Comment by Aymkdn** [comment]
Alexa n'a pas besoin de IFTTT.... Seul Google Home en a besoin....

**Comment by Aymkdn** [comment]
> pour allumer la Freebox révolution avec Alexa, changer de chaine etc... pas besoin de créer des action sur ifttt et webhooks ?

Non pas besoin.

> pourquoi cette phrase ?
> `Vous pouvez créer vos propres actions grâce à IFTTT + Google ou IFTTT + Alexa, et en utilisant l'URL qui sera fournie ci-dessous après avoir sélectionné l'enchainement des commandes souhaitées.

C'est uniquement pour faire des commandes personnalisées – c'est-à-dire différentes [des commandes de base](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-vocales#pour-alexa).

Je suis dispo sur le tchat du site si vous voulez.

**Comment by Xtoff06** [comment]
donc quand je recevrai mes Alexa DOT pas besoin de faire quoi que se soit pour piloter ma révolution comme j'ai fait avec google home mini

**Comment by Aymkdn** [comment]
Il faudra activer la skill Assistant Cloud et c'est un peu près tout (en supposant que vous avez bien tout configuré sur votre compte)

**Comment by Xtoff06** [comment]
j'ai activé le skill et je pense qu'il est bien configurer puisque ça marche avec google

**Comment by Xtoff06** [comment]
du coup je peu supprimer ce que j'ai créé sur IFTTT pour Alexa

**Comment by Aymkdn** [comment]
Vous avez activé le skill dans l'application Alexa ? OK, et votre Freebox a été reconnue par Alexa ? Et donc quand vous lancez une commande à Alexa, ça fonctionne ?

> du coup je peu supprimer ce que j'ai créé sur IFTTT pour Alexa

Oui

**Comment by Xtoff06** [comment]
et pas besoin de dire "déclenche" du coup merci beaucoup désolé du dérangement

**Comment by Aymkdn** [comment]
> et pas besoin de dire "déclenche" du coup merci beaucoup désolé du dérangement

Non pas besoin. Voici les commandes vocales : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-vocales#pour-alexa

**Comment by Xtoff06** [comment]
ah oui ok c'est la ou il faut préciser "de la Freebox" pour quelle comprenne de quoi on parle 
c'est bon j'ai compris tout ça merci 
je devrai le recevoir bientôt mais je gagnais du temps pour la configuration 
du coup je vous dirai si tout marche bien quand je la recevrai

**Comment by Aymkdn** [comment]
OK bien ! Je ferme cette issue du coup :)
