### ISSUE TITLE
freebox radios

### ISSUE THREAD

**Issue by raphackermann** [Aymkdn/assistant-freebox-cloud#109]
bonjour,
ce lien fonction sous l'ifttt
https://assistant-api.kodono.info/fbx/OTI0OTsjNmE1ZmIyMA__/?c=musiques

puisqu'il n'y en a pas pour générer un saut vers la radio, j'ai tenté de remplacer par
https://assistant-api.kodono.info/fbx/OTI0OTsjhYmE1ZmIyMA__/?c=radios

mais ça ne fonctionne pas, pourquoi ? merci pour votre aide

**Comment by Aymkdn** [comment]
Car je n'ai pas créé de raccourcis pour aller dans les radios.

Je pourrais en créer un, mais probablement pas avant quelques jours.

**Comment by raphackermann** [comment]
merci pour la réponse rapide Effectivement, je commence à comprendre ton GROS boulot, ça donne envie d’en faire autant 😉 Pour remplacer le raccourcis direct, j’ai généré une chaine de commande « home, right, right,down,down,down,ok»  mais ça ne marche pas à tous les coups… problème d’enchainement des commandes? pas assez de temps entre les commandes?… c’est bizarre, les résultats semblent aléatoiresT’as une idée ?

**Comment by Aymkdn** [comment]
Essaie d'ajouter des wait entre certaines commandes en effet

**Comment by raphackermann** [comment]
Merci pour ton aide  le wait ne fonctionne pas : je change la valeur, je le change de place dans la chaine, j’en mets partout… rien n’y fait, rien ne se passe voici mon dernier essai avec du wait : free,wait125,home,wait125,right,wait125,right,wait125,down,wait125,down,wait125,down,wait125,okalors que :free,home,right,right,down,down,down,okfonctionne, mais souvent aléatoirement on t’a déjà remonté un problème avec le wait ?

**Comment by Aymkdn** [comment]
C'est inutile de mettre des wait de partout... Ça permet de faire une pause entre deux commandes. À toi de voir là où l'interface est la moins réactive.

Ensuite wait125 est beaucoup trop court... Ça représente une attende de 125 milliseconds ! Le minimum serait un wait2000

**Comment by Aymkdn** [comment]
Alors, je viens de tester, et ceci devrait marcher : 
home,wait3000,right,right,down,down,down,ok

**Comment by raphackermann** [comment]
je viens d’essayer plusieurs fois et ça passe à chaque foisbon, les 3 secondes se font sentir mais ça aboutit merci beaucoup

**Comment by Aymkdn** [comment]
Tu peux essayer avec deux secondes au lieu de trois.
