### ISSUE TITLE
Cloud, je peux changer les chaines, c'est tout

### ISSUE THREAD

**Issue by Lodoxx** [Aymkdn/assistant-freebox-cloud#11]
Bonjour

Merci encore pour la travaille.
j'ai testé les applets qui m’intéresses, le résultat, c'est que je peux changer que les chaines, sinon, baisser le son, descendre, couper, baisser, augmenter, allumer la freebox, l’éteindre, impossible.
Une idée du problème ?

Merci d'avance.

**Comment by Aymkdn** [comment]
J'ai transféré ton issue au bon endroit puis ça concerne la version dans le cloud !

**Comment by Lodoxx** [comment]
merci Aymkdn.
Oui mais dans Google Assistant, je suis obligé de rajouté le $, sinon, quand je clic sur "Create trigger"  j'ai ce message: **_! Use only one $ in your phrase._**

**Comment by Aymkdn** [comment]
Tu dois choisir "simple phrase" et pas "simple phrase with ingredient". Comme indiqué dans le guide.

**Comment by Lodoxx** [comment]
Ok, je me suis fié au tuto vidéo, ou le choix est "simple phrase with ingredient".
Je teste, merci, a+

**Comment by Lodoxx** [comment]
C'est ok, ça fonctionne.
Merci !

**Comment by Aymkdn** [comment]
Cool!
