### ISSUE TITLE
Peut ouvrir Netflix ? Ou autre application (Youtube, Twitch...)

### ISSUE THREAD

**Issue by TapsHTS** [Aymkdn/assistant-freebox-cloud#110]
Est-ce possible d'ouvrir ces applications ?

**Comment by Aymkdn** [comment]
Netflix s'ouvre avec la commande vocale "zappe sur Netflix"

Cette commande vocale marchera bien pour la Freebox Révolution, et peut être plus aléatoire pour la Delta et One, en particulier si l'interface a été personnalisée. Mais je travaille sur une meilleure solution (comme expliqué là : https://github.com/Aymkdn/assistant-freebox-cloud/issues/70#issuecomment-626207108) 

Quant aux autres applications, non, elles ne sont pas prises en charge, mais il te suffit de créer tes propres commandes pour pouvoir le faire.
Si tu utilises Google : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Cr%C3%A9er-une-applet-IFTTT-pour-Google 
Si tu utilises Alexa : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Cr%C3%A9er-une-applet-IFTTT-pour-Alexa

**Comment by TapsHTS** [comment]
D'accord merci beaucoup
