### ISSUE TITLE
problème avec les commandes

### ISSUE THREAD

**Issue by Karamir-dev** [Aymkdn/assistant-freebox-cloud#112]
j'ai installer les applet pour les commande de base que tu propose et seul la commande pour éteindre la freebox fonctionne.

**Comment by Aymkdn** [comment]
Peux-tu me contacter par email ou sur le tchat ? Afin que je connaisse ton email et que je puisse regarder ton compte.

**Comment by huguesW** [comment]
bin je ne trouve pas ton email mais voici l'adresse du compte koryndumont@live.fr

**Comment by Aymkdn** [comment]
Je ne trouve aucun compte avec cet email. Je te contacte par mails pour voir ça… Sinon je suis sur le tchat https://assistant.kodono.info/freebox/ ce matin !
