### ISSUE TITLE
Simulation du bouton Netflix et l'utiliser comme bouquet tv au demarrage

### ISSUE THREAD

**Issue by HardyCheil** [Aymkdn/assistant-freebox-cloud#114]
Est ce que ce serait possible? 
Je me suis desabonné de l'offre tele et j'utilise que netflix/prime sur ma freebox

Les options sur la gestion du assistant permet seulement de connecter à freebox tv/mon bouquet/canal au demarrage.

Toutes mes excuses en avance pour mon français pourri.

**Comment by Aymkdn** [comment]
Avec Alexa il faudra créer une commande personnalisée pour cela : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Cr%C3%A9er-une-applet-IFTTT-pour-Alexa

La commande à associer sera `netflix`

**Comment by HardyCheil** [comment]
Tout a fait je l'ai deja fait et ca marche bien.

La probleme se produise au demarrage de la box, comme sur les options dans https://assistant.kodono.info/freebox/ on peut choisir que freebox tv/mon bouquet/canal et si on n'a pas une abonnement tele la box va essayer a nous abonner a la tele (avec PIN et tous ça) chaque fois qu'on l'allume avec alexa. 

L'option de tombe sur Netflix au demarrage serait top.
Au pire, l'option de ne rien faire apres allumage de la box serait bien.

**Comment by Aymkdn** [comment]
Ah, oui je comprends... C'est un cas très particulier ^^

Là encore vous pourriez créer votre propre commande vocale avec la commande `power` (qui va allumer la Freebox si éteinte, ou l'éteindre si allumer) une attente de quelques secondes avec `wait7000`, puis un `netflix` et même un `ok` après si vous n'utiliser qu'un compte Netflix.

**Comment by HardyCheil** [comment]
Merci pour tout !

Parfait!

Par contre, le bouton hardware de la telecommande 'netflix' est elle dispo comme les autres ? 
Il serait plus 'clean' d'activer netflix comme ca...

**Comment by Aymkdn** [comment]
Non, pas disponible... L'API de Free est super vieille et Netflix n'existait pas à l'époque.

Je suis en train de travailler sur une alternative mais qui n'est pas simple à mettre en place : https://github.com/Aymkdn/assistant-freebox-cloud/issues/70#issuecomment-626207108

**Comment by HardyCheil** [comment]
https://dev.freebox.fr/sdk/freebox_player_codes.html ?

**Comment by Aymkdn** [comment]
Non, ce n'est pas ça. Cette API là est pour du local.

**Comment by Aymkdn** [comment]
Et perso je n'ai jamais compris comment cela fonctionnait. Donc si tu sais implémenter ça avec des technologies comme JS et PHP depuis un serveur distant, je suis tout ouï ☺️
