### ISSUE TITLE
Commande "Couper le son de la TV" ne fonctionne pas

### ISSUE THREAD

**Issue by bvwclara** [Aymkdn/assistant-freebox-cloud#115]
Bonjour,

Déjà merci beaucoup, ça fonctionne globalement très bien.
J'ai juste un problème, la commande "Couper le son de la télé" ne fonctionne pas, google me dis que je n'ai pas d'appareil connecté.
Ce qui est bizarre c'est que la commande "couper le son de la Freebox" fonctionne parfaitement et pourtant j'ai ajouté la seconde phrase dans la rubrique "What's another way to say it? (optional)" du même applet. Je ne comprends donc pas pourquoi cela ne fonctionne pas.
Ce n'est bien sur pas indispensable mais j'aurais tout de même aimé savoir ce qui cause cette anomalie.

Autre question. Le son semble augmenter (ou baisser) de 15 point, y a t-il un moyen de changer cela pour augmenter ou baisser par série de 5 point? 

Merci

**Comment by Aymkdn** [comment]
> Je ne comprends donc pas pourquoi cela ne fonctionne pas.

**Comment by Aymkdn** [comment]
> Je ne comprends donc pas pourquoi cela ne fonctionne pas.

Essayez de le dire à Google Assistant sur votre téléphone pour voir comment Google reconnaît / écrit la phrase, puis assurez vous d'utiliser exactement la même écriture dans l'applet IFTTT ! 

> Le son semble augmenter (ou baisser) de 15 point, y a t-il un moyen de changer cela pour augmenter ou baisser par série de 5 point?

Vous pouvez modifier l'applet qui augmente le son et remplacer "volumeUp" dans l'URL par "vol_inc*5". Enfin ça dépend... Si vous utilisez un home cinéma alors ça ne va pas bien fonctionner car c'est "un appui long" qu'il faut faire normalement....
