### ISSUE TITLE
site IFTTT

### ISSUE THREAD

**Issue by ghost** [Aymkdn/assistant-freebox-cloud#116]
bonjour
c est dommage car site IFTTT est maintenant payant donc pour utiliser l assistant vocal avec la freebox revolution c est plus d actualite , peut etre y a t il un autre moyen de le faire

**Comment by Aymkdn** [comment]
En effet, comme indiqué sur mon site : 
![Capture](https://user-images.githubusercontent.com/946315/94168325-cd834f00-fe8d-11ea-903e-e48f942083b4.PNG)

J'étudie deux solutions actuellement : 
1. Avoir la Freebox dans Google Home directement – ça fait 2 mois que je me "bats" avec Google pour qu'ils acceptent mon service dans Google Home… Je les ai encore relancé aujourd'hui… je garde l'espoir que ce soit publié avant le 7 octobre afin que j'explique à tout le monde comment migrer sur l'application Google Home directement au lieu de passer par IFTTT
2. La solution de repli est que je paie 200$/an pour avoir un compte développeur chez IFTTT qui me permettra de publier des applets que vous pourrez ensuite utiliser gratuitement (même sans compte pro)… Mais du coup ça va me faire dépenser 200$/an pour un service que je fournis gratuitement 👎 

Voilà. Je croise les doigts pour que Google accepte mon service car ça résoudrait pas mal de soucis !
