### ISSUE TITLE
Routine

### ISSUE THREAD

**Issue by Magano91** [Aymkdn/assistant-freebox-cloud#119]
Est-il possible de créer une routine en cumulant les ordres ?
Je sais allumer la Freebox et ma télé avec une routine, pas de problème.
Mais je voudrais cumuler les actions suivantes :
Allume la télé
Mets la Freebox sûr M6
Mets sur pose.
Tout ça avec une routine et chaque ordre décaler de 30sec.
Merci pour votre aide 😉

**Comment by Aymkdn** [comment]
Il faut séparer chaque commande par une virgule. Je vous invite à vous reporter à la documentation exemple : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Cr%C3%A9er-une-applet-IFTTT-pour-Google

Revenez vers moi si vous avez des questions !

**Comment by Aymkdn** [comment]
Et toutes les commandes disponibles sont listées sur https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-personnalis%C3%A9es

**Comment by Magano91** [comment]
Bonjour Aymeric,
merci pour tout ce que vous faites, et merci pour votre réponse rapide, ça
marche !
je vais contribuer pour vous aider.
