### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#12]
Bonjour, tout d'abord félicitations au développeur c'est un sacré boulot! Si j'ai bien compris ceci n'est pas compatible Alexa et les avec les Amazon Écho etc... Est il possible d'aider de quelque manière pour ce projet ? Xander

_Originally posted by @Xanderyuku in https://github.com/Aymkdn/assistant-freebox-cloud/issues/9#issuecomment-473825235_

**Comment by Aymkdn** [comment]
@Xanderyuku j'ai créé ta propre issue car ça n'avait rien à faire dans l'autre...

Le projet est en phase de tests car il n'a débuté que la semaine dernière. J'attends de voir le comportement avec le Google Home et les 150 utilisateurs déjà inscrits.

J'utilise IFTTT pour connecter le Google Home à ce service. Alexa permet de faire la même chose mais son utilisation avec IFTTT est un peu différente. J'aimerais voir si un Skills Alexa serait plus adapté ici. Je dois donc prendre un peu plus de temps pour étudier la question et tester Alexa.

En résumé : 
1) J'attends de voir si le serveur supporte les utilisateurs Google Home pour commencer (et fixer tous les bugs qui peuvent être trouvés)
2) Parallèlement j'étudie la méthode qui me semble la plus adaptée pour utiliser ce service avec Alexa

Donc ça va venir.

**Comment by Xanderyuku** [comment]
Je comprends parfaitement, est il possible de t'aider d'une manière boulot d'une autre sur ce projet ? Des tests, je code un peu pour le plaisir surtout pour le boulot mais dans un domaine complètement différent ^^.

**Comment by Aymkdn** [comment]
Merci mais pour le moment ça va 😉

**Comment by dorber2008** [comment]
Bonjour et bravo pour le boulot !!!!
Certaines commandes fonctionnent parfaitement sur Delta ! Même mieux que ok Freebox !!! ;)
De plus j'ai testé : "mets le volume à # " et ça fonctionne nickel ! 
# = niveau de volume. Exemple: volume à 30%

**Comment by Aymkdn** [comment]
Voir https://github.com/Aymkdn/assistant-freebox-cloud/issues/41
