### ISSUE TITLE
probleme de commande

### ISSUE THREAD

**Issue by ghost** [Aymkdn/assistant-freebox-cloud#120]
bonjour
j ai plusieurs appareil de connecter sur mon assistant google , mais truc bizarre j allume ma lumiere de salon par ok google allume le salon et ca fonctionne mais si je veux l etteint si je dis ok google etteint le salon la il m etteint ma freebox ce qui est bizarre, je sais que pour mon salon je dois dire ok google coupe le salon mais bon si je dit ok google etteint et une choses qui n existe pas et me coupe la freebox ca aurait ete bien de dire ok google etteint la freebox

**Comment by Aymkdn** [comment]
Je suppose que tes lampes et la Freebox sont dans la pièce "salon". Donc quand tu dis « OK Google, éteins le salon », il va demander à tous les appareils qui se trouvent au salon de s'éteindre.

Donc faudrait plutôt dire « OK Google, éteins la lumière du salon » peut-être ?

**Comment by ghost** [comment]
oui dans la meme piece , je testerais ca

**Comment by Aymkdn** [comment]
C'est pas vraiment un problème lié à Assistant Cloud donc je ferme ce ticket, mais tu peux me poser des questions ici si besoin, ou sur le tchat de https://assistant.kodono.info/freebox/
