### ISSUE TITLE
commande : stop

### ISSUE THREAD

**Issue by flimo44** [Aymkdn/assistant-freebox-cloud#121]
Bonjour,
Depuis la nouvelle version le "Ok google stop ou arrêt, annule..." à pour effet un appui sur la touche Rouge de la Freebox. ( ex: quand je regarde une chaine il passe sur la chaine regardé précédemment )

Conséquence, mon google home n'interprète plus le commande stop ou arrête :/ ce qui est très gênant.
Donc si je met la radio , la music .... ça devient compliquer voir impossible d'arrêter sans parfois débrancher le google Home.
Je n'ai plus IFTT d'associé à mon GH.

**Comment by Aymkdn** [comment]
C'est parce qu'il n'y a pas de commande "stop" avec la Freebox. L'équivalent est la touche rouge lorsque vous regardez une vidéo.

La plupart des gens disent "OK Google, arrête la Freebox" pour l'éteindre, sauf que Google fait une demande de "stop" avec cette commande, du coup c'est pas simple à gérer. 

Si vous avez activé les fonctionnalités avancées (https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Les-fonctionnalit%C3%A9s-avanc%C3%A9es,-c'est-quoi-%3F) alors mon système vérifie si vous êtes en train de regarder un enregistrement vidéo et dans ce cas va envoyer un "red" pour sortir de la vidéo, dans les autres cas ça va éteindre la Freebox. 

Free a fait l'ébauche d'une API pour gérer la lecture (https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Player-API#contr%C3%B4le-de-la-lecture) mais malheureusement ils ne l'ont pas rendu disponible sur Freebox Révolution pour le moment... J'ai ouvert un ticket https://dev.freebox.fr/bugs/task/32407 mais ils s'en foutent de la Révolution désormais. 

 Je suis ouvert à toute suggestion.

> Conséquence, mon google home n'interprète plus le commande stop ou arrête 

Je n'ai pas compris ce passage ? Normalement si vous jouez de la musique sur le Google Home et lui dites "stop" il va arrêter la lecture de la musique. Ou alors vous lui dites "arrête la musique" ou "arrête Spotify" ou "tais toi" ou "ta gueule". 
Pour que ce soit envoyé à la Freebox il faudrait que vous dites "stop la Freebox" ou bien que vous demandiez une commande liée à la Freebox peu de temps avant, genre "OK Google, allume la Freebox" puis quelques minutes après vous lui dites "stop" alors il va interpréter que c'est pour la Freebox (en supposant que vous avez demandé la musique avant de lancer la Freebox). 

Par contre depuis quelques semaines j'ai remarqué que Google Home n'arrive pas toujours à arrêter ma musique Spotify, mais le problème n'est pas lié à la Freebox mais à Google Home qui merde. Du coup je suis parfois obligé d'ouvrir l'application Google Home, de cliquer sur mon device, puis d'arrêter la diffusion de la musique (vous pourriez faire pareil plutôt que de le redémarrer).

**Comment by flimo44** [comment]
Bonjour,
Comment savoir si les fonctionnalités avancé sont bien activé :/
Tout semble bien configuré sur l'application freestore.

![image](https://user-images.githubusercontent.com/33300032/104095484-597f8200-5297-11eb-8dea-17550b67f9f8.png)

J'ai cet écran chaque fois que je clic sur vérifier. J'ai donc un doute vu que le bouton vérifier est bien Vert....

Concernant le Google Home si j'écoute de la musique impossible de l'arrêter , j'ai testé toute les commandes que tu as donné même les insultes.

A chaque fois c'est ça me zappe les chaines sur la chaine précédente. Si je regarde la 6 il zappe sur la 2 puis à nouveau la 6 ..... 
Donc un simple stop sans préciser sur la freebox est envoyé sur la freebox et le GH reprend la ou il était et remet donc la music.

**Comment by Aymkdn** [comment]
Comme je n'ai pas ton e-mail je ne peux pas vérifier ton compte. Mais tant que tu as ce message c'est que ce n'est pas bon.
Quand tu lances l'application du Freestore, utilise le bouton "Supprimer" qui apparaît à la fin du message, puis relance l'application. Cela te demandera ton code d'activation qui est visible sur ton profil. Et si tu as installé l'application il y a longtemps (genre plus de 6 mois ou 1 an), normalement une mise à jour a dû t'être proposée, si non, supprime l''application et réinstalle la pour être sûr d'avoir la dernière version. 

Pour la Google Home si tu lui dis "arrête la musique", alors il répond quoi ?
Et tu me dis que ça fait un "red" sur la Freebox alors que tu lui as dit d'arrêter la musique ?! Ça n'a pas de sens... Je n'ai pas constaté ce problème chez moi et personne ne m'a remonté ça encore....

**Comment by flimo44** [comment]
J'ai bien eu la mise à jour que j'ai installé Hier. Je vais tenter de supprimer et réinstaller

**Comment by Aymkdn** [comment]
On voit ça sur le tchat, ça sera plus simple.
