### ISSUE TITLE
Le nom des chaînes n'est plus reconnu

### ISSUE THREAD

**Issue by NinaPop** [Aymkdn/assistant-freebox-cloud#122]
Bonjour !

Configuration :
- FreeBox Revolution
- Google Home

Je ne peux plus utiliser que les numéros des chaînes, quelle que soit la chaîne.
Exemple :
- "Zappe sur Arte" ==> le Google Home répond "je ne comprends pas"
- "Zappe sur la 7" => ça fonctionne.
Pas mieux en spécifiant "sur la Freebox"

C'est apparu il y a 2 jours environ, ça fonctionnait très bien avant.
Une idée ?
Merci d'avance :-)

**Comment by Aymkdn** [comment]
Bonjour.

alors, c'est assez curieux car suite à ton message, j'ai essayé sur ma Freebox et j'ai en effet eu Google me disant qu'il ne comprenait pas… Du coup j'ai commencé à fouiller mon code, la documentation de Google, etc… Puis j'ai retesté, et cette fois ça a marché avec les mêmes chaines / commandes vocales testées avant… !

Là je réessaie en disant "OK Google, mets Arte sur Freebox", et il me dit "excusez-moi je ne sais pas sur quel écran je dois lire la vidéo. Pouvez-vous me dire le nom exact de l'écran ?"… Et si je lui dis "zappe sur Arte sur Freebox", il me répond "je n'ai pas compris", alors que 2 minutes avant ça marchait.

J'ai poursuivi mes tests et en fait il semble que cela ne fonctionne que si la Freebox est allumée. Si j'allume la Freebox et que je demande une chaine, ça fonctionne sans soucis. Quand la box est éteinte, il me dit qu'il ne comprend pas…

Par contre demander un numéro de chaine lorsque la box est éteinte, fonctionne…

Je pense donc que Google a changé la façon d'interpréter les commandes ! Est-ce un bug ou est-ce voulu de leur part ? Difficile à dire… Je vais essayer de les contacter, mais là aussi pas simple !

**Comment by Aymkdn** [comment]
J'ai ouvert un ticket chez Google : https://issuetracker.google.com/issues/180021380

**Comment by NinaPop** [comment]
Merci :-)
Alors j'avais évité de faire un roman feuilleton en première intention, mais oui, depuis quelque temps Google s'emmêle les octets pour décider ce qu'il doit faire avec le multimedia.
Par ex, souvent, il ne comprend plus "mets France Inter" ; en revanche "mets France Inter sur tunein" fonctionne, et "mets Radio France" lance... France Inter. Tout ceci étant bien entendu légèrement aléatoire.

Ce matin, "zappe sur SerieClub sur freebox"==> OK (qu'on spécifie ou non "freebox"), mais Arte ou National Geographic ==> NOK.

Je viens de constater un truc intéressant :  "zappe sur France Info sur Freebox" met bien la chaîne TV FranceInfo, mais "zappe sur FranceInfo" lance... une playlist d'actualités nationales standard de Google (flash, revue de presse, etc), directement sur la Google Home. Mais si à ce moment je dis "OK Google, stop", pour arrêter cette radio, il éteint... la Freebox. Je suppose donc qu'à la base il a compris que "zappe" impliquait la Freebox, et qu'il s'est ensuite perdu en route.

Bref bon courage, bonne journée et merci !

**Comment by grillead** [comment]
> J'ai ouvert un ticket chez Google : https://issuetracker.google.com/issues/180021380

@Aymkdn Le problème viendrais bien de google je constate le meme soucis avec ma version pour la pop depuis ce matin ( avec applet ifttt ) la commande et bien comprise avec la bonne syntaxe mais appriori google ne vas pas piocher ses réponse en externe.

**Comment by grillead** [comment]
@NinaPop et @Aymkdn ca remarche chez vous ? Je viens de refaire le test chez moi apres avoir demander a l assistant via mon téléphone et ca a marché, du coup j ai tenter via mon home mini il a bien zapper sur la chaine demandée (alors qu'une heure avant il m envoyais sur youtube... )
Peut etre un test a faire si ca ne marche pas de passez via l'assistant google android pour voir si le fonctionnement et pareil ?
Bon weekend 😉

**Comment by NinaPop** [comment]
@grillead National Geographic OK, Serie Club NOK y a 2 mn, maintenant tout NOK.
Ce matin mon home mini était même infichu de répondre à "mets France inter" entre "je ne comprends pas" et "je ne trouve pas de chromecast pour lire cette video" (WTF ???)
j'ai interpellé googlenest sur twitter, pas de réponse pour l'instant, je tenterai le support demain.

Ca me pompe l'air, normalement je vends mon âme à Google en toute conscience et en échange de trucs qui fonctionnent impec, mais là ça va plus du tout 😉

Bon WE !

**Comment by Aymkdn** [comment]
Je confirme que quand je demande à Google Assistant ça fonctionne mais pas sur mon Google Home.

**Comment by NinaPop** [comment]
"zappe sur la 6" ==> "la possibilité de choisir des titres est réservé aux abonnés de Spotify premium..." 
🤣 🤔

**Comment by grillead** [comment]
Je propose d ouvrir un ehpad reserver au google home , le miens deviens de plus en plus sénile, je dois crier ok google sinon il entend rien 😂

**Comment by NinaPop** [comment]
J'ai discuté avec le support Google. 
Sur le thème des merdoyages de radio, qui est plus mainstream que Kodono 😉 , mais je suis relativement convaincue qu'il y a un rapport. Ne serait-ce que parce qu'avec un Nest fraîchement réinitialisé, la radio fonctionne impec, mais après la première interaction avec la FB ça fait n'importe quoi, et j'ai un vague soupçon que ce n'importe quoi peut aussi se produire chez les gens qui ont des TVs connectées diverses (certes, je peux me gourrer)

Quand je dis n'importe quoi, c'est :
![image](https://user-images.githubusercontent.com/78885534/107984557-71e66900-6fc8-11eb-8aa4-e52863b7ed19.png)

Bonne nouvelle, ça les intéresse car je ne suis pas la seule, donc voici la manière de faire un signalement dans les règles sur ce thème précis:

_Le support technique été notifié la semaine dernières de quelques contacts des utilisateurs à ce sujet, nos développeurs sont au courant et cherchent actuellement l'origine du problème afin de le corriger au plus vite par une mise à jour prochaine, ou pour déterminer si cela viendrait de notre côté ou de celui du service TuneIn.
En attendant, nous vous invitons à partager un rapport de diagnostic avec nos équipes afin de fournir des informations sur le bug qui vous atteint, en le faisant se reproduire une paire de fois, puis en envoyant un commentaire au travers de l'application Home comme suit: https://bit.ly/2KEsZKY, et en y insérant comme message l'expression: "GHT3 Fails to play radio stations [ NOMS DES RADIOS] on TuneIn", cela le redirigera automatiquement à l'équipe correspondante et leur permet souvent de comparer les rapports reçus et d'en identifier la  #source!_

Bonne soirée !

**Comment by Aymkdn** [comment]
@NinaPop : tu peux testerde dire « zappe sur TF1 » quand la Freebox est éteinte au lieu de « mets TF1 », et de me dire si ça fonctionne ? Car chez moi le « mets » ne fonctionne pas, mais le « zappe » fonctionne…

**Comment by NinaPop** [comment]
@Aymkdn Ben là Kodono est désactivé, j'ai tjs le pb de communication avec la FB (qui ressemble à un pb d'authentification chez toi, je creuse demain)
Mais de tte manière, je dis à peu près toujours "zappe", je pensais même que c'était le mot clé qui orientait la requête vers la FB

**Comment by NinaPop** [comment]
@Aymkdn J'ai réussi à réassocier la FB. Y a 3 jours, je n'accédais pas àla page d'authentification, et là ça a fonctionné.
Donc :
![image](https://user-images.githubusercontent.com/78885534/108551530-5fce3880-72f0-11eb-8814-36634809c5fd.png)

Pour les 2 1ères commandes, la FB était éteinte, la 3ème l'a allumée 'et mis TF1
Ensuite :
![image](https://user-images.githubusercontent.com/78885534/108551853-cbb0a100-72f0-11eb-9a8d-7aa4ce539c06.png)

Et bien entendu :
![image](https://user-images.githubusercontent.com/78885534/108551994-ff8bc680-72f0-11eb-8a0a-2f42e6a23db1.png)
(et je m'aperçois que j'ai des commandes en double, elle doit être en double qq part, comme d'hab)

**Comment by grillead** [comment]
Je sais pas pour vous mais pour ma part mmon mini a retrouver ses esprits depuis 24/48h environs, vous etes en version beta sur le mini ou release classique ?

**Comment by Aymkdn** [comment]
Ah ? Cool !
Je suis en version classique.

**Comment by NinaPop** [comment]
classique, 1.50.229149

**Comment by grillead** [comment]
Idem pour moi niveau version "CAST" , en FW systeme j ai la version 229149 (je suis dans le program preview)

**Comment by NinaPop** [comment]
Mon Nest est tjs aussi paumé...
![image](https://user-images.githubusercontent.com/78885534/109056858-49095680-76e1-11eb-992c-b5a43e61995f.png)

**Comment by Aymkdn** [comment]
Ouais.... Moi pareil. J'ai mis la preview mais j'ai pas noté de changement 🤷🏼‍♂️

**Comment by Aymkdn** [comment]
@NinaPop et @grillead si vous pouviez poster un message dans https://issuetracker.google.com/issues/180021380 ? Question de les relancer un peu :-)

J'ai plusieurs applets IFTTT aussi qui déconnent totalement : Google ne les comprend pas et je suis obligé de les activer/désactiver régulièrement… Depuis quelques semaines mon Google Home a vraiment du mal à comprendre, et prend beaucoup de temps pour répondre !

**Comment by Aymkdn** [comment]
Aujourd'hui il n'y a plus aucune commande de changement de chaine qui fonctionne… 😡

**Comment by hubertlejaune** [comment]
Si jamais, avec Alexa sur la Pop ça fonctionne

**Comment by Aymkdn** [comment]
Oui c'est un problème de Google... Plusieurs commandes merdent... Puis pour les joindre c'est compliqué 😕

**Comment by seb60500** [comment]
Plus aucune commande ne fonctionnent sur google home

**Comment by Aymkdn** [comment]
Je viens de tester et ça semble fonctionner ce matin.

@seb60500 va sur https://assistant.kodono.info/freebox/ et la vérification automatique va checker ton compte et t'indiquer le problème (tu as peut-être un soucis de configuration). Je serai sur le tchat si tu veux parler.

**Comment by Aymkdn** [comment]
Si vous avez loupé la réponse du développeur de Google : 
> Yes, this is internal device targeting logic change. We try to not target device that is "unqualified" and device being offline is considered "unqualified". However, I ack here that the query explicitly mentioned the target device name, so the query should at least reply with some more meaningful TTS.

Donc en gros, c'est une modification voulue par les développeurs de Google, car ils considèrent que si l'appareil est éteint alors on ne peut pas changer de chaine… J'ai répondu que ce n'était pas à eux de décider ça ! Bref, la seule modification qu'ils vont peut-être faire, est de mettre un message d'erreur plus explicite 👎 

Je ferme cette issue car de toute façon c'est hors de mon contrôle à ce niveau.
