### ISSUE TITLE
Enchainement de commande

### ISSUE THREAD

**Issue by Gouzy35** [Aymkdn/assistant-freebox-cloud#123]
Bonjour, 
Sur environnement Freebox / Alexa, j'ai tenté d'envoyer plusieurs commandes (3) mais il semble que seule la premiere passe...
https://assistant-api.kodono.info/fbx/MY CODE/?c=power,1,play

j'ai intercallé des WAIT mais pas de résultat non plus...

Auriez vous une idée ?

merci, et bravo pour ce tuto !

**Comment by Aymkdn** [comment]
Que cherches-tu à faire exactement ? Là ça va allumer la Freebox et directement envoyer un "1", puis un "play", donc en gros ça ne va rien faire, puisque 'power' a besoin de plusieurs secondes pour que la Freebox s'allume (jusqu'à 7 secondes), et ça va atterrir sur la home de ta Freebox donc le '1' ne va rien faire non plus, ni le 'play'.

Si tu cherches à mettre TF1 puis à mettre sur pause, et en sachant que tu as activé les fonctionnalités avancées, alors tu pourrais essayer : 
`https://assistant-api.kodono.info/fbx/TON_CODE_SECRET_À_NE_PAS_PARTAGER/?c=zappe sur 1,wait5000,pause`

**Comment by Gouzy35** [comment]
Merci pour le retour (j'ai effacé mon code secret.... merci pour l'indication... !!!!)
Je cherche à allumer la freebox, mettre la une, puis pause
J'avais mis des temporisations (wait) mais cela ne répond pas, ni ta commande en proposition - Il faut que je check ma paramétrie car seule les commandes "par défaut" semble fonctionner (les fonctionnalités avancées sont activées pourtant)

**Comment by Gouzy35** [comment]
Trouvé ! Le probleme était entre Alexa et la Freebox !!! :)
En fait pb de routine envoyée à Alexa que j'ai modifié - Depuis tout fonctionne
Un grand merci pour votre support et patience !

**Comment by Aymkdn** [comment]
Cool!
