### ISSUE TITLE
les chaines Freebox

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#124]
@Aymkdn Salut, hier l arraigné a gratter du coup j ai repris mon code pour la liste des chaines, et j ai trouvé une solution pour evité la base sql en interrogeant directement l api freeboxtv du serveur et je procede a la réecriture de certaine chaine directement dans le fichier php en charge de la recherche et du zapping des chaines :)
Si jamais tu peut jeter un oeil sur mon git(freeboxjson.php), pour le moment le fichier est en pull request le temps de tester chez moi ;)

_Originally posted by @grillead in https://github.com/Aymkdn/assistant-freebox-cloud/issues/117#issuecomment-794235363_

**Comment by Aymkdn** [comment]
Pour éviter de trop faire du hors sujet dans l'autre _issue_, j'en crée une dédiée.

> Si jamais tu peut jeter un oeil sur mon git(freeboxjson.php), pour le moment le fichier est en pull request le temps de tester chez moi  

J'ai regardé vite fait et ça me semble correct. Le fait que tu exécutes l'appel à chaque fois est peut être un peu dommage, et un système de cache pourrait légèrement améliorer les performances (les chaines sont rarement changées).

Si ça va fonctionner avec la majeure partie des chaines, il n'est pas impossible que certaines chaines ne soient pas bien reconnues selon comment Google va les interpréter et les envoyer à IFTTT (j'ai déjà vu la même chaine écrite différemment, par exemple "game one plus 1", "game one+un", "game one plus", "game one plus un", etc etc ou encore "TF1", "tf un", "TF1 SD", "TF1 HD", etc …). La compréhension de Google variant selon deux utilisateurs différents !

Bref, dans 95% des cas je pense que ça sera bon ;-)

**Comment by grillead** [comment]
Yes je vais checker chez moi justement en cas de non retour ce que google as envoyer et editer le fichier pour la réécriture.
Apres concernant les perf, perso pour le moment je n ai pas constaté de différence entre la base sql et l interro api, en gros il met entre 1 et 2s max entre la fin de ma phrase et le zapping

**Comment by Aymkdn** [comment]
OK :-)

Je vais fermer cette _issue_, mais du coup si tu as d'autres questions en rapport aux chaines, je t'invite à les poster ici !

**Comment by Aymkdn** [comment]
Pour info, il y a maintenant ça de disponible : https://www.free.fr/data-json/freebox-tv/channels.json qu'on retrouve via le site dédié https://www.free.fr/freebox/freebox-tv/

**Comment by grillead** [comment]
@Aymkdn Je vais regarder ca, ca peut etre pratique en effet vu que les chaines et les numeros sont dans le meme json ca evite de recherche l uuid et ensuite chercher le numeros via l uuid dans l autre json
