### ISSUE TITLE
Google Home Multi compte

### ISSUE THREAD

**Issue by Tugqis79** [Aymkdn/assistant-freebox-cloud#125]
Bonjour
Depuis le passage sur Google Home, ma femme ne ne peux plus piloter la freebox, je suis le seul.
Comment puis-je faire pour régler le problème ?

**Comment by Aymkdn** [comment]
Ouvrez l'application Home sur son téléphone pour voir si la Freebox est présente. Si non, il faudrait installer Kodono Smart Home dans le Home de votre femme en vous connectant à votre compte.

**Comment by Tugqis79** [comment]
L'ajout de la freebox ne fonctionne pas. je suis sur une "maison" avec plusieurs membres dans Google Home. Mais j'ai bien la freebox dans les périphériques Google Home de son compte

**Comment by Aymkdn** [comment]
La Freebox apparaît donc bien dans ses périphériques quand tu regardes son application Home ? Et quand tu ouvres la Freebox sur son téléphone dans Home, tu arrives à l'allumer / éteindre en cliquant sur le bouton ? Est-ce que les autres appareils connectés fonctionnent avec elle ? 

On ne m'a jamais rapporté ce problème et je dois avouer qu'il n'y a que moi qui demande des choses à Google pour la Freebox à la maison... Là on est en vacances, pas chez nous, donc je ne peux pas tester. On rentre dans 8 jours donc je pourrai faire des essais à notre retour. Je te tiens donc au courant fin de semaine prochaine !

**Comment by Tugqis79** [comment]
Ré,
Je te confirme que je peux allumer le player depuis son compte. 
Passe de bonne vacances,
À bientôt

**Comment by grillead** [comment]
@Tugqis79 Soit un petit probleme de voicematch et il faut refaire l'apprentissage, soit un pb de synchro et la au pire tu peut demande à ta femme de tenter la phrase magique "ok google synchronique mes equipements" et si KO de refaire l apprentissage voicematch

**Comment by Tugqis79** [comment]
@grillead On a refait Voice match et la synchro des équipements. Mais quand elle demande de zapper sur la 10 par exemple, ça zappe sur YouTube.

**Comment by Aymkdn** [comment]
Même en disant  « sur Freebox  »?

 « mets la 10 sur Freebox  »

**Comment by grillead** [comment]
@Tugqis79 et en vocal depuis le tel ca marche ?
@Aymkdn on dirais le meme genre de soucis que @ninapop et moi aussi de temps à autres, les appareil google sont à la rue mais l'assistant dans android lui a les idées clair, je viens d investir dans un nest hub je l'ai mis en route a midi idem il lance youtube de temps en temps au lieu de la tv...

**Comment by Tugqis79** [comment]
S'il elle précise sur freebox ça fonctionne. Mais dans ce cas pourquoi moi je n'ai pas besoin de dire sur freebox ?

**Comment by Aymkdn** [comment]
Peut être qu'elle a un compte YouTube configuré et toi non, ou autre....dur de savoir comment Google gère ça.... 

Je peux donc fermer cette issue ?

**Comment by Tugqis79** [comment]
@Aymkdn
Oui, merci à tous pour l'aide.
