### ISSUE TITLE
Je cherche des personnes ayant des Freebox Mini 4K

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#126]
Bonjour,

Dans le cadre des tests, j'aurais besoin de personnes ayant la Freebox Mini 4K. Je n'ai actuellement pas assez de testeurs…

Si vous lisez ce message, merci de me contacter sur assistant@kodono.info

Merci

**Comment by woctezuma** [comment]
Bonjour,

Je vois qu'il est question de Freebox mini 4K ici, ainsi que dans :
- #66 
- #93 
- #117 

J'ai trouvé cette page après avoir constaté que le Wiki mentionnait que la Freebox mini 4K n'était pas supportée :
- https://github.com/Aymkdn/assistant-freebox-cloud/wiki/%C3%89ligibilit%C3%A9

Personnellement, j'ai une Freebox mini 4K ainsi qu'une enceinte Echo Dot (5ème génération, année 2022). J'ai essayé de suivre la procédure sur le site https://assistant.kodono.info/freebox/ et je suis bloqué à l'étape 6 ("Lancement de l'application sur le Player") :
> Si l'application est bloquée sur « Chargement… », alors la désinstaller puis la résinstaller.

J'ai essayé de désinstaller/réinstaller l'application sans obtenir de résultat différent.

Dites-moi si vous êtes encore intéressé par ce problème et si vous avez besoin d'aide pour tester.

**Comment by Aymkdn** [comment]
Bonjour. Je vous confirme que ça fonctionne sur la Mini 4K. Passez me voir sur le tchat de https://assistant.kodono.info/freebox/ qu'on voit ça ensemble.

**Comment by woctezuma** [comment]
Bonjour,

Merci pour votre réponse. Finalement : 
- en réessayant environ une heure après votre message, l'application s'est lancée,
- ce matin, j'ai pu finir la configuration, et ça fonctionne !

Merci pour la skill, c'est super !
