### ISSUE TITLE
"Alexa, lance youtube sur freebox" ne fonctionne pas

### ISSUE THREAD

**Issue by DarkAdrick** [Aymkdn/assistant-freebox-cloud#127]
Alexa dis bien "voici l'application youtube sur freebox" mais rien ne bouge, que l'on soit sur le menu ou dans la TV freebox

**Comment by Aymkdn** [comment]
Viens me voir sur la tchat du site afin que je regarde ton profil. Ça sera plus simple. Je ferme cet issue du coup.

**Comment by DarkAdrick** [comment]
Ok thx mais là pas le temps, je reviendrai vers toi
Après c'est peut-être parceque je viens de créer toute la  procédure, ça marchera peut-être avec un reboot.

Mais en tout cas merci pour le tuto, et le projet !
