### ISSUE TITLE
wiki about newer version of android tv

### ISSUE THREAD

**Issue by theRemoter** [Aymkdn/assistant-freebox-cloud#128]
Hello,

I have read your great wiki about how to pair with older version of google android tv, which isn't working with 5+ newer versions.
do you plan on trying to reverse engineer the new versions as well?

thanks for your great work

**Comment by Aymkdn** [comment]
Yes and I actually started to write a draft: https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2)

It's a work in progress…

**Comment by theRemoter** [comment]
are u available on discord maybe to chat a bit about it?

**Comment by Aymkdn** [comment]
I didn't finish to understand all the protocol, and I'll update the documentation as I go along. I hope to get the whole picture by the end of the year.

This documentation is provided as it is. I don't expect to provide any support about it. I created it to share my findings and makes life easier for other developers, but it's not a project that I'll maintain for the community.

So, to your question, I'd say "No, I'm not available".

Wait for the documentation to be completed, and then try to figure out by yourself. I know it's not super easy, but it's the best way to learn. You could try to post your questions on Stackoverflow too. I can also try to answer your questions here, if I can.

**Comment by theRemoter** [comment]
no problem, thanks a lot for your contribution of course. I just wanted to try and continue from where you've stopped, but I guess I'll do it anyway.
by saying you "hope to get the whole picture by the end of the year." you mean by this year? 2021?

thanks a lot, appreciate your hard work

**Comment by Aymkdn** [comment]
Yes, I mean within the next 2-3 weeks.
