### ISSUE TITLE
"Malheureusement la chaîne la 3 n'est pas disponible" 

### ISSUE THREAD

**Issue by renaudcerrato** [Aymkdn/assistant-freebox-cloud#129]
Depuis quelques temps, il n'est plus possible de mettre une chaîne depuis son Google Assistant en l'appelant par son numéro... Il faut prononcer son nom (France 3)... Bien sûr, il ne comprend pas quand je dis TF1....

**Comment by Aymkdn** [comment]
Ouais, Google a foiré sa mise à jour de la grammaire et du coup le nom des chaines déconne.

Pour TF1, la phrase qui marche est : « OK Google, mets la chaine numéro 1 »

Je vous invite à faire comme moi et à signaler le problème à Google : 
  - ouvrir l'application "Home"
  - cliquer sur son profil en haut à droite
  - choisir "Envoyer des commentaires"
  - indiquer que la reconnaissance vocale des chaines ne fonctionne plus correctement

**Comment by Aymkdn** [comment]
Le problème étant lié à Google et non à mon service, je ferme cet issue.

Merci de contacter Google pour leur remonter le soucis. Plus on sera nombreux, plus il y a de chances qu'ils y fassent quelque chose !
