### ISSUE TITLE
Ajout de la chaine 61 - NatGeo Wild

### ISSUE THREAD

**Issue by AbouArez** [Aymkdn/assistant-freebox-cloud#13]
Bonjour,

J'utilise depuis aujourd'hui la version Assistant Cloud...

En suivant l'installation pas à pas, tout s'est tres bien passé !
Le guide explique tres bien, en pas a pas, les actions à faire... y compris la creation des appets ifttt, qui, finalement n'est pas du tout fastidieux.

Nous regardons la chaine NatGeo Wild (61), qui, apparemment n'est pas reconnue dans la base (ou alors, ce n'est pas le bon mot cle ?).

Voici ce que la partie Message d'Erreur retourne : 
  commande : zappe sur NatGeo wild 
  message d'erreur : La chaine natgeo wild est inconnue.

Merci pour tout, c'est presque magique !

**Comment by Aymkdn** [comment]
Je viens de l'ajouter. Réessaie !

**Comment by AbouArez** [comment]
Je fais le test en rentrant et te tiens au courant.
Merci.

**Comment by Aymkdn** [comment]
J'ai pu tester (la TV était occupée hier soir), et mon Google Home a bien reconnu la chaine :-) Je clos donc ici, mais n'hésite pas à reposter si ça ne fonctionne pas.

**Comment by AbouArez** [comment]
Bonsoir,

Je te confirme, ça fonctionne parfaitement pour nous aussi !

Merci.

Envoyé de mon iPhone

Le 19 mars 2019 à 09:25, Aymeric <notifications@github.com<mailto:notifications@github.com>> a écrit :


J'ai pu tester (la TV était occupée hier soir), et mon Google Home a bien reconnu la chaine :-) Je clos donc ici, mais n'hésite pas à reposter si ça ne fonctionne pas.
