### ISSUE TITLE
New changes in google update

### ISSUE THREAD

**Issue by ghost** [Aymkdn/assistant-freebox-cloud#130]
Hello
thanks for your work!
There is an update that google did and right when you open a connection you get a message that looks like this:
```
[85]
[10, 83, 8, -17, 4, 18, 78, 10, 3, 121, 101, 115, 18, 12, 83, 69, 73, 32, 82, 111, 98, 111, 116, 105, 99, 115, 24, 1, 34, 2, 49, 48, 42, 36, 99, 111, 109, 46, 103, 111, 111, 103, 108, 101, 46, 97, 110, 100, 114, 111, 105, 100, 46, 116, 118, 46, 114, 101, 109, 111, 116, 101, 46, 115, 101, 114, 118, 105, 99, 101, 50, 13, 53, 46, 49, 46, 52, 49, 53, 51, 50, 52, 55, 50, 56]
```

not sure what it means, but the current instructions in the protocol doesn't work for me (the pairing works fine, but cannot start the configuration protocol and send commands).

I think that maybe something changed in the first configuration message, becase after I'm trying to send it, I get an exception in my socket and I try to get the response after the first configuration message.

**Comment by Aymkdn** [comment]
Sorry, but I have no idea... It's already been painful to get there 😅

You may want to try https://github.com/louis49/androidtv-remote to see how it goes. You can add some debug lines to see what is sent / received. 

If you find new information, feel free to share.

**Comment by Aymkdn** [comment]
Did you make any progress regarding this issue? A couple of people told me there is a new version of the Remote service zand it seems the way the commands are sent.
I'm on vacation in another country so I cannot test myself right now. I'll be able to investigate more in two weeks. So if you found the issue, it might help 😊 Thanks

**Comment by ghost** [comment]
actually I also haven't tried to use it since then, but I think I had an issue in the way I tried to parse the bytes, and I think it does working

**Comment by techie-gabbar** [comment]
@Ganime422 

Can u please help in below issue.  Android CertPathValidatorException when sending TLS True

```
 var options = {
              port: 6467,
              host: host,
              tls: true,
              tlsCheckValidity: false,
              tlsCert: require('./public-cert.pem')
         }

            const client = TcpSocket.createConnection(options, () => {
              console.log("Connccted");
            });
```
When sending above thing in Android. Than Below Error is coming. Can u please help. The public-cert.pem is in my root react native project.

ERROR:
"**java.security.cert.CertPathValidatorException**: Trust anchor for certification path not found."
