### ISSUE TITLE
Android TV Remote problem

### ISSUE THREAD

**Issue by XITRIX** [Aymkdn/assistant-freebox-cloud#131]
Hi, thanks for your great work with [ATV Remote v2](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2)).

Could I ask you a question about it? 

I'm trying to implement it using OpenSSL + (C++\Swift) but I've met some problems.

I've programmatically generated pem cert and private key using mbedtls, and added them into SSL context, successfully opened socket and send a pairing payload from your example, but after that I receive strange response

Here are three example payloads from your doc:
![image](https://user-images.githubusercontent.com/9553519/151453906-d25ef8ac-8c33-452d-a1fb-26c57568982b.png)

As I can see there are lots of extra zeros, which breaks the response into pieces, like first response contains [8, 2], second length is [16], and the respond is [200, 1, 90, 0] and all together exactly what I should get 

I'm noob in TLS stuff so I have no idea where I could messed up, so if you've met such behavior, how did you solved it, if you need some code samples, I'll send them with no doubt.

**Comment by XITRIX** [comment]
Oh, ok, I've found the problem, I've tried to get all the length of bytes using SSL_read(&buf, length), but instead I should use for loop ( 0 ... length ) with SSL_read(&buf, 1), reading bytes one by one. It seems strange for me, but now I've finally got pairing screen on my TV! :)

**Comment by SodaSurfer** [comment]
@XITRIX I'm also trying to implement this using SWIFT but I had troubles opening an SSL socket with the tv.
do you mind to share your repo or maybe we can talk about it on discord or email?

**Comment by XITRIX** [comment]
@SodaSurfer, if you'd like to do it for iOS, you should not use internal TLS framework, cause it have lots of restrictions about server certificates, so it just refuse to work with Android TV's one. Better use something open source like OpenSSL via native Darwin sockets.
P.S. if you tried to use TLS libs for swift - it's useless, cause all of them uses the same Apple's TLS backend with restrictions.

**Comment by SodaSurfer** [comment]
@XITRIX good to know! what can u expect from apple... I'll try to use the OpenSSL and native Darwin sockets that you suggested though I'm not familiar with that. if you can give me some hints on this I'll appreciate it. Hope I'll manage to at least get the socket open. thanks!

**Comment by XITRIX** [comment]
I've started to learn that TLS stuff about 1 week ago, so I know almost nothing :)
Try to find some C examples, it's not so hard to rewrite C code to swift as it seems, cause swift has backward compatibility with C

**Comment by SodaSurfer** [comment]
@XITRIX Hi
So I tried the whole week to open a connection with my tv using iOS but I'm still struggling it.
can u give a hint or maybe an article u used to start the tls connection?
have u used objective-c for that or only old school C?
did u needed to edit ur info.plist file and add some sort of an app transport security setting?
did u used TrustKey lib for iOS?
any help is very appreciated

**Comment by XITRIX** [comment]
Hi, the problem is that Apple's security transport lib don't like Android TV's certificate and refuses to work with it, the only solution is to abandon it and use any other alternative, like OpenSSL. Nothing else is needed. For key generation I've used MbedTLS lib, but I'm pretty sure that OpenSSL can do the same, I've used it cause I already had a piece of code doing what I need from my another app. Talking about C, I've not used any line of code on it, Swift only with OpenSSL Swift bindings

**Comment by SodaSurfer** [comment]
I understand. so u haven't touched info.plist file as well to add some kind of transport security settings?
and thank u. I'll try to look for libraries that do OpenSSL swift bindings and dig into it.

**Comment by SodaSurfer** [comment]
@XITRIX can you shed the light on the way you created the secret message?
I think I am getting the modulus from the peer & client certificate in a wrong way.
I am doing something like that:
getting the certificate:
`var peer_cert = SSL_get_certificate(ssl)
`
getting the RSA key:
```
var pubkey = X509_get_pubkey(peer_cert)
var rsakey = EVP_PKEY_get1_RSA(pubkey)
```

getting the modulus and exponent:
```
var n = UnsafeMutablePointer<OpaquePointer>.allocate(capacity: 1)
var objOpaquePtr_n : OpaquePointer! = OpaquePointer(n)
var e = UnsafeMutablePointer<OpaquePointer>.allocate(capacity: 1)
var objOpaquePtr_e : OpaquePointer! = OpaquePointer(e)
RSA_get0_key(rsakey, &objOpaquePtr_n, &objOpaquePtr_e, nil)
```

now get the byte data of the modulus and exponent:
```
let modulus = BN_num_bits(objOpaquePtr_n)
let public_exponent = BN_get_word(objOpaquePtr_e)

let n_data = Data(bytes: UnsafePointer<UInt8>(objOpaquePtr_n), count: Int(modulus)).bytes
let e_data = Data(bytes: UnsafePointer<UInt8>(objOpaquePtr_e), count: Int(public_exponent)).bytes
```

and I used this lib to create a digest message:
https://github.com/krzyzanowskim/CryptoSwift

but I think I am not doing it correct since I don't get a correct response. can you please share some hints on how you generated the secret message?

**Comment by XITRIX** [comment]
CryptoSwift - good,
Getting the certificate - good
Getting the RSA key - good
Getting the modulus and exponent - nope, something strange

There are 2 methods for it `RSA_get0_n(rsa)` for modules and `RSA_get0_e(rsa)` for exponent
Then you could convert them into String using `String(cString: BN_bn2hex(<modules or exponent>))` (I'm storing them as strings)

**Comment by SodaSurfer** [comment]
@XITRIX thanks for the tip but I still can't get it right, and have now I'm not sure where my problem is.
I know the modulus I get now is correct thanks to you.

after you get the modulus and exponent as strings, you update the digest message just by changing it to bytes? I mean:
```
var hash =  SHA3(variant: SHA3.Variant.sha256)
let partial1 = try hash.update(withBytes: n_string.bytes)
let partial2 = try hash.update(withBytes: e_string.bytes)
let partial3 = try hash.update(withBytes: peer_n_string.bytes)
let partial4 = try hash.update(withBytes: peer_e_string.bytes)
let partial5 = try hash.update(withBytes: sub_code.bytes)
let result = try hash.finish()
```

and then I just append the result to the initial message:
```
var byte_array : [UInt8] = [ 8, 2, 16, 200, 1, 194, 2, 34, 10, 32 ]
byte_array.append(contentsOf: result)
```

but I keep getting the wrong response. I assume that I don't convert the strings to bytes in the correct way which is unclear.
can you direct me where the issue is?

**Comment by XITRIX** [comment]
1 Why SHA3? You need SHA2
2 You should convert strings not to bytes, but into hexBytes
3 Try to copy paste your cert and private key into js lib, and compare where your calculations go wrong

**Comment by XITRIX** [comment]
1 Why SHA3? You need SHA2
2 You should convert strings not to bytes, but into hexBytes

**Comment by sz-ashik440** [comment]
@sodasurfer


> @XITRIX can you shed the light on the way you created the secret message? I think I am getting the modulus from the peer & client certificate in a wrong way. I am doing something like that: 
> getting the certificate: 
> `var peer_cert = SSL_get_certificate(ssl)`
> getting the RSA key:
> 
> ```
> var pubkey = X509_get_pubkey(peer_cert)
> var rsakey = EVP_PKEY_get1_RSA(pubkey)
> ```

How did you get `ssl` for `var peer_cert = SSL_get_certificate(ssl) `? I assume you have used [krzyzanowskim/OpenSSL](https://github.dev/krzyzanowskim/OpenSSL) library, but how did you generate `ssl` object?

**Comment by sz-ashik440** [comment]
> I've started to learn that TLS stuff about 1 week ago, so I know almost nothing :) Try to find some C examples, it's not so hard to rewrite C code to swift as it seems, cause swift has backward compatibility with C

@XITRIX @SodaSurfer 
I used openSSL and created key and certificate files. But struggling to make a connection with those certificates using openSSL. Any direction will be helpful(even any C/C++ implementation).
Every time I try to read data with `SSL_read`, it fails with `SSL_ERROR_WANT_READ` 
Thanks

**Comment by sz-ashik440** [comment]
> 2 You should convert strings not to bytes, but into hexBytes

This does the tricks.
