### ISSUE TITLE
Android CertPathValidatorException when sending TLS True

### ISSUE THREAD

**Issue by techie-gabbar** [Aymkdn/assistant-freebox-cloud#132]
```
 var options = {
              port: 6467,
              host: host,
              tls: true,
              tlsCheckValidity: false,
              tlsCert: require('./public-cert.pem')
         }

            const client = TcpSocket.createConnection(options, () => {
              console.log("Connccted");
            });
```
When sending above thing in Android. Than Below Error is coming. Can u please help. The public-cert.pem is in my root react native project.

ERROR:
"**java.security.cert.CertPathValidatorException**: Trust anchor for certification path not found."

@Aymkdn Please Help

**Comment by Aymkdn** [comment]
Unfortunately it's barely impossible for me to help with this kind of error, and again this repo is not for this kind of support. Please, use StackOverflow to ask your questions.
