### ISSUE TITLE
Android app SSL decription

### ISSUE THREAD

**Issue by XITRIX** [Aymkdn/assistant-freebox-cloud#133]
Hi, thanks for your great work on [ATVR2 protocol](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2))!

I'm trying to create remote controller for iOS and I want to dump and decrypt Google Home\TV app's praffic to understand what packets needs to be sent to use Ime service (keyboard input). And I'm stuck on decrypting part. I have rooted Android tablet and TV, and I tried lots of things to make it work (Frida, apk-mitm, PCAPdroid, mitmproxy, installing root CA into system, tcpdump, ssl unpining), and I always finish with unworking connection between App and TV, or just unable to decrypt the traffic I got. I have also tried to decompile app to find some stuff there, but it's completely obfuscated and I cannot understang nothing.

Could you please help me to find the correct way of how to decryps app's traffic?

**Comment by Aymkdn** [comment]
Sorry, but all my tries to decrypt app traffic failed too.

I've been able to find the bits using some debug `console.log` from https://github.com/louis49/androidtv-remote and [by debugging](https://blog.kodono.info/wordpress/2021/11/29/debug-a-third-party-android-apk/) a remote app for Android.

I cannot help you more than that…

Good luck.

**Comment by piyush2greedy** [comment]
@Aymkdn @XITRIX 
I have been able to do a successful SSL Handshake from Android to Android TV. Next thing is that I need to send message via SSL Socket. Can anyone help me in that. In NodeJS Version it is done through proto. How to do it in Android.

**Comment by ghost** [comment]
@XITRIX did you have any progress? I am also unable to decrypt the traffic.

**Comment by XITRIX** [comment]
I've been able to decrypt some traffic with Frida, but it was limited and hard to read, also I've had to find proper methods to override searching for them using decompilers

**Comment by cd-dan** [comment]
Did you find out how to send text?
