### ISSUE TITLE
Google TV (aka Android TV) Remote Control (v2)

### ISSUE THREAD

**Issue by nickmalevich** [Aymkdn/assistant-freebox-cloud#137]
Hi
I am developing a remote control for Android TV on iOS. I used your explanation of the communication protocol with Android TV. It works great, thank you for that. I already have pairing with the TV and sending keyCodes to the TV. Now I want to implement input in the search fields on the TV using the keyboard on the phone. Just sending letter keyCodes doesn't work. So I am writing to you for help, maybe you have implemented this feature or know where you can look to implement
Thank you in advance

**Comment by Aymkdn** [comment]
I'm sorry, but I never tried that, and I have no idea how to do it....

**Comment by ghost** [comment]
@nickmalevich Did you solve? If yes can you please share the solution.
