### ISSUE TITLE
Can you write method or payload form to send voice and text from keyboard

### ISSUE THREAD

**Issue by nandishyb** [Aymkdn/assistant-freebox-cloud#139]
Can you write method or payload form to send voice and text from keyboard?

**Comment by Aymkdn** [comment]
Honestly I don't know, but I'd think this is not possible.

**Comment by nandishyb** [comment]
It is possible as Google Home app is doing it , Only thing it needs to be decompiled. If you have easy way to check it , that would be good to get the payload details to send the Keyboard text to TV 
Thanks.

**Comment by Aymkdn** [comment]
I don't have any easy to check/do it.

**Comment by nandishyb** [comment]
How did you do the reverse engineering for pairing and other sending commands ? It is so helpful and accurate. Similarly , can you do it for send keyboard text.

**Comment by Aymkdn** [comment]
> How did you do the reverse engineering for pairing and other sending commands ? It is so helpful and accurate.

@hubertlejaune did most of the work, and for what I didn't get from him while working together to figure out how it worked, then I used https://github.com/louis49/androidtv-remote that resolves most of it too.

**Comment by nandishyb** [comment]
Can @hubertlejaune be contacted and checked to figure out how it worked?

**Comment by Aymkdn** [comment]
I have no way to contact him anymore, and I don't think he would help anyway :-)

Your best chance is too use https://github.com/louis49/androidtv-remote and see if this project can help.

**Comment by nandishyb** [comment]
I have referred the above mentioned github and it is really good one. I have also registered an issue in this github and waiting for louis49 to respond. Lets see. Thank you for your time.

**Comment by hubertlejaune** [comment]
Hello,
For the paring protocole I have use multiple source and combine them all.
- App using old protocole
- Working app with debug log that wasn't removed
- Logics

I remember there was a message type for sending voice message but didn't try making it working. There are too many unknow :
- audio format
- audio code
- max lenght
- max duration

And for the initial use we didn't need it. So yes it should be possible but I dont know how.

**Comment by nandishyb** [comment]
@hubertlejaune Its nice to see your response . How about sending the keyboard text to TV.  Do you have any idea ?

**Comment by hubertlejaune** [comment]
If it isn't documented [Here](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Google-TV-(aka-Android-TV)-Remote-Control-(v2)) , either we didn't try nor we didn't succeed in making it working. 
I may have somewhere some supposed "message tag" for voice and text but nothing more than that.

**Comment by nandishyb** [comment]
@hubertlejaune Can you give some payload information to send text with "message tag" details that you might have? It will be helpful. Maybe can update also the document.

**Comment by MatanYamin** [comment]
@nandishyb  Did you manage to figure it out and send text to TV?

**Comment by nandishyb** [comment]
@MatanYamin No not yet, I shifted my focus on other project and haven't got time to look further into it.

**Comment by MatanYamin** [comment]
OK, thanks.

**Comment by MuhammadAsad786** [comment]
@nandishyb did you solve the voice assistance working issue in AndroidTv Remote?.
if yes, so can you share me some piece of code that working , I transport the voice begin command but android tv does not listerner

**Comment by ghost** [comment]
@MatanYamin 
Did you solve it ? if yes can you please share it the protocols

**Comment by ghost** [comment]
@MuhammadAsad786 did you implemented text input or voice begin or voice payload?

**Comment by MuhammadAsad786** [comment]
At this time text input working done and looking for Voice working

**Comment by MuhammadAsad786** [comment]
> @MuhammadAsad786 did you implemented text input or voice begin or voice payload?
> 

At this time the keyboard working complete. Now, looking for Voice integration

**Comment by ghost** [comment]
@MuhammadAsad786 can you please share the keyboard integration protocols for sending letters??

**Comment by MuhammadAsad786** [comment]
> @MuhammadAsad786 can you please share the keyboard integration protocols for sending letters??


Tomorrow i will send you
If you have any query then contact me on mail muhammadasad5683@gmail.com

**Comment by ghost** [comment]
> > [@MuhammadAsad786](https://github.com/MuhammadAsad786) can you please share the keyboard integration protocols for sending letters??
> 
> Tomorrow i will send you If you have any query then contact me on mail [muhammadasad5683@gmail.com](mailto:muhammadasad5683@gmail.com)

Thank You So Much

**Comment by MatanYamin** [comment]
> > [@MuhammadAsad786](https://github.com/MuhammadAsad786) can you please share the keyboard integration protocols for sending letters??
> 
> Tomorrow i will send you If you have any query then contact me on mail [muhammadasad5683@gmail.com](mailto:muhammadasad5683@gmail.com)

Hi, I would be happy to understand the keyboard integration as well, sir.

**Comment by Aymkdn** [comment]
Could you please share it here? It's a recurrent question that I receive and it would be beneficial to everyone if I could add the explanation on the existing documentation. Thanks.

**Comment by astrokin** [comment]
feel free to find text input implementation without ADB for Android TV in [python](https://github.com/tronikos/androidtvremote2/pull/25) and [js](https://github.com/louis49/androidtv-remote/pull/46)

**Comment by NaikUrRehman** [comment]
> > [@MuhammadAsad786](https://github.com/MuhammadAsad786) can you please share the keyboard integration protocols for sending letters??
> 
> Tomorrow i will send you If you have any query then contact me on mail [muhammadasad5683@gmail.com](mailto:muhammadasad5683@gmail.com)

Hey how did you do it for YouTube. My implementation works fine for the search bar having focus state. But it is not working for YouTube.
