### ISSUE TITLE
Problème lors de l'authentification 

### ISSUE THREAD

**Issue by Poldou** [Aymkdn/assistant-freebox-cloud#14]
Bonjour !
Votre application pour contrôler la freebox avec l'assistant Google m'a vraiment beaucoup intéressé. 
Donc j'ai voulu tester mais il y'a eu un problème lors de la recherche du freebox player sur l'application assistant freebox directement sur la freebox. J'ai indiqué le code demandé sur internet mais la freebox est restée bloquée sur la recherche du freebox player... 
Merci d'avance pour votre aide 
Cordialement

**Comment by Aymkdn** [comment]
Quel message *exactement* apparaît sur l'application ?

As-tu essayé de relancer l'application pour voir si ça changeait quelque chose ? 

Peux-tu me donner un bout de ton e-mail afin que je puisse te retrouver dans la base de données ?

**Comment by Poldou** [comment]
Alors le message sur l'application est : nombre de freebox player détecté = 0
Oui j'ai réessayé de relancer l'application mais ça ne change rien ça reste sur le message. 
Et sur le site assistant cloud il reste sur l'étape 2 avec : en attente de la configuration de la freebox.
Mon adresse email est : leopold...... @yahoo.fr
Merci

**Comment by Aymkdn** [comment]
Mmhhhh... étrange.

Peux-tu suivre ces étapes qui m'aideront à comprendre pourquoi : 

1. Va sur http://mafreebox.freebox.fr/ (depuis chez toi puisque ça te donne accès à l'interface de ta Freebox)
2. Ensuite va dans **Périphérique Réseau**
3. Clique sur "Freebox Player"
![Capture](https://user-images.githubusercontent.com/946315/54588196-8f98a580-4a22-11e9-98ca-0a88ac8da59a.PNG)
4. Dans **Type de Périphérique** tu as bien **Freebox Player** ?
![Capture](https://user-images.githubusercontent.com/946315/54588239-afc86480-4a22-11e9-9215-82d3199a06f4.PNG)
5. Dans l'onglet "Connectivité" tu as bien au moins une ligne avec **Joignable** et **Actif** ? Avec en face de cette ligne une adresse IPv4 (par exemple 192.168.0.33) ?
![Capture](https://user-images.githubusercontent.com/946315/54588317-ec945b80-4a22-11e9-8654-b55622f05059.PNG)

**Comment by Poldou** [comment]
Alors je suis allé dans périphérique réseau et sur le freebox player. Il y a ici indiqué freebox HD.
Et dans l'onglet connectivité, il y a une ligne active et une ligne injoignable...

**Comment by Aymkdn** [comment]
Tu as bien une Freebox Révolution ?

**Comment by Poldou** [comment]
Oui une freebox révolution

**Comment by Poldou** [comment]
Mais dans les réglages je peux changer freebox HD en freebox player

**Comment by Aymkdn** [comment]
Laisse Freebox HD. Je t'envoie un email maintenant pour tester un truc.

**Comment by Aymkdn** [comment]
Je t'ai envoyé un email. J'ai mis en ligne un version bêta de l'application que tu testeras si tu veux bien :)

**Comment by Aymkdn** [comment]
L'utilisateur m'a confirmé que la nouvelle version de l'application a résolu le problème !
