### ISSUE TITLE
Having problem to connect with port 6466. Port 6467 connects great.

### ISSUE THREAD

**Issue by MatanYamin** [Aymkdn/assistant-freebox-cloud#141]
I'm opening 2 ssl connection with the same client certificate, but for some reason, I can only connect to port 6467.

When trying connect to port 6466 I'm getting authentication error.

Do you know why?

**Comment by Aymkdn** [comment]
If the pairing failed on port 6467, then the client certificate won't be accepted on port 6466. So, you probably have an issue during the pairing process.

You can also try to restart your Android TV, or to use a new client certificate (after too many tests it can corrupt things).

**Comment by MatanYamin** [comment]
I was able to successfully pair with port 6467 to the Android device, indicated by the TV.
But, now I want to send the commands using port 6466, and that is where I can't authenticate for sending the commands.
Didn't have issues with port 6467 so the pairing was successful.

**Comment by Aymkdn** [comment]
Then, sorry, I don't know.
