### ISSUE TITLE
How can I know which button needs one message or press + release messages?

### ISSUE THREAD

**Issue by MatanYamin** [Aymkdn/assistant-freebox-cloud#143]
How can I know which button needs one message or press + release messages?

**Comment by Aymkdn** [comment]
Sorry, but I have no idea. Try asking to ChatGPT, [Perplexity](https://www.perplexity.ai), [Claude](https://claude.ai), or [Google](https://www.google.com/) :-)

**Comment by yuqingyuan** [comment]
@MatanYamin @Aymkdn  you can try this in v1 protocol (I write in swift), it combines press+release in one message
`[1, 2, 0, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {value},
   1, 2, 0, 16, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, {value}]`

**Comment by ghost** [comment]
@MatanYamin You can place one click for normal buttons but some time we need press + release (on long press) for volums , forward and rewinds videos etc
