### ISSUE TITLE
Unable to Send Text Input to AndroidTV v2 Device

### ISSUE THREAD

**Issue by MatanYamin** [Aymkdn/assistant-freebox-cloud#144]
First of all, thank you for this great project.

Problem:
I’m unable to send text input (letters) to the device (KEYCODE_A = 29, KEYCODE_B = 30 etc..). 
Other commands are working fine, but when I try to send text characters (for example, for entering text in a YouTube search field), nothing happens on the device.

Is there an alternative way of doing this?

**Comment by Aymkdn** [comment]
Sorry, I don't use this function and I don't know how to make it work. Several people asked me this question... I suppose someone figured it out by now but they never came back to me to tell how to proceed.

**Comment by umrmbasw2332** [comment]
@MatanYamin  have you found solution for text and voice input ? Please let me know..

**Comment by astrokin** [comment]
feel free to find text input implementation without ADB for Android TV in [python](https://github.com/tronikos/androidtvremote2/pull/25) and [js](https://github.com/louis49/androidtv-remote/pull/46)
