### ISSUE TITLE
Freebox Delta

### ISSUE THREAD

**Issue by francklek** [Aymkdn/assistant-freebox-cloud#15]
Hello, utilisateur du plugin de la première heure, j'ai entre temps opté pour la freebox delta, et son assistant qui est un peu sourd ! 
Comme les commandes http semblent presque toutes identiques, on pourrait passer la delta sous google home. Malheureusement l'application n'est pas dispo dans le store de la delta et je ne peux donc pas aller plus loin.
Est-ce qu'il te semble réalisable de diffuser le soft de config dans le store de la delta ? Pour pouvoir la piloter comme une révolution...
Merci à toi pour le job !

**Comment by Aymkdn** [comment]
Y-a-t'il un code télécommande sur la Delta ? Si oui peux-tu me décrire comment le trouver ?

Une fois que tu as le code télécommande, est-ce que les commandes HTTP fonctionnent de la même façon avec la Delta ?

**Comment by francklek** [comment]
oui il y a un code télectommande sur la delta exactement comme sur la révolution. Il est accessible dans paramètres/reseau puis sur l'onglet "player"
les commandes http fonctionnent aussi, je m'en sert avec domoticz pour allumer le player.

**Comment by Aymkdn** [comment]
Ah OK cool, je ne savais pas ! Et du coup tu as accès à l'interface de la Freebox si tu vas sur http://mafreebox.freebox.fr/ et c'est la même que pour la Révolution ?

Par contre, je ne sais pas comment je peux publier sur le FreeStore Delta... Je vais me renseigner.

Tu t'es inscrit déjà sur le site mais t'es bloqué à l'étape 2 ? Si c'est le cas, donne moi un bout de ton email que je puisse te retrouver dans la base de données, et je te contacterai en privé.

**Comment by francklek** [comment]
oui l'interface "OS" de la delta est la même que celle de la révolution. La version actuelle est 4.0
Je me suis déjà inscrit et mon email : francklek

**Comment by Aymkdn** [comment]
L'application est maintenant disponible sur le Freestore de la Delta, et d'après les premiers retours, cela fonctionne. Je ferme donc cet issue.
