### ISSUE TITLE
Ne fonctionne pas

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#16]
Bonjour, et bien après avoir suivi scupuleusement le tuto... ma freebox ne s'allume pas, ne séteins pas. une incompatibilité avec google home mini ?

_Originally posted by @elyo33 in https://github.com/Aymkdn/assistant-freebox-cloud/issues/7#issuecomment-474354393_

**Comment by Aymkdn** [comment]
Salut @elyo33 ... J'ai déplacé ta question dans son propre thread.

Quand tu demandes à Google `Allume la Freebox`, il te répond `J'allume la Freebox` ou il te répond `Je n'ai pas compris` ?

Donne moi un bout de ton email afin que je te retrouve dans la base de données.

**Comment by elyo33** [comment]
merci pour le déplacement ;)
quand je lui demande Allume la Freebox, il me répond J'allume la Freebox.
mais rien ne se passe. 

quand je lui demande eteins la Freebox, il me répond qu'il n'a pas compris. 
lionel********@gmail

**Comment by Aymkdn** [comment]
Alors je vois que tu as en effet demandé du "allume la Freebox" plusieurs fois. De mon côté tout a l'air bon pourtant.

Une fois que tu as terminé le guide, tu arrives sur ton profil. De là tu as une section **Créer mes propres actions**.
Dans la liste déroulante, sélectionne `touche "power" de la télécommande`, puis clique sur `Ajouter` et ensuite sur le bouton `Tester`.
Toujours rien ne se passe ?

**Comment by elyo33** [comment]
toujours rien

**Comment by Aymkdn** [comment]
Je t'envoie un email pour que tu essaies autre chose.

**Comment by Aymkdn** [comment]
Après discussion : 

- le code télécommande était incorrect
- la commande `power` ne fonctionnait pas pour l'allumage de la Freebox, et pour résoudre ce problème : Aller dans **Réglages** > **Système** > **Gestion de l'énergie** > **Action par défaut de la touche d'extinction** doit être sur **Mettre en veille**
