### ISSUE TITLE
Super programme !!!

### ISSUE THREAD

**Issue by pinkheritage** [Aymkdn/assistant-freebox-cloud#17]
Bonjour,
Grace à cet assistant, google home devient interressant.
Bravo pour la conception, mais aussi et surtout pour le tutoriel. Chapeau !
Une petite question, comment programmer la consultation des messages le matin en allumant le player ? ce serait sympa....
Merci encore.

**Comment by pinkheritage** [comment]
Consulter mes messages vocaux dans applications

**Comment by Aymkdn** [comment]
Ah OK.

Alors, sur le site https://assistant.kodono.info/freebox/ va dans la section **"Créer mes propres actions"** puis sélectionne : 

- `touche « power » de la télécommande`, puis clique sur **Ajouter**
- `séquence de commande permettant d'aller au  « home »`, et clique sur **Ajouter**
- `enclencher une attente de X secondes`, en mettant **2** pour le délai, puis clique sur **Ajouter**
- `touche « flèche gauche » de la télécommande`, puis clique sur **Ajouter**
- `touche « flèche gauche » de la télécommande`, puis clique sur **Ajouter**
- `touche « flèche haut » de la télécommande`, puis clique sur **Ajouter**
- `touche « OK » de la télécommande`, puis clique sur **Ajouter**
- `touche « OK » de la télécommande`, puis clique sur **Ajouter**

Comme tu l'auras peut-être compris, cela simule toutes les actions de la télécommande. Donc là on allume, on se place sur "home", puis on se déplace jusqu'à **Messagerie Vocale**, on rentre dedans, puis on clique **OK** pour lire le premier message.

Il te reste à créer une applet IFTTT comme tu l'as fait pour les autres commandes, en mettant la phrase que tu souhaites, et en copiant le lien fourni.

Visuellement ça donne ça : 
![Capture](https://user-images.githubusercontent.com/946315/54622800-87645880-4a6a-11e9-8636-2fc7f7023347.PNG)

**Comment by pinkheritage** [comment]
Impec, j'avais commencé, mais cela ne fonctionnait pas car délai d'attente trop court. j'ai appliqué 4 s et cela fonctionne parfaitement. Merci encore, je vais faire un petit don, rien que pour le travail fourni et l'implication.

**Comment by Aymkdn** [comment]
Cool :-)

**Comment by pinkheritage** [comment]
https://assistant-api.kodono.info/fbx/NjYwOyM1YzkwZGU5NWNkMDI4/?c=on,wait4000,left,left,down,down,down,down,down,OK
