### ISSUE TITLE
Reboot

### ISSUE THREAD

**Issue by jlfm1** [Aymkdn/assistant-freebox-cloud#18]
Tout d'abord, BRAVO pour cette version !
J'essaye de créer une fonction reboot de la freebox, mais je suis bloqué :-(
J'arrive à accéder aux 'informations Freebox', mais pas à l'onglet Server. La dernière commande 'right" n'est pas prise en compte.
Je passe les paramètres suivants (la fin sera ,ok,right,ok pour confirmer)
c=home,wait2000,red,left,left,left,left,up,up,ok,wait2000,down,down,down,ok, wait3000,right

**Comment by Aymkdn** [comment]
Ce genre de longue commande n'est pas facile à traiter pour le serveur, car cela fait plein de requêtes à envoyer, et certaines peuvent mal passer.

Essaie cette commande : `home,wait2000,left*4,up*2,ok,wait2000,down*3,ok,wait2000,right,wait2000,ok,wait2000,right,ok`

(je n'ai pas testé le dernier appui sur OK car je ne veux pas redémarrer :p)

**Comment by jlfm1** [comment]
GENIAL !

Ca fonctionne impec... et je note le *n après une commande

Merci
