### ISSUE TITLE
Dysfonctionnement des actions vocales

### ISSUE THREAD

**Issue by BenCath** [Aymkdn/assistant-freebox-cloud#19]
Bonjour et merci pour le boulot effectué.
Je ne comprends car j'ai bien tout paramétré comme indiqué (a priori) mais rien ne se passe sur la Freebox pour aucune des commandes.
Mon Google Home me confirme bien la commande avec la phrase choisie mais aucune action n'est effectivement réalisée. J'ai pourtant installé l'app via le Freestore et fait la procédure d’association avec le code à saisir... J en vois pas où le problème se pose.
Mon compte Google est bien le même utilisé pour mon inscription et pour mon Google Home.

**Comment by Aymkdn** [comment]
Peux tu me donner un bout de ton e-mail afin que je puisse te retrouver dans la base de données ?

**Comment by Aymkdn** [comment]
Et vérifie également que tu as bien entré le bon code télécommande

**Comment by BenCath** [comment]
mon mail : benoitc....@gmail.com
et le code semble le bon.

**Comment by Aymkdn** [comment]
Ton code télécommande est visiblement incorrect car il ne fait que 4 chiffres, alors qu'il doit faire entre 7 et 8 chiffres...

**Comment by BenCath** [comment]
OK je suis un idiot ! :))
J'ai confondu avec le code secret de la Freebox.
C'est bon tout fonctionne bien maintenant !
Merci encore pour le boulot et tes réponses.

C'est génial !

**Comment by Aymkdn** [comment]
Cool 😊
