### ISSUE TITLE
pas d application assistant freebox

### ISSUE THREAD

**Issue by seb60500** [Aymkdn/assistant-freebox-cloud#2]
bonsoir je ne trouve pas l'application dans le freestore .
a t'elle été retirer??

**Comment by Aymkdn** [comment]
Je n'ai pas encore officiellement lancé la chose. L'application n'a donc pas été publiée sur le freestore encore.

Je t'invite à lire les messages là  : 
https://github.com/Aymkdn/assistant-freebox-cloud/issues/1
