### ISSUE TITLE
firewall vs Assistant-Freebox-Cloud

### ISSUE THREAD

**Issue by gb31** [Aymkdn/assistant-freebox-cloud#20]
Bonjour Aymeric,
Excellente Application Merci

Afin de configurer mon firewall, Je voudrais connaitre les flux réseau et les ports TCP ou UDP utiliser par l'appli.
Chez le Player est derrière le firewall, du coup la détection de celui-ci ne passe pas.
pourriez-vous m'aider sur ce point.

en vous remerciant 
Cordialement
GB

**Comment by Aymkdn** [comment]
Je viens d'ajouter une section dans la FAQ où j'explique cela : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox-

Dis moi si tu as d'autres questions !
