### ISSUE TITLE
Impossible d'ouvrir l'application depuis ma freebox

### ISSUE THREAD

**Issue by VegasLord** [Aymkdn/assistant-freebox-cloud#21]
Bonjour je n'arrive pas a ouvrir l'application depuis ma freebox  avez vous une solution ?

Merci

**Comment by Aymkdn** [comment]
Tu utilises une Freebox Révolution ?

Tu entends quoi exactement par "je n'arrive pas à ouvrir l'application"?

**Comment by VegasLord** [comment]
Oui une Freebox révolution 

Alors j'ai télécharger l'application sur ma freebox, 
puis quand j'essaye de lancé l'application elle ne s'ouvre pas ... :(

**Comment by Aymkdn** [comment]
Elle ne s'ouvre pas ? Elle est dans "Mes Applications" et tu cliques dessus, et rien ne se passe ? Bizarre...

As-tu récemment redémarré ta Freebox Serveur et Player pour être sûr qu'elles sont à jour ?

Sinon tu as la possibilité de configurer manuellement ta Freebox : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox-

**Comment by VegasLord** [comment]
salut c'est bon pour moi tout est configuré je t'ai envoyé un mail ;)

merci

**Comment by Aymkdn** [comment]
Réponse par email !
