### ISSUE TITLE
Liste des chaines canal

### ISSUE THREAD

**Issue by CCoupel** [Aymkdn/assistant-freebox-cloud#22]
En selectionnant les chaines canal dans mes options, le changement de chaines se fait correctement via un appui long, cependant , quand je demande a zapper sur un nom de chaine, par exemple RMC decouverte, le system zape sur la 24 au lieu de 98. Il semble qu'il reste sur le nommage Freebox et non Canalsat.

**Comment by Aymkdn** [comment]
Ouais il est possible que certaines chaines ne soient pas bien mappés. Je viens de modifier pour RMC. N'hésite pas à m'indiquer les autres chaines qui auraient le même problème pour que je les modifie !

**Comment by Aymkdn** [comment]
Je ferme ce ticket, mais n'hésite pas à reposter ici pour d'autres chaines mal numérotées (ou à ouvrir une nouvelle issue).

**Comment by CCoupel** [comment]
Superbe reactivé.
Plus globalement, la liste des chaines quand on selectionne l'option canal renvoie le chiffrage des chaines freebox, il faudrait revoir entirement la mapping:

Science & vie TV n'est pas reconnue non plus (91)
manga n'est pas bonne (

Chaines non reconues:
les canal+ (10 - 14)
les cine+ (20 - 25)
les OCS 26 - 29)

Disney Channel (48 au lieu de 30)

**Comment by Aymkdn** [comment]
Si tu me trouves une liste fiable des chaines Canal, je reprendrai tout !

**Comment by Aymkdn** [comment]
Pour info, je viens de récupérer cette liste : https://alloforfait.fr/tv/canal .... et je suis en train de mettre à jour les numéros de chaine

**Comment by Aymkdn** [comment]
Enfin... Avant de tout mettre à jour, peux-tu me confirmer que cette liste représente bien les chaines CANAL de Free ? Question que je ne fasse pas tout ça pour rien !

**Comment by CCoupel** [comment]
Oui, je retrouve bien le Numero de chaines quand je suis dans l'univers Canal de free. Désolé de ne pas avoir pu te repondre plus tot.

**Comment by Aymkdn** [comment]
OK, parfait. Je continue à mettre à jour demain !

**Comment by Aymkdn** [comment]
Voilà j'ai mis à jour les 151 chaines que j'ai dans la base de données actuellement !

**Comment by CCoupel** [comment]
Super, J'ai testé les 110 premieres chaines:
certaines chaines ne sont pas reconnues:
OCS max => 26
OCS city => 27
OCS choc => 28
OCS geants => 29
Action => 33
Sundance TC => 34
Novelas TV => 47
My Zen TV => 76
M6 boutique => 78
Astrocenter TV => 79
Planete+ crime investigation => 81
Planete+ aventure experience => 82
Museum => 84
National geographic channel => 85
toute l'histoire => 90
science & vie TV => 91
Bloomberg => 107

Le systeme ne comprends pas "zap sur comedie +"

Il y a une erreur sur 
serie club => 43 mais renvoie sur 0
MCM => mais 48 mais renvoie sur 87
PAris Premeire => 55 mais renvoie sur 28
RTL 9 => 56 mais renvoie sur 29
NRJ 12 => 62 mais renvoie sur 12
cherie 25 => 69 mais renvoie sur 25
LCI => 103 mais renvoire sur 26
France Info => 104 mais renvoire sur 27

**Comment by Aymkdn** [comment]
Pour Comédie + c'est dû, je pense, à ce que j'explique dans l'aide : 

> Si jamais votre assistant ne comprend pas quand vous dites `zappe sur ...` (et donc qu'il répond autre chose que `je zappe sur`), alors il est possible qu'il comprenne `zap` au lieu de `zappe`. Ouvrir Google Assistant sur le téléphone et dire la phrase souhaitée. Si votre phrase est reconnue avec `zap` au lieu de `zappe` alors vous devez modifier votre applet IFTTT qui permet de zapper afin d'ajouter la prise en compte de la commande `zap` en plus de `zappe`.

Merci pour avoir testé tout ça ! J'ai mis à jour ce que tu m'as dit :-)
