### ISSUE TITLE
allume la freebox et saute sur mes enregistrement au lieu de TV

### ISSUE THREAD

**Issue by CCoupel** [Aymkdn/assistant-freebox-cloud#23]
En utilisant la commande vocal "allume la freebox et zap sur XXX" avec l'option Canal Sat, l'enchainement des commande ne me semble pas bon car je me retrouve dans l'univers mes enregistrements. Pour arriver a mes fins, j'ai utilisé les commandes: 
power,wait6000,home,down,down,OK,wait2000,zappe {{TextField}}

**Comment by Aymkdn** [comment]
Alors en effet, il y avait un problème dans mon code (l'appui long se faisait pour toutes les commandes, dont le `down`). J'ai testé et maintenant cela fonctionne correctement.

Merci !
