### ISSUE TITLE
zappe sur 2

### ISSUE THREAD

**Issue by petrus55** [Aymkdn/assistant-freebox-cloud#24]
bonjour 
voila la phrase que je colle dans "Make a web request "mais ou faut il écrire la chaine 2 j ai essayé a la place de TEXTFLIED 
https://assistant-api.kodono.info/fbx/MjE4OyM1YzhmZGI4YzdjZGQy/?c=zappe {{TextField}}

mais j ai cette erreur 
Unrecognized Ingredient in action field: {{TextField}}

merci pour vos réponse

**Comment by Aymkdn** [comment]
As-tu bien choisi **"Simple phrase with text ingredient"** quand tu as créé l'applet Google Assistant ? À priori non, sinon tu n'aurais pas cette erreur.

Il ne faut pas écrire `chaine 2`, mais simplement faire un copier/coller de ce que le guide indique (puisque Google/IFTTT va automatiquement remplacer `{{TextField}}` par ce que tu as prononcé).

Regarde la vidéo qui explique comment procéder : https://www.youtube.com/watch?v=L5M8JBxht6k

**Comment by petrus55** [comment]
bonjour et merci 
j ai réussi a valider la commande ,je gardais les guillemets c est pour ça ,
mais aussi en collant le texte cela ne changeais rien comme vous expliquer ,la commande a été valider avec finish ,mais cela ne fonctionne toujours pas  donc je creuse encore .
merci pour le boulot mais pas évident .

**Comment by Aymkdn** [comment]
Il faut lire **attentivement** chaque étape expliquée dans le guide.

Si tu penses avoir suivi **scrupuleusement** les indications, et que ça ne marche toujours pas, alors regarde sur la page d'aide : https://github.com/Aymkdn/assistant-freebox-cloud/wiki

**Comment by petrus55** [comment]
bonjour
j ai réussi enfin de compte fallait faire un  copier collé, moi je collais la ligne mais je rajoutais la chaîne 2 .3. ou 4 ,alors qu il ne fallait que collé la commande éditer .
merci

**Comment by petrus55** [comment]
et cela marche aussi sur les chaines my canal en prononcent que les numéros des chaines sa marche nickel
