### ISSUE TITLE
Bug délais editeur de commande

### ISSUE THREAD

**Issue by ppicppic** [Aymkdn/assistant-freebox-cloud#25]
si on met plusieurs actions d'attente dans l'éditeur de commande, celle ci on la même durée, si on en modifie une, les autres le sont aussi.

**Comment by Aymkdn** [comment]
Oui je suis au courant mais j'ai pas eu le temps de corriger ce problème. Tu peux manuellement changer la valeur avant de coller l'URL. Je pense avoir du temps demain pour m'en occuper !

**Comment by ppicppic** [comment]
oui, j'avais noté pour l'url.
en revanche, en idée ++ pour ton éditeur (très pratique au passage!):
pouvoir ajouter une commande dans la liste, pas seulement à la fin.
quand on se rend compte qu'on a oublié une pause en testant, faut tout re-décaller :-(

**Comment by Aymkdn** [comment]
Je viens de corriger et j'ai rajouter du drag&drop donc on peut désormais déplacer les commandes avec la souris afin d'en changer l'ordre !
