### ISSUE TITLE
Vous ne pouvez pas dépasser les 25 commandes dans un seul appel.

### ISSUE THREAD

**Issue by ppicppic** [Aymkdn/assistant-freebox-cloud#26]
Je comprend la limite, mais je n'ai que 24 commandes dans ligne:

c=replay,wait3000,down,down,down,down,down,down,right,right,right,OK,wait6000,right,right,right,OK,wait3000,down,right,right,OK,down,OK

du coup, je me doute que l'action "replay" comprend plusieurs commandes qui sont décomptées aussi ?
du coup, je te laisse juger si bug ou pas.

à quelques commandes j'y étais presque, possible de légèrement augmenter ou ce n'est pas jouable?

**Comment by Aymkdn** [comment]
La commande "replay" est remplacée par plusieurs commandes/requêtes. J'essaierai de voir une solution.

**Comment by Aymkdn** [comment]
Pour le moment je préfère ne pas augmenter le nombre de commandes (comme tu le comprends c'est pour éviter les abus, car pour chaque action une requête est faite). Ici `replay` est remplacé par `home,wait4000,home,wait2000,right,up,ok`

Une solution est de découper ton action en 2 : 
  1. Une action qui va dans le Replay : `OK Google, va dans le replay`
  2. Une fois qu'il y est tu lui demandes de lancer ce que tu veux : `OK Google, lance machin chose`

Une autre possibilité est de créer une applet à deux niveaux : 
  1. Va sur https://platform.ifttt.com/ puis crée une nouvelle applet (qui aura 2 actions)
  2. La première action sera l'action `replay`
  3. La deuxième action sera `wait9000,down,down,down,down,down,down,right,right,right,OK,wait6000,right,right,right,OK,wait3000,down,right,right,OK,down,OK`

Comme ça tu peux tout lancer d'un coup.

**Comment by ppicppic** [comment]
ok, les deux solutions semble valable, je ne connaissait pas la seconde, je vois ça en rentrant ce soir.
merci de ta réactivité.

**Comment by ppicppic** [comment]
j'essaye ta seconde solution, mais impossible de créer une applet avec 2 webhooks :-(

**Comment by Aymkdn** [comment]
Ils sont relou chez IFTTT.... Peut être que c'est un bug ? J'enverrai un message à leur support technique demain pour savoir.

**Comment by Aymkdn** [comment]
Ils m'ont confirmé que (pour le moment) on ne peut pas avoir plus d'un webhook dans ce type d'applet... Donc tu vas devoir suivre la première solution...

**Comment by ppicppic** [comment]
ok,

merci quand même ;-)

pierrick
