### ISSUE TITLE
prise de controle de ma freebox par le cloud

### ISSUE THREAD

**Issue by Ghyghy31** [Aymkdn/assistant-freebox-cloud#27]
Bonjour
j'avais utilisé votre tuto il y a un peu plus d'un an afin de contrôler ma Freebox via mon Google home et push Bullet. j'avais utiliser vos commande IFTTT standart mais je m'etais fait également mes propres commandes exemple ( Freebox_home,home, right*4, ok,wait3000,ok,wait2000,down*4,ok)
Aujourd'hui j'ai mis en place votre nouveau système via la prise de contrôle par URL et ca marche niquel pour les commande standart.
Comment puis-je faire pour coder mes commandes IFTTT perso en URL ?
Comment transformer la suite de commandes dans un URL ?

**Comment by Aymkdn** [comment]
Il suffit d'utiliser la section "Créer mes propres actions" sur https://assistant.kodono.info/freebox/
