### ISSUE TITLE
guide des programmes freebox

### ISSUE THREAD

**Issue by petrus55** [Aymkdn/assistant-freebox-cloud#28]
bonjour
est-il possible de sélection guide des programmes et de le faire défiler je voudrais essayé mais je ne sait même pas par ou commencé.
merci

**Comment by Aymkdn** [comment]
1. Va sur https://assistant.kodono.info/freebox/ dans "Créer mes propres actions"
2. Choisis : 
      - **séquence de commandes permettant d'aller au « home »**, puis Ajouter
      - **touche « flèche haut » de la télécommande**, puis Ajouter
      - **touche « flèche haut » de la télécommande**, puis Ajouter
      - **touche « OK » de la télécommande**, puis Ajouter
      - Ce qui donne : 
![Capture](https://user-images.githubusercontent.com/946315/54814709-90367380-4c90-11e9-8c65-9a81b467409e.PNG)
3. Crée une nouvelle applet sur IFTTT : https://ifttt.com/create
       - clique sur **This**
       - choisis **Google Assistant**
       - choisis **Say a simple phrase**
       - entre la phrase qui va déclencher l'action : **montre moi le programme**
       - choisis une phrase de réponse : **je vais dans le guide des programmes**
       - choisis **French** pour la langue
       - après avoir validé, tu cliques sur **That**
       - tu choisis **webhook**
       - pour le champs URL tu copies/colles l'URL fournie à l'étape 2
       - OK / Finish

Maintenant quand tu dis **montre moi le programme**, il va aller dans "Guide des Programmes" de la Freebox.

Ensuite, tu peux créer une action qui réagit à la phrase **Page suivante**. Pour cela : 
1. Va sur https://assistant.kodono.info/freebox/ dans "Créer mes propres actions"
2. Choisis : 
      - **touche « volume + » de la télécommande avec un appui long** (bien choisir **avec un appui long**), puis Ajouter
3. Crée une nouvelle applet sur IFTTT : https://ifttt.com/create
       - clique sur **This**
       - choisis **Google Assistant**
       - choisis **Say a simple phrase**
       - entre la phrase qui va déclencher l'action : **page suivante**
       - choisis une phrase de réponse : **OK**
       - choisis **French** pour la langue
       - après avoir validé, tu cliques sur **That**
       - tu choisis **webhook**
       - pour le champs URL tu copies/colles l'URL fournie à l'étape ci-dessus
       - OK / Finish

Donc maintenant tu as deux commandes : 

1. **montre moi le programme** qui va dans le guide des programmes
2. et **page suivante** qui va te montrer la page suivante des programmes

**Comment by petrus55** [comment]
bonjour 
merci pour le tuto 
petit soucis a l annonce page suivante c est la barre du  volume son qui interagie .

**Comment by Aymkdn** [comment]
Oui désolé j'ai dit :  "**touche « volume + » de la télécommande avec un appui long**" alors que je voulais dire "**touche « flèche bas » de la télécommande avec un appui long**"

J'ai modifié [mon commentaire ](https://github.com/Aymkdn/assistant-freebox-cloud/issues/28#issuecomment-475560444)

**Comment by petrus55** [comment]
pas grave sa arrive 
oui je me disait aussi il y avait deux fois la même commande .

merci
