### ISSUE TITLE
La télé ne s'éteint plus.

### ISSUE THREAD

**Issue by yoel83** [Aymkdn/assistant-freebox-cloud#29]
Tout d'abord bravo et merci de ce travail.
Lorsque j'eteinds la freebox avec Google home, ma télé ne s'éteind  plus comme quand je l'éteins avec la télécommande .
Il y a t'il une astuce?

**Comment by Aymkdn** [comment]
Normalement cela doit fonctionner de la même façon qu'avec la télécommande. En tout cas c'est ce qui est constaté chez la plupart des utilisateurs : sur les 1300 personnes inscrites actuellement, qu'une seule autre personne a eu un problème similaire (qui m'a été signalé en tout cas)... Chez moi en tout cas, le comportement est le même.

Peut-être un bidouillage au niveau des paramètres de la box, par exemple la gestion de l'énergie : 
* allumer la Freebox
* aller dans le menu **Réglages**
* aller dans **Système**
* aller dans **Gestion de l'énergie**
* Pour **Action par défaut de la touche d'extinction**, il faut choisir **Mettre en veille**.

Ou un autre paramètre quelque part.... Ou bien il existe un bug dans certains box qui sont à l'origine du problème ? En tout cas, je n'ai pas de solution pour toi...

Par contre, si jamais tu trouves, je veux bien que tu m'en informes !

**Comment by yoel83** [comment]
Merci pour ta rapide réponse. 
J'avais fait cette manip que j'avais trouvé ici afin d'allumer en vocal la freebox. 
Mais cela n'empêche pas mon problème. 
Je continu à chercher merci

**Comment by Aymkdn** [comment]
OK. Je ferme le ticket en attendant. Si tu trouves quelque chose, poste le ici ;-)
