### ISSUE TITLE
Pourquoi ne pas avoir fait une vrai appli dialogflow ?

### ISSUE THREAD

**Issue by manatlan** [Aymkdn/assistant-freebox-cloud#30]
J'ai aussi pas mal joué avec "ok google" ... suis passé aussi par IFTTT ...
Mais au final, je trouve qu'on peut faire des choses bien plus interessantes avec https://dialogflow.com/ (la vraie façon "google" de créer des assistants).
ça éviterait à l'utilisateur de devoir créer ses propres commande IFTTT. mais ça vous obligerait à disposer d'un serveur http (pour héberger les interactions)
Est-ce un choix "simple" ? ou c'est pour vous éviter de devoir avoir un serveur ?
Bon, je ne suis jamais allé plus loin que de créer des assistants dialogflow pour moi, du coup, mes commandes passent par une invocation de mon assistant (roger) ... "ok google ... parler avec roger ... faire telle ou telle chose" (ou "ok google ... demander à roger de faire telle ou telle chose". (après, avec des "routines" que l'utilisateur créé : on peut éviter la double invocation)
Mais en gros ; vous hébergeriez vos commandes chez vous, et pour tout le monde ... sans devoir passer par ifttt.

Je peux aider, pour mettre ça sur les rails (bon je dis ça, mais je viens de voir qu'ils migrent tout en V2(oct.2019) ... je n'ai fait que du V1 moi ;-) )...

**Comment by Aymkdn** [comment]
(et je bouge ta question dans la version Cloud de l'assistant Freebox car je suppose que tu fais référence à ce programme là et pas à `assistant-plugins`)

**Comment by manatlan** [comment]
Je comprends tout à fait ...

Mais on est d'accord : ce serait à "free" de faire ça !!! (Ou à minima; d'exposer dans les "api freebox" un moyen de navigation dans les interfaces ... pour faciliter la tâche des personnes qui tentent d'automatiser ça)

Question subsidiare : quel est le rôle de l'applet sur la freebox ? (est-ce elle qui permet de recevoir certains ordre non possible par http ?)

SInon, tu peux close

**Comment by Aymkdn** [comment]
> quel est le rôle de l'applet sur la freebox ?

Tu veux parler de l'application du Freestore ? Elle permet de configurer la Freebox en faisant automatiquement ce qui est expliqué là : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox- ....

J'ai essayé de simplifier au maximum toutes les étapes, afin que même un novice en informatique puisse y arriver. D'où la publication de cette application (j'ai eu peur qu'elle ne soit pas acceptée par Free, mais le gars qui valide est plutôt cool et répond vite et bien aux emails !).

J'aurais trop voulu que mon service IFTTT soit publié, car ça aurait simplifié pas mal de choses encore... D'autant que j'y ai passé beaucoup d'heures dessus.... pour qu'au moment de le publier on me réclame des milliers d'euros... 👎
