### ISSUE TITLE
Freebox révolution 

### ISSUE THREAD

**Issue by David3170021** [Aymkdn/assistant-freebox-cloud#31]
Bonjour 
Je souhaiterais m inscrire sur le assistant cloud mais je ne sais pas ou aller ?
Pouvez vous m aider ?
Merci 
David

**Comment by Aymkdn** [comment]
J'ai déjà répondu à ton email.

Il y a un tutorial sur https://www.universfreebox.com/article/49079/Tutoriel-piloter-la-Freebox-Revolution-a-la-voix

Sinon il suffit de se laisser guider sur https://assistant.kodono.info/freebox/
