### ISSUE TITLE
ifttt ne communique pas avec google home

### ISSUE THREAD

**Issue by zebess** [Aymkdn/assistant-freebox-cloud#32]
Bonjour, j'ai l'impression que ma google home ne se synchronise pas avec ifttt. J'ai testé ma commande personnalisée de votre service sur un navigateur et ça réagit bien. Par contre ma google home me répond à chaque fois qu'elle ne peut pas m'aider. Le compte google home et iftt est bien le même. Je ne sais pas comment forcer la synchro ou la tester.
Merci.

**Comment by zebess** [comment]
J'ai trouvé, il fallait demander à la home de synchroniser ses appareils ...

**Comment by zebess** [comment]
Ok Google, synchronise mes appareils

**Comment by Aymkdn** [comment]
Donc c'est bon maintenant ?

**Comment by zebess** [comment]
Yes merci  ;-)
Par contre les chaînes a plusieurs numéros ne fonctionnent pas car je suis en appui long sur mes touches de télécommande. Je suis ds ce mode à cause de ma box domotique eedomus qui demande ce mode. Je voulais savoir si il y a quelques chose à faire sur votre programme pour être ds ce mode appui long ?

Envoyé de mon téléphone. 



Le 24 mars 2019 à 14:22, Aymeric <notifications@github.com> a écrit :

Donc c'est bon maintenant ?

**Comment by Aymkdn** [comment]
Oui, il suffit de remplacer la commande `zappe` par `zappelong` dans ton applet IFTTT.

**Comment by zebess** [comment]
Yes ça marche nickel. Encore merci et bravo pour le programme et tes réponses rapides.

**Comment by Aymkdn** [comment]
Cool!
