### ISSUE TITLE
impossible de créer l'applet zap $  j'ai la réponse "The recipe is for number(#) not text ($) ingredients

### ISSUE THREAD

**Issue by mlasne** [Aymkdn/assistant-freebox-cloud#33]

**Comment by Aymkdn** [comment]
Tu n'as pas sélectionné le bon type d'applet. Tu as choisi "say a phrase with a number" au lieu de "say a phrase with a text ingredient"
![Screenshot_20190324-162955__01](https://user-images.githubusercontent.com/946315/54881644-44332c80-4e52-11e9-8e2c-265afa84013a.jpg)

**Comment by mlasne** [comment]
Merci !


----- Mail original -----
De: "Aymeric" <notifications@github.com>
À: "Aymkdn/assistant-freebox-cloud" <assistant-freebox-cloud@noreply.github.com>
Cc: "mlasne" <mlasne@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 24 Mars 2019 16:31:40
Objet: Re: [Aymkdn/assistant-freebox-cloud] impossible de créer l'applet zap $  j'ai la réponse "The recipe is for number(#) not text ($) ingredients (#33)



Tu n'as pas sélectionné le bon type d'applet. Tu as choisi "say a phrase with a number" au lieu de "say a phrase with a text ingredient" 
Screenshot_20190324-162955__01
