### ISSUE TITLE
Ça ne marche plus

### ISSUE THREAD

**Issue by sPioT** [Aymkdn/assistant-freebox-cloud#34]
Bonjour,

D'abord bravo et merci pour cette initiative. Malheureusement pour moi plus aucune commande ne fonctionne depuis ce weekend. J'ai vu qu'une mise à jour de l'application était disponible sur la Freebox et j'ai fait la mise à jour ce matin sans que cela ne change quoi que ce soit.
Au niveau ifttt les applets m'indiquent qu'elles ont bien fonctionné. Si j'appelle l'URL d'une commande direct depuis un navigateur j'ai un "ok" en retour.

**Comment by Aymkdn** [comment]
Bonjour,

Peux-tu me donner un bout de ton email afin que je te retrouve dans la base de données ?

**Comment by sPioT** [comment]
Voilà mon email

**Comment by Aymkdn** [comment]
1. Va sur http://mafreebox.freebox.fr/ depuis ton réseau local et connecte-toi (afin d'accéder à l'interface Web de la Freebox)  
2. Va dans **Paramètres de la Freebox**, onglet **Mode avancé**
3. Va dans **Gestion des ports**
4. As-tu une ligne qui ressemble à celle-ci dessous ? (sauf que tu dois avoir **7485** en face de WAN au lieu de 58269)
![Capture](https://user-images.githubusercontent.com/946315/54905838-3d53fa80-4ee2-11e9-9843-98ee7d76e26b.PNG)

**Comment by sPioT** [comment]
En effet, cependant cette redirection semble pointer vers ma mibox et pas
vers la Freebox.

Je vais rajouter une règle avec le port que tu m'indique vers la Freebox.
Je ferai des essais ce soir car je suis au bureau. Je t'informe dès que
j'aurai avancé

**Comment by Aymkdn** [comment]
Il te suffit de cliquer sur le bouton "Edit" puis de sélectionner ton Freebox Player plutôt que la Mibox et ça marchera :-)

**Comment by sPioT** [comment]
Je supposé que IP source correspondent à ton serveur donc en effet rien ne
sert de garder la règle pour la mibox.

Je teste ça ce soir. 👍

**Comment by sPioT** [comment]
C'est bon va refonctionne. 👍

Je me demande comment la règle a basculé vers la mibox. Peut-être un
changement des IPs suite à un redémarrage.

En tout cas merci pour ton aide.
