### ISSUE TITLE
Commande son Freebox

### ISSUE THREAD

**Issue by quent13476** [Aymkdn/assistant-freebox-cloud#35]
Bonjour,
Je découvre suite à la réception du google mini et ca marche top.
Question pour la commande de volume est ce que l'on peut baisser plus en une seule commande ?
car avec "https://assistant.kodono.info/freebox/" point 7 " baisse le son" cela baisse trop peu.
Qu'est ce que je dois modifier ?

merci d'avance

**Comment by Aymkdn** [comment]
Remplace `soundDown*15` par `soundLongDown` qui baissera de 30 points au lieu de 15.

**Comment by ppicppic** [comment]
personnellement, à 30 c'est ok, à 15, il ne se passe rien une fois sur deux.
c'était déjà le cas avec assistant-plugin, je ne sais pas si c'est le fait d'être relié à un ampli pour le contrôle du volue.

**Comment by Aymkdn** [comment]
En effet, c'est parce que tu utilises un ampli

**Comment by ppicppic** [comment]
Bon a savoir ! 😀

**Comment by quent13476** [comment]
Parfait 👌
