### ISSUE TITLE
Dossier "Téléchargements"

### ISSUE THREAD

**Issue by M3HDiX** [Aymkdn/assistant-freebox-cloud#36]
Bonsoir,

Avant toute chose un grand merci pour le travail que tu as fourni parce que c'est juste génial.
Ma question concerne sur la possibilité d'aller sur le dossier "téléchargements" dans le disque dur. Est ce possible ?

**Comment by Aymkdn** [comment]
Oui. Utilise la section "Créer mes propres actions" sur le site pour te déplacer dans les menus de la Freebox afin d'atteindre la destination choisie. Le système ne fait que simuler les appuis sur les touches de la télécommande.

Je suis en vacances à l'étranger là donc je te laisse un peu chercher et si tu n'y arrives pas, demande moi de l'aide.

**Comment by M3HDiX** [comment]
D'accord profites bien de tes vacances je vais essayer de me débrouiller en espérant ne pas revenir t'embêter ;) 

Amuses toi bien ^^
