### ISSUE TITLE
Radio

### ISSUE THREAD

**Issue by gerardsix** [Aymkdn/assistant-freebox-cloud#37]
Bonjour.
Est-il possible de commander la radio de la freebox à la voix?

**Comment by Aymkdn** [comment]
Merci Gérard pour ton don, et merci de poster ta question ici, car je ne peux pas répondre via PayPal !

Oui c'est sûrement possible. Utilise la section "Créer mes propres actions" sur le site pour te déplacer dans les menus de la Freebox afin d'atteindre la destination choisie. Le système ne fait que simuler les appuis sur les touches de la télécommande.

Je suis en vacances à l'étranger là donc je te laisse un peu chercher et si tu n'y arrives pas, demande moi de l'aide, je ferai de mon mieux en attendant mon retour en fin de semaine !

**Comment by Aymkdn** [comment]
Où en es-tu de tes recherches ?

**Comment by gerardsix** [comment]
Bonsoir. 
Je n'ai pas encore regardé. Néanmoins il ne me semble pas trop compliqué de reproduire la suite de touches tapées pour atteindre une radio (disons France Inter) en commençant systématiquement par la touche «free» rouge. Maintenant je ne vois pas comment faire pour choisir la radio voulue comme on choisi la chaîne de télévision que l'on veut (ce qui existe déjà et que tu as fait).

⁣Cordialement,
Gérard Juin.​

Le 30 mars 2019 à 17:40, à 17:40, Aymeric <notifications@github.com> a écrit:

**Comment by Aymkdn** [comment]
Alors, en effet, si tu cherches à avoir un truc du style "mets la radio XYZ sur la Freebox" avec XYZ qui peut être n'importe quelle station, alors il va falloir que je crée une fonction spécifique. Par contre si c'est juste pour écouter telle ou telle radio, tu peux créer l'ensemble des actions toi-même.

Après, est-ce le rôle de la Freebox de jouer des radios ? En sachant que tu peux déjà demander au Google Home de te mettre n'importe quelle station ? 

Faire un système équivalent au `zappe` mais pour les radios va être très compliqué pour moi....

**Comment by gerardsix** [comment]
Tout ce que tu dis est vrai. Le seul intérêt est de jouer la radio sur un bon amplificateur. Et, effectivement, j'écoute toujours à peu près les mêmes stations radio. 
Maintenant, on s'est habitué à zapper sur d'autres chaînes sans effort.
Merci encore pour ton travail et bon dimanche.

⁣Cordialement,
Gérard Juin.​

Le 30 mars 2019 à 23:24, à 23:24, Aymeric <notifications@github.com> a écrit:

**Comment by Aymkdn** [comment]
Il y a actuellement 87 radios sur la Freebox et ça me semble vraiment beaucoup de boulot pour moi pour les prendre en compte comme le `zappe`. Je t'invite donc à créer tes propres applets pour les radios que tu utilises le plus. Si tu as besoin d'aide pour une radio spécifique, tu peux me dire laquelle et je t'aiderai.
