### ISSUE TITLE
Pas de passage sur BFM

### ISSUE THREAD

**Issue by zebess** [Aymkdn/assistant-freebox-cloud#38]
Bonjour,
Ce matin j'ai demandé à ma Google de passer sur BFM mais elle n'a pas compris. J'ai demander à passer sur BFM TV. Elle ne comprenait pas la demande. Je lui ai demandé la chaîne 15 mais ça n'a pas été mieux. J'ai donc pris mon tel pour regarder si elle comprenait bien ma demande orale en écrit et c’était bien le cas. J ai demandé de passer sur TMC puis C8 et cela n'a posé aucune difficultés. D’où peut venir ce bug?
J'ai regardé ce matin sur mon interface assistant cloud si je voyais un message d'erreur mais je n'ai pas de log à ce jour sur les erreurs.
Merci.

**Comment by Aymkdn** [comment]
Quand tu as demandé au téléphone, ça a écrit "zap" ou "zappe"? (https://github.com/Aymkdn/assistant-freebox-cloud/wiki#1-la-chaine-xyz-nest-pas-reconnue-que-faire-)

Si ça a bien écrit, c'était peut être un problème temporaire de Google ? Car s'il te répond "je n'ai pas compris", le problème ne vient pas de mon système mais de tout ce qui se passe avant (Google, IFTTT,...)

**Comment by zebess** [comment]
J'ai essayé aussi avec "passe" ou "met" qui sont des mots que j'ai enregistré sur IFTTT. Je me rappel plus ce qu'il a écrit ou pour zap mais j'avais lu l'article sur ce détail. Ce qui est surprenant c'est que quand j'ai demandé C8 ou RMC pour tester IFTTT ou Google, il a bien zappé. Alors je me suis demandé si BFM était bien enregistré et j'ai vu que ça faisait parti des premières chaines enregistrées dans votre change log. Donc là je ne sais pas d'où peu venir le blocage.

**Comment by Aymkdn** [comment]
Si ton Google a dit "je ne comprends pas" c'est que le problème était au niveau de Google. Tu as réessayé depuis ?

**Comment by zebess** [comment]
je vais retester ce soir ^^

**Comment by Aymkdn** [comment]
Du coup, tu as retesté ?

**Comment by zebess** [comment]
Oui, ça marché pour BFM.... bizarre. Une fausse alerte. Bon WE. :-)
