### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by kiri945** [Aymkdn/assistant-freebox-cloud#39]
Bonjour serait-il possible de faire une commande pour Spotify et pour les playlist de Spotify et merci pour ton travail formidable

**Comment by Aymkdn** [comment]
C'est sûrement possible. Utilise la section "Créer mes propres actions" sur le site pour te déplacer dans les menus de la Freebox afin d'atteindre la destination choisie. Le système ne fait que simuler les appuis sur les touches de la télécommande.

Je suis en vacances à l'étranger là donc je te laisse un peu chercher et si tu n'y arrives pas, demande moi de l'aide, je ferai de mon mieux en attendant mon retour en fin de semaine !

**Comment by kiri945** [comment]
Ok je réussis mais le problème c'est que je dois être toujours au même endroit si je ne suis pas au même endroit la succession de touche ne va pas fonctionner

**Comment by Aymkdn** [comment]
Commence t succession de touches par `home` qui va te placer au même endroit à chaque fois. Puis pars de là.

**Comment by kiri945** [comment]
Ah oui c'est bon je commence par home et après je mets mes succession de touche

**Comment by Aymkdn** [comment]
Oui tout à fait !

**Comment by kiri945** [comment]
c'est bon j'ai créé la commande merci maintenant je vais écrire les autres commandes pour changer de musique ou revenir en arrière

**Comment by Aymkdn** [comment]
Parfait !
