### ISSUE TITLE
Installation assistant-freebox-cloud

### ISSUE THREAD

**Issue by histoirede** [Aymkdn/assistant-freebox-cloud#4]
Bonsoir aymeric,
J’ai procédé à l’installation, pas de problèmes, tout c’est bien passé. J’ai créé une applet (allume la freebox), c’est ok. Demain je continue, mais il faut que je vois les applets que j’avais créés pour assistant-plugins afin de les supprimer pour qu’ils ne fassent pas doublons. Je continuerai demain, mais je me pose la question pour aller directement sur les chaînes Canal car sur mon profil, que je choisisse l’univers freebox ou Canal, la commande est là même. Je vais essayer d’affiner cela demain.
Merci beaucoup pour ce magnifique travail.
Cordialement.

**Comment by Aymkdn** [comment]
> sur mon profil, que je choisisse l’univers freebox ou Canal, la commande est là même

La commande est la même, mais si tu as bien choisi l'option dans ton of profil, le système va automatiquement sélectionner ce qu'il faut.

**Comment by histoirede** [comment]
Bonsoir Aymeric,
Ça marche nickel lorsque je sélectionne l’univers freebox, par contre lorsque je sélectionne l’univers canal, si je demande « Allume et zappe sur la 3 » par exemple ou n’importe quelle chaîne, je me retrouve dans mes enregistrements, et si je lui demande d’éteindre la freebox, j’ai la réponse de l’applet « zappe sur la $ » , réponse  « je zappe sur éteins la freebox ».
Avec l’assistant-plugins, tu avais créé la possibilité d’aller dans l’univers freebox ou canal par commande directement dans l’applet. Là il faut modifier sur le site si l’on veut aller sur un univers ou sur l’autre, ou y a t’il un autre moyen?
Merci beaucoup pour ton travail et pour ta réponse.
Cordialement.
Joël

Envoyé de mon iPad

**Comment by Aymkdn** [comment]
Tu peux utiliser la commande "zappelong", comme je l'explique là : https://github.com/Aymkdn/assistant-freebox-cloud/issues/3#issuecomment-472867631

**Comment by histoirede** [comment]
Re bonsoir,
Le gars qui avais le problème avec les chaînes rugby, c’était moi. 
Mais là, mon problème, c’est qu’il ne va pas dans le domaine canal mais sur mes enregistrements.
Est-ce que je peux rester sur le domaine freebox et créer un applet qui après le c=poser pourrait avoir la forme: « c=power,home,down*2,ok,zappelong # » ou quelque chose dans ce genre, c’est ce qui marchait avec assistant-plugins. Merci
Cordialement.
Joël.

Envoyé de mon iPad

**Comment by Aymkdn** [comment]
Oui tu peux. Sur ton profil tu peux créer des commandes personnalisées.

**Comment by histoirede** [comment]
Voilà, j’apporte ma maigre contribution, mais ça peut aider quelqu’un; je partage la commande pour aller sur les chaînes canal tout en restant sur l’univers freebox.
La commande vocale avec un champ nombre: « Allume canal la # »
https://assistant-api.kodono.info/fbx/NjU7IzVjODk2ZTQxMzJlMzA_/c=power,home,down,down,tv,zapellong) » « NumberField »
Désolé, il y a un retour ligne qui se fait automatiquement dans mon message après ‘-‘’, bien entendu c’est d’un seul tenant, sans espace entre assistant et api.

**Comment by Aymkdn** [comment]
N'indique pas ton URL car on y voit ton code confidentiel et n'importe qui peut alors commander ta Freebox !

**Comment by histoirede** [comment]
Ha, ok merci
Cordialement.
Joël

Envoyé de mon iPad
