### ISSUE TITLE
La radio du Freebox player

### ISSUE THREAD

**Issue by Sebtou** [Aymkdn/assistant-freebox-cloud#40]
Bonjour,

Je souhaiterais commander vocalement l'accès à la radio et aussi aux grandes chaînes fm ainsi que quelques Web radio comme RadioMeuh.com.

Serait-ce possible ? 

Cordialement, 

Sébastien

**Comment by Aymkdn** [comment]
Salut

Même réponse que juste en dessous : https://github.com/Aymkdn/assistant-freebox-cloud/issues/37#issuecomment-477477852

:-)

**Comment by Sebtou** [comment]
Oui effectivement, je viens de le lire, je ne l'avais pas vu

**Comment by Aymkdn** [comment]
Où en es-tu de tes recherches ?

**Comment by Aymkdn** [comment]
Il y a actuellement 87 radios sur la Freebox et ça me semble vraiment beaucoup de boulot pour moi pour les prendre en compte comme le `zappe`. Je t'invite donc à créer tes propres applets pour les radios que tu utilises le plus. Si tu as besoin d'aide pour une radio spécifique, tu peux me dire laquelle et je t'aiderai.
