### ISSUE TITLE
Alexa

### ISSUE THREAD

**Issue by Dav-76** [Aymkdn/assistant-freebox-cloud#41]
À quand une compatibilité Alexa ?

**Comment by Aymkdn** [comment]
Pour le moment on essuie les plâtres avec ceux qui ont un Google Home.

La façon dont Alexa traite les commandes vocales avec IFTTT est différente, moins pratique. Cela va me demander plus de tests pour rendre ça le plus simple possible.

Étant donné que je fais ça sur mon temps libre, ça arrivera aussi tôt que je peux me le permettre. 

À noter toute fois que les plus geeks peuvent utiliser ce qui existe déjà (les URL générées par le système actuel seront les mêmes). Ils devront juste faire leurs propres applets IFTTT sans aide pour le moment.

**Comment by tcsevens** [comment]
En effet c'est assez basique à faire: sur IFFTT utiliser le service "Amazon Alexa", en trigger "Say a specific phrase" avec la phrase de la commande, admettons "allume la freebox" avec "webhook" en action service pour la requête et préciser la commande.
Testé et approuvé,

Simple point de différence c'est qu'il faut utiliser le mot "déclenche", par exemple "Alexa, déclenche allume la freebox". Ce qui est un peu bête mais c'est comme ça ...

**Comment by Dav-76** [comment]
Premier pas sur IFTTT 😊
Avec Webook
"Allume la freebox" : ok
"Éteint la Freebox" : ok
"Coupe le son de la Freebox" : ok
"Remets le son de la Freebox" ok
Pour zapper c'est une autre histoire...,
Même en créant une Applet par chaîne ça ne fonctionne pas ☹️

**Comment by Aymkdn** [comment]
Ouais... Alexa ne propose pas les mêmes fonctions que Google Home... D'où le fait que ce soit plus long/compliqué à mettre en place pour avoir un truc le plus simple possible.

**Comment by Xanderyuku** [comment]
Bonjour comment réussissez vous à créer bises applet Alexa pour la Freebox révolution Dav-76 celà m'intéresse pas mal.

**Comment by Aymkdn** [comment]
@Xanderyuku  > 

1. Aller sur https://assistant.kodono.info/freebox/ dans la section **"Commandes vocales"** puis cliquer sur **"Cliquer ici pour afficher la suite"**
2. Cliquer sur chaque commande vocale et suivre les instructions... Sauf qu'au lieu de choisir **Google Assistant** pour le service, il faudra choisir **Amazon Alexa**, et **Say a specific phrase** pour chaque commande
3. Pour tester la commande (une fois l'applet créée) il faudra dire : **"Alexa, déclenche allume la Freebox"** ou **"Alexa, déclenche augmente le son de la Freebox"** (attention, il faut dire à chaque fois le mot clé **déclenche**)

**Comment by dorber2008** [comment]
Bonsoir 
Bravo pour ce travail !!!!
Pour paramétrer une commande pour Freebox delta, tu as la commande Home qui envoie vers une combinaison de touche(Home, wait et red) or, sur delta pas de touche de couleur !!!!!
Comment avoir un Home en tant que touche free ?????

**Comment by Aymkdn** [comment]
Pour info je suis en train de créer une Skill pour Alexa. Faut voir si ça fonctionne, si je peux la publier pour tout le monde, etc....

Dans l'idée, le but est de permettre d'avoir des appels de commandes plus "naturels", et surtout la prise en charge du `zappe` sur toutes les chaines sans devoir créer une applet IFTTT pour chaque chaine...

Au lieu de dire `Alexa déclenche zappe sur Gulli` (version IFTTT), il faudra dire une phrase du style : `Alexa demande à la box de zapper sur Gulli` (je ne peux pas utiliser le mot `la Freebox` car Free risque de ne pas aimer, du coup ça sera `la box`). Cela reste beaucoup plus verbeux qu'avec le Google Home + IFTTT, mais pas le choix.

À noter cependant que la personnalisation des commandes devra se faire sous IFTTT, et donc obligera de dire `déclenche`. Par exemple si on crée une commande pour redémarrer la Freebox (commande qui ne sera pas disponible avec le Skill), alors il faudra le faire sous IFTTT et dire : `Alexa déclenche le reboot de la Freebox`.

**Comment by Xanderyuku** [comment]
Super nouvelle ! Un grand merci pour ce travail !

Actuellement je passe par IFTTT et Webhooks pour lancer des requêtes URL
pour chaque touche mais effectivement obligé de dire Alexa déclenche la
télé, Alexa déclenche éteints la télé...

Sur iPhone j'ai testé le même truc en passant par l'application  Raccourcis
du coup celà me permet aussi via Siri de lancer des requêtes URL.

**Comment by Xanderyuku** [comment]
En activant le HDMI CEC on allume en même temps la télé en même temps que la Freebox, par contre comme on ne peux lancer des requêtes URL successives obligé d'ajouter un applet Alexa déclenche OK 😂 et ensuite je peux changer de chaîne.

Un coup à prendre.

**Comment by Aymkdn** [comment]
Pour info j'ai créé une skill Alexa que je viens de soumettre à Amazon. Elle est très basique pour le moment (on peut juste allumer la box et zapper sur quelques chaines), le but étant surtout de voir si Amazon l'accepte ou s'ils m'envoient chier :-)

**Comment by Xanderyuku** [comment]
Un grand merci à toi pour ce travail, je testerais  dès que possible !
C'est vrai que passer par IFTTT c'est fonctionnelnmais tellement lent.

J'ai testé aussi via l'application Raccourcis sur iphone en lançant une
requête URL qui pointe vers les boutons, ça marche mais trop lent. La seule
solution c'est la skill ou un hub Broadlink et un dongle IR mais ça gonfle
de s'équiper de tout ça pour juste changer changer les chaînes 😂

**Comment by tcsevens** [comment]
Merci à toi tout d'abord !

On peut trouver la skill sur le store d'amazon ou elle est encore en approbation ?

**Comment by Aymkdn** [comment]
Amazon m'a demandé de modifier plusieurs choses sur ma skill. De toute façon je ferai une annonce officielle (ici et sur mon Twitter) quand elle sera vraiment disponible et complète. Le site internet devra aussi être adapté etc.

Pour le moment je fais une version super light juste pour être sûr que ça fonctionne et voir les conditions imposées par Amazon. Donc même si elle était disponible elle serait inutile 😉

**Comment by LordDarkneo** [comment]
Hello! Je suis très intéressé par ce plugin, car je viens de prendre un echo dot et il ne me reste plus que la Freebox à commander pour être au top!
Si jamais, je dois pouvoir retrouver les codes que j'utilisais sur Jarvis (un autre assistant vocal), mais de mémoire c'était en bash... Je ne sais pas si c'est compatible avec la skill Alexa.

Et pour l'inutilté, je suis pas d'accord avec toi :) PErso je suis en HDMI CEC, donc le simple fait de dire "Allume (ou éteint) la télé" me permettrait déjà d'allumer et la télé et la box. A noter que nous avions fait une commande bash pour l'allumage afin de lancer directement le service télé (plutôt que de rester sur le menu de la freebox).

**Comment by Aymkdn** [comment]
J'ai peu de temps en ce moment (nouvelle maison et beaucoup de gens qui squattent durant l'été pour la voir et profiter du soleil du sud et de la piscine ^^) mais ce projet reste dans mes priorités. Je n'ai pas abandonné donc ça finira par arriver ! ☺️

**Comment by LordDarkneo** [comment]
MDR! Exactement pareil! D'où l'echo dot pour arreter de me battre avec la reconnaissance vocale de Jarvis :)

**Comment by LordDarkneo** [comment]
Hello! Je suppose que c'est déjà ce que tu itulise pour la Google Home, mais voici quelques informations tirées de Jarvis:
Url type:
command=http://hd1.freebox.fr/pub/remote_control?code=$Remote_Key&key=$variable

Pour jarvis, c'était "plus" simple, car chaque commande à son bouton (mais je pense que dans la skill c'est pareil:

Si Allume : $variable = power
command && sleep 12
$variable = OK
command

Si Eteint : $variable = power
command

Si Plus_Fort:  : $variable = vol_inc
command

Si Moins_Fort $variable =vol_dec
command

etc... Si jamais tu as besoin, je peux te sortir tous les boutons dans "variable".

Si jamais certains veulent faire le test manuellement, sur votre réseau local (PC ou smart phone en wifi) de rentrer l'url suivante dans votre navigateur:

http://hd1.freebox.fr/pub/remote_control?code=$Remote_Key&key=power

en remplacant $Remote_Key par la valeur de votre ID de télécommande (paramètre, etc...). Cela devrait avoir pour effet d'allumer votre freebox :)

A noter que parfois (pour ceux qui ont plusieurs box), hd1 peut être remplacé par hd2...

**Comment by Aymkdn** [comment]
C'est déjà ce qui est utilisé. D'ailleurs tu peux suivre le tutoriel du Google Home car ça fonctionne de la même façon pour Alexa (via IFTTT). C'est juste que IFTTT et Alexa ne sont pas optimal dans leur gestion des commandes vocales et qu'une Skill sera mieux (en particulier sur la gestion du changement de chaîne)

**Comment by Davidou62** [comment]
Bonjour,

Je suis intéressé par le pilotage de la Freebox révolution par Alexa. Quand pensez vous pouvoir  sortir la skill le permettant ?

En vous remerciant par avance

**Comment by Aymkdn** [comment]
Donner un délai va être compliqué... Je suis en train de modifier le site Web pour prendre en compte les différentes Freebox et assistants, comme Alexa, et en parallèle je dois arriver à publier la skill (et la faire accepter par Amazon).

Sachant que je ne peux m'en occuper que sur mon temps libre, le projet avance doucement :-)

**Comment by Davidou62** [comment]
Ok merci beaucoup en tout cas et s'il avance même doucement c'est tant mieux !

**Comment by Aymkdn** [comment]
La skill Alexa marche bien et est très réactive ! J'ai encore des choses à peaufiner sur le nouveau site... mais on est proche d' un lancement !! :-)

**Comment by Xanderyuku** [comment]
Super !!! Un grand merci pour ton travail voilà qui me refera passer chez
Free je pense :)

Bon weekend à toi.

**Comment by Dav-76** [comment]
Hâte du lancement !! Bravo pour tout le travail fourni !!👍
Cette skill m'éviteras l'achat d'un Broadlink RM Pro 😉

**Comment by Xanderyuku** [comment]
Le Broadlink ne peut en aucun cas gérer une Freebox sans adaptateur IR, par
contre via IFTTT une Freebox se gère sans problème.

**Comment by Aymkdn** [comment]
Ma skill Alexa a été "certifiée" par Amazon. donc maintenant je devrais pouvoir la publier dès que le nouveau site est en place. Donc si tout va bien, d'ici la fin du mois !

**Comment by Dav-76** [comment]
> Le Broadlink ne peut en aucun cas gérer une Freebox sans adaptateur IR, par contre via IFTTT une Freebox se gère sans problème.

C'était prévu d'acheter l'adaptateur IR 😉, ont va plutôt attendre la fin du mois la skill d'Aymkdn 😊

**Comment by Xanderyuku** [comment]
C'est exactement ce que je disais 👍🏻

**Comment by LordDarkneo** [comment]
> > Le Broadlink ne peut en aucun cas gérer une Freebox sans adaptateur IR, par contre via IFTTT une Freebox se gère sans problème.
> 
> C'était prévu d'acheter l'adaptateur IR 😉, ont va plutôt attendre la fin du mois la skill d'Aymkdn 😊

Je n'arrive pas bien à comprendre ces informations.... le Broadlink (RM Pro +) a déjà 2 émetteurs (IR+RF). Mais la télécommande de la Freebox (Révolution) n'est pas du tout en IR! Elle est en http. Vous avez plusieurs possibilités pour "commander" votre révolution:
- Sur le reseau local, vous lancez dans votre navigateur le lien http://hd1.freebox.fr/pub/remote_control?code=123456789&key=power ou
http://hd2.freebox.fr/pub/remote_control?code=123456789&key=power
Il faut remplacer 123456789 par la valeur de votre télécommande que vous trouverez dans le menu de la freebox.
- A distance (sur un réseau externe), il faut "juste" remplacer hd1.freebox.fr ou hd2.freebox.fr par l'ip de votre box ou votre DNS.

Personnellement, en attendant cette skill (que je n'utiliserai peut être pas car je vais passer chez SFR pour la fibre), j'ai créé des boutons virtuels sur Domoticz qui sont déclenchés par Alexa, via Alhau (un bouton pour allumer la box, un bouton pour l'éteindre, un bouton pour le zap couplé à un autre pour traduire la chaine. Je n'utilise pas la gestion du volume car j'ai une barre de son que je commande en direct pour le son.
En tout cas, merci @Aymkdn pour ton investissement sur ce sujet, bon courage pour la suite et félicitations pour ta skill ;)

**Comment by Aymkdn** [comment]
Voilà c'est en ligne ! Assurez-vous de d'abord passer par https://assistant.kodono.info/freebox/ pour créer votre compte et le configurer.

Si vous avez une Freebox Delta ou une Freebox One, j'aurais besoin d'aide (j'ai ouvert un sujet à ce propos : https://github.com/Aymkdn/assistant-freebox-cloud/issues/88) pour trouver la suite de commandes/touches qui permet de revenir au premier menu, à savoir celui-ci, où que l'on soit (enregistrements. TV, replay, Netflix …) : 
![Capture](https://user-images.githubusercontent.com/946315/73119250-5e9cd180-3f5f-11ea-9410-3d251517f9ee.JPG)

Si la skill fonctionne bien, n'hésitez pas à la noter (qu'un mec lui a mis 1 étoile car il a essayé de l'installer juste quand j'ai fermé le site mardi soir et que la page retournait un 404 à ce moment là… 👎 )

**Comment by LordDarkneo** [comment]
Pour info, la skill s'appelle "Assistant cloud pour Freebox"
Ici: https://skills-store.amazon.fr/deeplink/dp/B0844Z6JFP?deviceType=app&share&refSuffix=ss_copy
Thomas souhaite partager cette Skill Alexa Amazon
