### ISSUE TITLE
mes disques

### ISSUE THREAD

**Issue by Donload** [Aymkdn/assistant-freebox-cloud#42]
Bonjour 
bravo pour ce projet et ce travail !
je cherche à ma créer un accès direct sur "mes disques" mais pas moyen.
J'ai essayé avec disques et mes disques  rien à faire.
J'ai tenté avec le retour sur home et les directions plus ok mais en fonction de l'endroit où je me trouve le résultat n'est pas bon.
Un peu d'aide ou un truc déjà testé ?

Merci d'avance

**Comment by Aymkdn** [comment]
Si tu commences par `home` alors tu commences par toujours le même endroit... Donc à moins que ton disque dur change de place, tu devrais réussir à y aller avec les mêmes commandes....

**Comment by Donload** [comment]
non pas toujours, exemple :  je suis dans un sous menu appli, si tu fais home il revient juste d'un niveau mais pas au home de base donc tout est décalé.

**Comment by Aymkdn** [comment]
Mmmhhh non. Si tu utilises "mon" `home` ça va te ramener tout au début. Tu as testé ?

**Comment by Donload** [comment]
ton home ?
j'utilise l'assistant et je cumule home et 4 x droite puis ok
je dois tester comme ça pour voir

**Comment by Donload** [comment]
Sinon tu peux créer un chemin direct comme pour la musique ou les videos mais vers les disques ?
j'ai essayé en remplaçant musique par disques mais ne fonctionne pas

**Comment by Aymkdn** [comment]
Je peux créer un Mes Disques, mais ça sera pareil que toi... Je regarde ça quand je rentre de vacances

**Comment by Aymkdn** [comment]
Voilà j'ai rajouté une action pour "Mes Disques" (*disques*) : 
![Capture](https://user-images.githubusercontent.com/946315/55292679-1a4bae00-53ee-11e9-949e-2549d4a99191.PNG)
