### ISSUE TITLE
freebox et assistant

### ISSUE THREAD

**Issue by didou038** [Aymkdn/assistant-freebox-cloud#43]
Bonjour,

je viens de découvrir cette app et c'est ce que je cherchais depuis un moment, donc tout d'abord merci !

Néanmoins, j'ai configuré les 2 premières commandes de base pour tester, c'est à dire allumer et éteindre la freebox.

La google mini répond bien aux 2 demandes mais rien ne se passe. J'ai vérifié tous les infos comme indiqué dans l'aide et rien de particulier à signaler.
La freebox est bien active dans les paramètres, si j'injecte une commande en direct via le navigateur (pour l'éteindre par exemple) ça marche, bref, rien ne semble incohérent.
Quand je crée une commande spécifique "bouton rouge" par exemple pour tester avec création de l'applet IFTTT, la commande est bien envoyée et ça fonctionne.

Pour info, j'ai 2 players et j'ai bien mis le numéro de télécommande du player que je veux commander (celui du salon en l’occurrence).

Avec le tel ou avec la mini la requête est bien reconnu mais rien ne se passe.

J'aurai besoin d'un petit coup de main pour le coup ^^

Merci d'avance pour le coup de main ;)

mon mail stellieph... at gmail dot com

edit : il s'avère que j'étais pas sur le bon compte google où est installée et configurée la google home.
J'ai tout corriger, cette fois j'ai :
les commandes sont rejetées par la Home, les commandes en direct depuis le navigateur fonctionnent.
C'est le bazar lol

**Comment by Aymkdn** [comment]
Alors, je vois que tu as effectivement 2 comptes, et les 2 ont le **même code de télécommande**... Donc déjà, il faudrait que tu t'accordes sur quel compte va représenter quelle Freebox, et que tu inscrives le bon code télécommande !

Ensuite, il faut que tu t'assures que dans la gestion des ports, chaque compte redirige vers le bon port, et ensuite vers la bonne Freebox : 
  - stellieph : port 47812
  - didou : port 12968

Pendant que tu es dans ces vérifications, assure-toi que tes 2 box ont un bail statique pour éviter de futurs problèmes : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player

**Comment by didou038** [comment]
merci pour le retour !

pour faire simple, j'ai supprimé le compte didou comme ça pas d'ambiguité !

Mes 2 box sont en bail statique depuis toujours ;)

**Comment by Aymkdn** [comment]
Du coup t'as réussi à t'en sortir, et ça fonctionne maintenant ?

**Comment by didou038** [comment]
Du coup non, la home ne reconnait aucune commande
En direct par le navigateur les commandes sont ok, donc ça doit venir du compte google j'imagine

**Comment by Aymkdn** [comment]
Si la Home ne reconnaît pas c'est un problème de Google et de IFTTT

**Comment by didou038** [comment]
ok je vais check tout ça dans la semaine, là je sature ;)
merci pour le coup de main et bravo pour l'appli (même si ça marche pas encore chez moi quand se sera le cas se sera top ;) )

**Comment by didou038** [comment]
Hello,
je viens de delete les applets déjà fait et non fonctionnel et de les recréer. Tout semble fonctionner. J'ai rien fait de particulier, donc aucune explication sur le pourquoi du comment. Merci encore pour le coup de main et bravo pour le taf !

**Comment by Aymkdn** [comment]
OK cool :-)
