### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by melvind911** [Aymkdn/assistant-freebox-cloud#44]
Deja bravo pour votre application freebox , elle est très fonctionnel et pratique !
Je voudrais pouvoir utiliser les commandes vocal de google home pour lancer mes musiques spotify directement sur la freebox player delta au lieu de mon google home, je me demande si cela est possible ou pas ?

Merci encore pour cette super appli en tout cas, car je trouve google home bien plus pratique qu'Alexa.

**Comment by Aymkdn** [comment]
Bonjour

Je t'invite à lire ça : https://github.com/Aymkdn/assistant-freebox-cloud/issues/39
