### ISSUE TITLE
Problème Freebox Delta assistant cloud

### ISSUE THREAD

**Issue by JehutySensei** [Aymkdn/assistant-freebox-cloud#45]
Bonjour, avant tout un grand merci pour le superbe travail que vous faite ! Malheureusement, après avoir effectué toute les vérifications décrites dans la section aide, mon Google Home me répond mais ma Freebox Delta ne réagit pas. J'ai fixé l'ip du player, mes applets sont fonctionnelles (pas d'erreurs dans ifttt), le code Télécommande correspond, le compte utilisé est le même, pas d'erreur non plus sur la page d'accueil d'assistant cloud, la procédure de test via l'url de la page d'aide est concluante (ma Delta s'éteint et s'allume). Je ne comprend pas d'où peut provenir le problème. Comme indiqué à la fin de la section aide, je me permet de vous contacter à ce sujet.
D'avance merci.

**Comment by Aymkdn** [comment]
Vérifie que le port **52141** est bien ouvert et qu'il redirige vers la bonne Freebox Player (https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player)

**Comment by JehutySensei** [comment]
J'ai bien en redirection Wan : 52141 vers mon player.

**Comment by Aymkdn** [comment]
De mon côté tout à l'air normal... Et de ce que tu me dis, ta configuration est correcte également... Donc je ne vois pas ce qui peut poser problème pour toi.

[Ton adresse IPv4 publique](https://www.whatismyip.com/fr/) finit bien par .88 ?

**Comment by JehutySensei** [comment]
Non, elle se termine par .129

**Comment by Aymkdn** [comment]
Je viens de t'envoyer un email pour voir ça en privé.
