### ISSUE TITLE
petit probleme 

### ISSUE THREAD

**Issue by gibbsotis83210** [Aymkdn/assistant-freebox-cloud#47]
Super appli et bravo pour le boulot de fait.
Personnellement tout a bien fonctionné pendant 3 jours mais depuis la Google comprends l'ordre mais rien ne se passe j'ai effectué toutes les démarches d'ecrites en cas de non réponse et tout est ok . Donc je vois plus trop quoi faire pour que ça refonctionne, j'aurais besoin de conseil. Merci

**Comment by Aymkdn** [comment]
Je viens de rajouter 2 sections dans l'aide. Tu peux les vérifier stp et voir si ton problème est lié à ça ?

1.  https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-votre-adresse-ip-publique
2. https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-du-port-de-redirection

**Comment by gibbsotis83210** [comment]
merci de la reponse mais j'ai vérifié et tout est bon . Et si je supprime tout et que je recommence tout à zero ?

**Comment by Aymkdn** [comment]
Tu peux me donner un bout de ton email que je te cherche dans la base ?

**Comment by gibbsotis83210** [comment]
andre.oti... pour assistant cloud

**Comment by Aymkdn** [comment]
Je vois que tu as effectivement demandé des "on" / "off" à ta Freebox aujourd'hui.

Les paramètres ont l'air correct, et si tu as fait toutes les vérifications que je t'ai indiquées, alors je ne vois pas trop où peut être le problème...

Tu peux éventuellement relancer l'application du Freestore. Quand tu la lances tu dois choisir **"Supprimer"** (au lieu de "Quitter"), puis tu devras rentrer le **code d'activation** visible sur https://assistant.kodono.info/freebox/ afin que ça reconfigure le schmilblick.

**Comment by gibbsotis83210** [comment]
super ça marche merci et bonne continuation. Super boulot

**Comment by Aymkdn** [comment]
OK parfait !
