### ISSUE TITLE
Je reviens sur la radio

### ISSUE THREAD

**Issue by Sebtou** [Aymkdn/assistant-freebox-cloud#48]
Bonjour,

J'ai créé une commande "mets la radio" partant du home, suivi d'une combinaison de flèche allant jusqu'à la radio. Désormais je souhaiterais créer des commandes pour aller sur des radios favorites. Le problème étant que le chemin change dès que l'on est sur telle ou telle radio. Est il possible de récupérer ma commande initiale de façon automatique au début de chaque nouvelle séquence pour zapper sur une radio ? Ou bien d'avoir une séquence comme il en existe pour aller sur les enregistrements ou bien ma musique ?

Merci d'avance, 

Sébastien

**Comment by Aymkdn** [comment]
Je n'ai pas compris...

> Le problème étant que le chemin change dès que l'on est sur telle ou telle radio

C'est quoi qui change exactement ? L'emplacement de la radio est à priori toujours le même dans l'interface "Radios" (sauf si Free vient à ajouter/retirer des radios très régulièrement, mais j'en doute)

> Est il possible de récupérer ma commande initiale de façon automatique au début de chaque nouvelle séquence pour zapper sur une radio ?

Désolé mais je n'ai rien compris à cette phrase... Un exemple peut-être ?

> Ou bien d'avoir une séquence comme il en existe pour aller sur les enregistrements ou bien ma musique ?

Pour aller dans Radios la séquence est : `home,wait2000,right,right,down,down,down,ok`

Attention, je limite à 25 actions par appel (là on en a déjà 10 car `home` équivaut à 3 appels côté serveur).

**Comment by Sebtou** [comment]
Par exemple, pour aller sur rtl, le chemin est différent si l'on part de fun radio ou de jazz radio. D'où la nécessité de revenir à l'accueil de la radio avant de repartir sur une autre station.

Donc afin d'économiser les commandes, et éviter de répéter à chaque fois "home,wait2000,right,right,down,down,down,OK". Je souhaitais une commande compacte pour aller direct sur l'accueil de la radio

Enfin, le but avouer est d'aller chercher une ou 2 Web radio un peu loin dans les menus...

**Comment by Aymkdn** [comment]
> Enfin, le but avoué est d'aller chercher une ou 2 Web radio un peu loin dans les menus. Mais il me semble comprendre que même réduite, une commande peut correspondre à plusieurs appels pour le serveur...

En effet.... Il faudrait le faire en deux temps.
Tu crées une applet "va dans mes radios", et une autre applet "mets fun radio". 

Dans la seconde applet tu la commences par `wait10000` (pour attendre 10 secondes). Il faudra peut être rajouter deux ou trois secondes avec un  `wait3000` supplémentaire (je limite à 10 secondes par commande `wait`). Suivi par les commandes depuis Mes Radios pour aller jusqu'à Fun Radio.

Ensuite il faudra dire "OK Google, va dans mes radios, et, mets Fun Radio". Grâce à la double compréhension des commandes par le Google Home ça devrait marcher. 

Si tu es déjà dans Mes Radios, peut être qu'une combinaison de commandes (que je devrais tester) pourrait te ramener en haut de Mes Radios, plus rapidement (sans attendre les 12 secondes). Mais du coup il te faudra une autre commande vocale spécifique à cette action.... Car non, on ne peut pas détecter dans quel menu on se trouve (malheureusement)!

**Comment by Sebtou** [comment]
Aaah! il y a une double compréhension de commande ! Effectivement dans ce cas, je vais essayer. Merci.

**Comment by Aymkdn** [comment]
Oui, Google Home peut enchaine plusieurs commandes : https://www.begeek.fr/google-home-peut-desormais-traiter-trois-commandes-a-la-suite-278510
