### ISSUE TITLE
Commande home 

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#49]
Bonsoir 
Bravo pour ce travail !!!!
Pour paramétrer une commande pour Freebox delta, tu as la commande Home qui envoie vers une combinaison de touche(Home, wait et red) or, sur delta pas de touche de couleur !!!!!
Comment avoir un Home en tant que touche free ?????

_Originally posted by @dorber2008 in https://github.com/Aymkdn/assistant-freebox-cloud/issues/41#issuecomment-479191825_

**Comment by Aymkdn** [comment]
Désolé la documentation n'était à jour.

La commande `home` équivaut à `home, wait4000, home`. Il n'y a donc plus l'utilisation de `red`.

**Comment by dorber2008** [comment]
Merci pour ta réponse rapide !
J'ai essayé ceci pour aller dans Replay (agencement perso des différents menus !!!):
Home,wait2000,down,wait2000,ok
Et il m'envoie sur "enregistrer" la chaîne en cour !!!

Encore merci pour ton boulot !!!!

**Comment by Aymkdn** [comment]
N'ayant pas de Delta je ne sais pas à quoi ressemble l'interface, et je ne peux pas tester...

Je viens d'ajouter la commande `free` qui permet de simuler juste un appui sur le bouton Free de la télécommande. Si cela peut t'aider ?

**Comment by dorber2008** [comment]
Nickel cette commande free ! 
Maintenant, le tout et de faire fonctionner la combinaison avec ifttt sous Google assistant ou amazon Alexa !!!!
Combinaison: free,wait1000,down,wait1000,ok,wait1000,down,wait1000,down,wait1000,down,wait1000,down
En test, ça fonctionne parfaitement !!!
PS: cette combinaison n'est que bonne sur ma delta étant donné que mes menus sont personnalisés !!!!
Je vous tient au courant ....

**Comment by dorber2008** [comment]
Bon.... Pour l'instant ça ne va pas .....
J'ai essayé toutes les versions possibles (Google assistant et amazon Alexa (avec la technique du "declenche"!)) avec toutes les phrases simple mais rien n'y fait !
Alexa dit qu'elle ne comprend pas puis coupe.
J'ai une petite question: si je comprends bien, l'ordre que l'on donne à Alexa peut être n'importe quoi a condition que la combinaison d'action fonctionne non ?

**Comment by Aymkdn** [comment]
> Alexa dit qu'elle ne comprend pas puis coupe.

Assure-toi d'avoir bien utilisé le même compte Amazon pour Alexa et IFTTT.

> si je comprends bien, l'ordre que l'on donne à Alexa peut être n'importe quoi a condition que la combinaison d'action fonctionne non ?

Tout à fait.

**Comment by dorber2008** [comment]
J'ai tout vérifié, refait, les comptes sont ok mais rien à faire .... Ça ne fonctionne pas !
Les autres commandes fonctionnent parfaitement !
Bizarre bizarre ......

**Comment by Aymkdn** [comment]
> Les autres commandes fonctionnent parfaitement !

Les autres commandes Alexa liées à la Freebox ? Quoi qui marche / qui ne marche pas ?

**Comment by dorber2008** [comment]
Les commandes qui fonctionnent sur Alexa avec Google assistant:
Allume la Freebox
Éteind la Freebox
Mets le volume à #
Augmente le son (pas de 20 chez moi )
Baisse le son (20 aussi !!!!)
Coupe le son
Remets le son

Celles qui ne fonctionnent pas:
Allume la Freebox et zappe sur $
Zappe sur la $
Mets le Replay
Va dans photos

**Comment by Aymkdn** [comment]
> Les commandes qui fonctionnent sur Alexa avec Google assistant

Cette phrase ne veut rien dire. Soit tu utilises Alexa, soit Google Assistant, mais pas les deux en même temps !
J'imagine que tu voulais écrire : *"Les commandes qui fonctionnent sur Alexa avec Assistant Cloud"*

Pas étonnant que `Allume la Freebox et zappe sur $` et `Zappe sur la $` ne fonctionnent pas avec Alexa, puisqu'Alexa ne fonctionne pas comme Google, à qui on peut dire "prend cette phrase, et ce morceau-là tu dois l'interpréter".

Par contre, `Mets le Replay` et `Va dans photos`, si tu as mis le bon trigger Alexa, et si tu as utiliser la bonne commande, alors pas de raison que la commande vocale ne soit pas reconnue et que l'action ne soit pas effectuée.

**Comment by dorber2008** [comment]
Pourtant, il faut bien choisir Google assistant lors de la création de l'applet !?!?!?

**Comment by Aymkdn** [comment]
Si tu utilises Alexa, non il faut choisir "Alexa"....

Si tu utilises Google Home / Google Assistant, il faut suivre les instructions du site et choisir "Google Assistant".

**Comment by dorber2008** [comment]
Ben... les commandes qui fonctionnent pour le moment, fonctionnent parfaitement bien ( bien mieux qu'avec Ok Freebox soit dit en passant) en appelant Alexa et les applets sont bien créés avec le service Google assistant puis webhooks sur ifttt !

L'inconvénient quand je passe par Alexa sur ifttt est le "déclenche" a dire a chaque fois !!!!!

Que remplace les $ de google dans Alexa ????

**Comment by Aymkdn** [comment]
> en appelant Alexa et les applets sont bien créés avec le service Google assistant puis webhooks sur ifttt !

Non. Le service Google Assistant de IFTTT répond au Google Home, pas à Alexa. Si tu dis `Alexa, déclenche allume la Freebox`, c'est le service Alexa de IFTTT qui prend en charge, pas le Google Assistant.

Utilises-tu Google Home chez toi ?? Si non, alors tes applets sont inutiles car elles ne se déclencheront pas...

Si tu dis juste `Alexa, allume la Freebox` (sans utiliser le mot de clé **"déclenche"**) et que ta Freebox s'allume, alors il est possible que le Alexa de la Delta réponde comme si tu avais dit `OK Freebox`, et donc ça passe par le programme créé par Free et non pas mon service Assistant Cloud.

**Comment by dorber2008** [comment]
Je comprends ce que tu dis, mais avant de passer par assistant cloud, Alexa n'avait aucune action sur la Freebox allumage, volume etc ! 
Avant: "Alexa allume la télé" (ou la Freebox) réponse :" je ne trouve pas de skills video pour .... Etc..."
Maintenant : "Alexa allume la Freebox"
Réponse : la TV s'allume et se met sur le menu TV

Et je le rappelle je n'est aucun applet Alexa !

**Comment by Aymkdn** [comment]
> Maintenant : "Alexa allume la Freebox"
> Réponse : la TV s'allume et se met sur le menu TV

Je suis sûr à 100% que ça n'a rien à voir avec IFTTT. Peut-être que Free a poussé une mise à jour ? Regarde sur https://ifttt.com/activity pour voir les applets qui ont été enclenchées.

Aussi, donne moi un bout de ton email que je puisse te retrouver dans la base et que je regarde ton activité.

**Comment by dorber2008** [comment]
Dorber....@gmail.com

**Comment by Aymkdn** [comment]
Je n'ai personne avec cet email dans la base de données... Tu peux vérifier sur https://assistant.kodono.info/freebox/ l'email que tu as utilisé pour t'inscrire.

**Comment by dorber2008** [comment]
Oupsss
Ta..@free

**Comment by Aymkdn** [comment]
J'imagine que tu n'es pas Tania ? Donc tu dois être l'autre user ;-)

La dernière commande reçue de toi date du 3 avril.

**Comment by dorber2008** [comment]
Tu as raison je ne suis pas Tania !!!!

**Comment by dorber2008** [comment]
Ben.... Sur mon activity la dernière date c'est aujourd'hui !!!!

**Comment by Aymkdn** [comment]
Et bien, rien n'a été reçu sur mon serveur depuis le 3 avril pour ton compte.

**Comment by dorber2008** [comment]
Quoi qu'il en soit, les applets qui fonctionnent date du 30 mars

**Comment by Aymkdn** [comment]
Donc comme je te l'ai dit, les commandes vocales de ton Alexa sont celles créées par Free. Si tu souhaites zapper sur une chaine, [d'après ce forum qui répertorie les commandes Alexa pour la Delta](https://freebox.toosurtoo.com/forum/viewtopic.php?f=123&t=22868&sid=c5f4ee31b91ec80966214ca2c1e0e82c), tu dois dire `mets TF1` et pas `zappe sur TF1`
