### ISSUE TITLE
Plusieurs Freeplayer

### ISSUE THREAD

**Issue by collicalex** [Aymkdn/assistant-freebox-cloud#5]
Bonjour,

Tout d'abord bravo pour ce travail!
Est ce que cela fonctionne avec plusieurs Freeplayer dans le même foyer?

**Comment by Aymkdn** [comment]
Théoriquement, oui. Il faudrait créer deux comptes différents sur le site. Ensuite il faudra créer des applets différentes dans IFTTT, du genre "allume la Freebox du salon" ou "zappe sur BFM sur la Freebox de la cuisine", afin que les commandes s'exécutent sur la bonne Freebox

**Comment by collicalex** [comment]
Ok, j'avoue que je n'ai pas (encore) installé le soft sur le player, donc pas testé.

Je m'étais codé un petit truc maison pour gérer tout ça (avec la contrainte d'un pc allumé H24, donc votre service "cloud" ma parait nettement mieux)... j'avais contourné le problème de la façon suivante:

"Dis google, allume la freebox <salon>"
Le nom de la pièce est un paramètre dans mon applet IFTTT et dans mon appli j'avais configuré un freeplayer <salon>, un freeplayer <chambre> (j'ai un google home par pièce)
A partir de là, n'importe quelle interaction (chaine suivante par exemple), se fait avec le dernier freeplayer allumé (je ne regarde qu'un freeplayer à la fois) gardé en mémoire dans l'appli.

Si je comprends bien votre modèle, il faut installer une appli par freeplayer.. qui ne peuvent pas communiquer entre elles? Donc pas trop faisable de savoir laquelle interagit... Donc lot de commandes IFTTT  par freeplayer obligatoire?

**Comment by Aymkdn** [comment]
> Donc lot de commandes IFTTT par freeplayer obligatoire?

Oui.

Ça représente une douzaine d'applets par player pour être assez complet.
