### ISSUE TITLE
perte total avec GH

### ISSUE THREAD

**Issue by petrus55** [Aymkdn/assistant-freebox-cloud#50]
bonjour

Depuis quelques jours les commandes ne répondent plus avec le GH , il me répond je zappe sur la 3  mais plus rien ne se passe de même pour le volume, avant j ai eu une panne de courant ,et depuis hier je suis passer a la fibre free , autrement le GH marche bien avec les objets connecté etc...

merci

**Comment by Loeildejoe** [comment]
Pareil pour moi  depuis plusieurs jours. ... 
ex : Ok Google "Eteinds la Freebox"
"OK? c'est fait"
et rien ne se passe alors que ça marchait impeccable..
Merci

**Comment by Aymkdn** [comment]
Essaie de relancer l'application depuis le Freestore pour que ça mette à jour tes informations, puis reteste.

**Comment by Aymkdn** [comment]
Quand tu lances l'application du Freestore, choisis "Supprimer" (au lieu de "Quitter"). Il va te demander ton code d'activation : tu trouves celui-ci sur https://assistant.kodono.info/freebox/

**Comment by Loeildejoe** [comment]
Bon ... ça marche ... :) :) .... j'ai supprimé ma configure et recommencé
... tout remarche sans problèmes.
En tout cas, encore bravo :) .... c'est vraiment un bonheur et en plus
quelle facilité pour mettre en place .... Encore bravo.



*J@ël CARPENTIER*
joedieppe@gmail.com

**Comment by petrus55** [comment]
bonjour
cela remarche après avoir suivi les instructions ci dessus .
merci

**Comment by Aymkdn** [comment]
Si le problème se reproduit, je vous invite tous les deux à jeter un œil à cette section : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player
