### ISSUE TITLE
déconnexion ou démarrage freebox 

### ISSUE THREAD

**Issue by petrus55** [Aymkdn/assistant-freebox-cloud#51]
bonjour

j ai constaté qu'après un de redémarrage ou déconnexion de la freebox  cela ne fonctionne plus faut retourner sur le freestor et refaire la manip et sa règle le problème .

merci

**Comment by Aymkdn** [comment]
C'est parce que ton Player n'a pas d'IP fixe. J'explique comment résoudre ce problème là : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#mettre-un-bail-statique-au-player
