### ISSUE TITLE
Accès aux photos sur disque dur

### ISSUE THREAD

**Issue by dcnfurter** [Aymkdn/assistant-freebox-cloud#52]
Bonjour,

Un grand bravo pour ce travail.

J'essaie de mettre au point une commande qui me permet d'accéder à des photos de mon répertoire et de les lancer en aléatoire.
Depuis google je mets au point l'url et j'en suis à : https://assistant-api.kodono.info/fbx/xxx__/?c=disques,wait8000,down,ok,wait600,down,down,wait200,ok,wait1000,down,down,ok,wait2000

et je suis loin d'avoir fini...

Mais déjà à ce stade j'ai un message : Vous ne pouvez pas dépasser 6 commandes 'wait' dans un seul appel.

Est il possible d'outrepasser cette limite (je pense que je ne devrais pas être loin des 15 wait).

Par avance, merci et encore bravo.

Dic.

**Comment by Aymkdn** [comment]
Pour le moment non, on ne peut pas dépasser cette limite (pour éviter les abus).

Je réfléchis à proposer des options payantes pour débloquer ce genre de chose par exemple (ou autre modèle économique pour m'aider avec les diverses dépenses). 

En attendant, tu peux essayer de décomposer en plusieurs commandes. Par exemple commence par une commande "va dans les disques", puis une fois dans les diques tu peux dire "va dans mes séries".

**Comment by dcnfurter** [comment]
Merci. Ça m'embête car je voulais un truc simple pour ma femme. Et que 2 ou 3 commandes ça va la rebuter. Mais tant pis. On fera avec.

A nouveau merci pour tout ce qui a déjà été fait. J'attends les options (si ce n'est pas sous forme d'abonnement).

**Comment by FredSan83** [comment]
Salut Dic,

Aymeric, si tu me le permets, nous pouvons peut-être recommander à Dic la lecture de notre issue : [https://github.com/Aymkdn/assistant-freebox/issues/18#issue-408441671](url)

Évidemment ce n'est pas le même plugin et nécessite un pc tournant dans le même créneau horaire que la Freebox mais, je pense, qui répond tout à fait au besoin de Dic avec ta commande "folder" et mon applet "Diaporama"

@+

**Comment by Aymkdn** [comment]
C'est en effet pas la même chose car [`assistant-freebox` nécessite un ordinateur qui tourne 24h/24](https://aymkdn.github.io/assistant-plugins/), qui soit branché sur le réseau, et des connaissances informatiques un peu poussées.

**Comment by FredSan83** [comment]
c'est bien ce que je disais !
(merde je constate que le lien est foireux, tu peux le corriger ?)

**Comment by FredSan83** [comment]
je l'ai fait !

**Comment by FredSan83** [comment]
PS : éventuellement tu peux lui communiquer mon adresse perso et je lui assure le tutorat.

**Comment by dcnfurter** [comment]
Merci FredSan de t'intéresser à mes soucis. Malheureusement Aymeric a raison. Avoir une machine dédiée est pour l'instant rédhibitoire. Je ne désespère pas de monter  un raspberry un jour. Mais pas pour l'instant. 
Merci en tout cas.
