### ISSUE TITLE
Nouveautés à venir

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#53]
Voici un aperçu des différentes nouveautés sur lesquelles j'aimerais travailler ces prochains mois : 

- [x] **Skill pour Alexa** : 
   * [x] Création d'une version simplifiée pour tester
   * [x] En attente de validation par Amazon
   * [x] Amélioration de la Skill pour supporter toutes les commandes par défaut
- [ ] **Intégration dans Google Home**
   * [Voir cet autre sujet](https://github.com/Aymkdn/assistant-freebox-cloud/issues/59)
- [ ] **Simplifier la configuration IFTTT** : 
   * Pour cela j'aimerais étudier la possibilité avec une application mobile (Android / iOS), ou à défaut un *addon* pour Chrome ou Firefox
- [x] **Meilleure gestion des différentes Freebox**
   * L'idée est d'enregistrer le modèle de Freebox (et le type d'assistant) lors de l'inscription pour ensuite adapter les étapes suivantes, les commandes par défaut, la configuration, les conseils, etc.
- [x] **Commandes personnalisées plus visuelles et simplifiées**
   * Grâce à une image de la télécommande de la Freebox (selon le modèle sélectionné) on pourra composer ses propres commandes : on cliquera sur les touches de la télécommande et ça ira sélectionner l'action associée dans les menus déroulants
- [ ] **Mise en place d'un modèle économique**
  * [Voir cet autre sujet](https://github.com/Aymkdn/assistant-freebox-cloud/issues/54)

**Comment by LeTailleCrayon** [comment]
Bonjour,
J'ai fait un petit modèle d'interface pour les commandes personnalisés. Pour l'instant, je ne l'ai fait qu'avec la Freebox Révolution et ce n'est pas encore parfait, notamment pour les touches directionnelles...
[https://drive.google.com/file/d/1vzYnQK-N0zh_5Ofp-PmH-IZNDgboioPz/view?usp=sharing](url)

**Comment by Aymkdn** [comment]
Merci. Depuis mon déménagement, j'ai très peu de temps libre pour me pencher sur ce projet... Mais je compte bien m'y replonger dès que j'aurai de la dispo !
