### ISSUE TITLE
Modèle économique

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#54]
Je ne m'attendais pas à un tel succès pour ce service... Mais qui dit succès dit aussi des dépenses qui se profilent.

Quelques exemples de dépenses : 
  - Si j'ai besoin d'envoyer un email à tous les utilisateurs pour une annonce importante (comme une maintenance du serveur ou autre), je dois débourser 8€/mois pour un service de type MailJet ou MailChimp
  - Le serveur qui gère le service (environ 15€/mois) est assez vieux même s'il tient bien la charge pour le moment, mais que va-t-il se passer quand je vais ouvrir aux utilisateurs d'Alexa, ou si un gros site (genre Le Monde) vient à faire un article pour en parler ? Il pourrait être nécessaire de prendre un serveur plus puissant, et peut-être deux serveurs pour faire du *load balancing*
  - Je réfléchis à proposer une application mobile pour aider à la configuration sur IFTTT, mais juste pour publier une application sur l'Apple Store je dois débourser 99€/an, et 25€ (en une seule fois) pour le Google Play Store, et cela même si l'application est gratuite
  - Je ne parle même pas de la création d'un service dédié sur IFTTT qui coûte plusieurs dizaines de milliers d'euros par an !
  - J'aurais voulu acheter un nom de domaine spécial, mais là encore il faut compter entre 10€ et 150€ par an selon le domaine acheté

Bref, en plus d'y consacrer énormément de temps, si je souhaite continuer à améliorer ce service, il va me coûter un peu d'argent. Je réfléchis donc à un modèle économique le plus raisonnable.

L'idée que j'ai pour le moment est de continuer de proposer un service gratuit pour tous mais sans accès aux commandes personnalisées (l'utilisateur est donc limité aux commandes vocales que j'ai pré-définies et qui couvrent la plupart des besoins de monsieur et madame tout-le-monde).

Ensuite on aurait une option payante (5€ à payer une seule fois) qui permettrait d'avoir accès aux commandes personnalisées, mais soumis à des limitations de ressources (nombre d'actions par commande, nombre de `wait` par appel, nombre de commandes par minute), comme c'est le cas aujourd’hui.

Et enfin une option payante différente (10€ à payer une seule fois) qui inclurait les commandes personnalisées et qui, en plus, relèverait les limites de ressources imposées, pour les quelques personnes qui ont des besoins spécifiques.

En plus de cela, je pourrais proposer un [Tipeee](https://fr.tipeee.com/about) (comme font beaucoup de Youtubeurs et autres créateurs) pour ceux qui souhaiteraient m'encourager dans le développement et l'amélioration du service, et dont la souscription débloquerait les options pré-citées.

Je suis preneur de vos avis :-) Il s'agit juste d'une idée pour le moment, qui n'engage en rien sur ce qui pourrait ou pas arriver.

PS : bien sûr, les gens qui ont déjà fait un don du bon montant auront dores et déjà accès aux options indiquées

**Comment by ppicppic** [comment]
je comprend ta problématique, rencontré assez souvent dans ce genre de service ( je pense à contrlicz par exemple)
néanmoins, je doute que l'option de paiement unitaire puisse te permettre de tenir à la longue, si on paye une fois, sur le temps, tu n'auras plus d'entrée mais toujours des serveur à faire tourner.
n'oublies pas également de jeter un œil du côté législatif du sujet, tu fournis un service 'payant', quid des garanties? si tu fermes du jour au lendemain ?

**Comment by Aymkdn** [comment]
> néanmoins, je doute que l'option de paiement unitaire puisse te permettre de tenir à la longue, si on paye une fois, sur le temps,

C'est pas faux, mais en même temps, j'ai toujours trouvé ça relou les abonnements, et je préfère donner 5€ ou 10€ d'un coup plutôt que d'être abonné. Même si, là, l'abonnement serait gratuit pour les options de base, de 0.50€/mois (pour le déblocage des commandes personnalisées), et 1€/mois pour le "tout option", ce qui me semble raisonnable.

Malgré tout il y a de nombreuses personnes qui continuent à s'inscrire tous les jours, et je pense que ça continuera comme ça tout le temps (au fur et à mesure qu'il y a de nouveaux abonnés Free ou de gens qui ont un assistant vocal). Je pense donc que le paiement en une fois reste viable, et comme je l'ai indiqué je pourrais mettre en place un système de Tipeee également.

Rien n'empêche que quelques mois/années plus tard je décide de passer à un abonnement si je vois que la solution actuellement n'est pas viable financièrement.

> n'oublies pas également de jeter un œil du côté législatif du sujet, tu fournis un service 'payant', quid des garanties? si tu fermes du jour au lendemain ?

En effet, un aspect à étudier. J'ai déjà mis en ligne un "Privacy Policy" (requis par Amazon Alexa), et sûrement que je ferai un "Term of Use" aussi.

Je continue à étudier la question tandis que je travaille sur les [nouveautés](https://github.com/Aymkdn/assistant-freebox-cloud/issues/53) !

Il n'est pas impossible non plus que je fasse un vote/sondage auprès des personnes inscrites durant cette phase de test pour connaitre leur avis sur la question. À réfléchir.

Merci de ton avis :-)

**Comment by Vinsyl33** [comment]
Bonsoir Aymeric,
A tout hasard je suis venu sur ton site pour voir les nouveautés étant déjà utilisateur de ta solution et je viens de voir ton post donc voici mon avis.
Je suis un peu de l'avis de ppicppic er je pense qu'un paiement one shot ne te permettra pas de tenir dans le temps.
Il est vrai qu'un abonnement est peut être plus difficile à mettre en place et à gérer mais je pense que ce serait le plus juste. Je trouve que payer, par exemple, 0,99€ par mois, n'est pas aberrant. Tu pourrais proposer aussi un paiement unitaire de 10€ pour 1 an, faire un tarif réduit pour les étudiants... Tu pourrais aussi proposer une période d'essai d'un mois afin de permettre au gens de tester et de se rendre compte qu'une fois qu'on utilise ta solution on ne peut plus s'en passer:-). Je pense que même utiliser les fonctions de bases mériteraient qu'on paye aussi.
Bonne soirée.

**Comment by LeTailleCrayon** [comment]
(Merci de ne PAS utiliser Google Traduction sur ce Post !)

Bonjour,
Je trouve que faire payer des utilisateurs pour les fonctionnalités personnalisées n'est pas une très bonne idée, j'explique :
Si les gens sont attirés par ce service c'est pour sa gratuité ! Si demain, le site devenait payant (même si ce n'est que pour quelques fonctions), le site attirerait moins de monde ! Il faudra également bien maîtriser la communication avec les utilisateurs déjà inscrits pour leur expliquer qu'ils devront payer pour ce qu'ils utilisaient peut-être déjà et Gratuitement ! Je comprends qu'il y a besoin d'argent, mais proposer un service payant n'est pas forcément la bonne solution ! Il vaut mieux chercher à faire des économies : 
 En ce qui concerne l'Application, elle pourrait être en APK ou en PWA (sur iOS), cela permettrait de ne pas payer les frais du Play Store et de l'App Store et le fichier pourrait être sur le site. Personnellement, je trouve la création d'un service dédié est inutile car il est simple de créer des Applets avec Webhooks, il faut juste fournir un bon Tutoriel ce qui est déjà le cas ! En ce qui concerne le nom de domaine spécial, je trouve également que c'est inutile car des solutions comme Bitlink (bit.ly/quelquechose) existent déjà ! En ce qui concerne les Emails, c'est difficile... Il pourrait par exemple avoir des notifications via l'application ! Pour le serveur, il n'y a pas vraiment de solutions... En ce qui concerne le paiement, il serait possible de faire payer les utilisateurs afin qu'ils débloquent par exemple un nombre plus important de Wait par Applet ou bien proposer un Pack pas cher qui inclut les Appuis Longs même si je redis que faire payer les utilisateurs n'est vraiment pas une bonne solution ! 

En espérant que mon Post sera lu
En attendant une réponse de votre Part
