### ISSUE TITLE
Erreur soundLongU

### ISSUE THREAD

**Issue by LeTailleCrayon** [Aymkdn/assistant-freebox-cloud#55]
(Merci de ne PAS activer Google Traduction sur ce Post !)
Bonjour,
J'ai remarqué une erreur sur GitHub à Propos de l'appui Long sur la touche Vol + , en effet il est indiqué sur GitHub que la commande est soundLongU au lieu soundLongUp comme indiqué sur le site. Lequel des 2 est correct ?

Merci d'avance,
En espérant une réponse de votre part.

**Comment by Aymkdn** [comment]
C'est bien "Up"!

**Comment by LeTailleCrayon** [comment]
Merci !
