### ISSUE TITLE
problème 

### ISSUE THREAD

**Issue by mnms13770** [Aymkdn/assistant-freebox-cloud#56]
bonjour,
aucune commande ne marche..

 j’ai bien regardé l’aide en ligne c’est bien le même compte pour google et ifttt pourtant google home ne reconnais rien... 
merci pour ton aide 
cldt

**Comment by mnms13770** [comment]
précision dans ifttt je suis en « never Run » ...

**Comment by Aymkdn** [comment]
C'est donc la liaison entre Google et IFTTT le problème.

Tu es sûr que tu utilises bien le même compte Google ?
Quand tu dis une phrase clé, le Home te répond qu'il ne comprend pas, c'est bien ça ? 
Tu peux essayer de déconnecter le service Google de IFTTT via https://ifttt.com/services/google_assistant/settings puis de le reconnecter.

**Comment by mnms13770** [comment]
merci pour ta réponse ;) 
oui c’est bien le même compte google et en effet l’assistant ne comprend pas du genre « et là c’est le bug » 
je vais essayer de deco/ reco 
merci ;)

**Comment by mnms13770** [comment]
Bon j’ai pas vérifié avant je me suis déco et reco ça ne marche toujours pas en même temps c’est normal je n’ai plus aucun Applets dans un IFTTT... 
je vais tout refaire ...

**Comment by mnms13770** [comment]
après avoir tout remis Toutes les commandes tout marche parfaitement 😉
je te remercie pour le travail accompli👌

**Comment by Aymkdn** [comment]
Cool!

**Comment by ptibob76** [comment]
Bonjour, je me permet de mettre un message mais j'ai le même problème depuis hier soir (depuis la mise a jour de google home) et j'ai tout refait à zéro.
Réinstallation, déconnexion de Pushbullet et IFTTT, reconnexion de Pushbullet et IFTTT, liaison des comptes, modification du fichier configuration.json (code télécommande + Token), création d'une applet Freebox et installation d'une applet toute faite mais le problème c'est que j'ai beau dire la phrase mais rien ne se passe dans la fenêtre "Start" donc rien du coter de Pushbullet.
Est-il possible d'avoir un coup de main pour régler le problème svp ?

**Comment by Aymkdn** [comment]
Pour @mnms13770  le problème semble lié à un problème entre les services Google et IFTTT puisque dans https://ifttt.com/activity rien n'apparait.

Je viens de tester chez moi, et même soucis, donc visiblement il y a un problème entre ces deux services qui touchent tout le monde (ou une partie des utilisateurs). Donc faut attendre pour le moment...

**Comment by ptibob76** [comment]
@Aymkdn Merci pour la réponse rapide, j'ai essayer de voir partout et je viens d'essayer ton nouveau concept de la freebox revolution par la voix mais pareil elle ne comprend pas l'action qu'on lui demande et sur [https://ifttt.com/activity](url)  j'ai [https://image.noelshack.com/fichiers/2019/32/5/1565356451-sans-titre-2.jpg](url)

**Comment by Aymkdn** [comment]
Oui, comme indiqué, le problème touche les gens à travers le monde. J'ai envoyé un tweet à IFTTT et y'a quelqu'un qui a dit avoir le même problème: https://twitter.com/aymkdn/status/1159809483985608705

Donc il n'y a rien à faire pour le moment, à part attendre qu'ils fixent le problème.
