### ISSUE TITLE
L'assistant me répond mais rien ne se passe

### ISSUE THREAD

**Issue by ptanseri** [Aymkdn/assistant-freebox-cloud#58]
Bonjour,

Après avoir effectué les séries de tests "https://github.com/Aymkdn/assistant-freebox-cloud/wiki#8-lassistant-me-r%C3%A9pond-mais-rien-ne-se-passe"

Et tous les résultats sont OK, l'assistant me répond mais pas d'action, quand je crée d'autres applets , IDEM,

Tout fonctionnait bien hier soir :)

Une autre piste ?

Merci de ton aide

**Comment by Aymkdn** [comment]
Si tu as fait tous les tests décrits et que tout est bon, alors non je ne vois pas d'où pourrait venir le problème.... 

Si ça marchait hier et que ça ne fonctionne plus aujourd'hui, c'est soit un problème IFTTT ou Google (dans ce cas attend un peu pour voir si ça remarche), ou une adresse IP qui a changé (ton adresse publique ou locale de ta Freebox). 

Sinon je ne vois pas !

**Comment by ptanseri** [comment]
Ok merci je vais attendre pour voir.. Merci de ta reactivite

**Comment by ptanseri** [comment]
Problème résolu, j'ai  forcé l'ancien IP de la freebox player, du coup je l'ai passé en static.
La validation de l'assistant cloud ne suffit pas.
Bravo pour ton travail :)

**Comment by Aymkdn** [comment]
Ok cool!
