### ISSUE TITLE
Google Actions

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#59]
J'ai commencé à explorer l'utilisation de **Google Actions** qui permet d'ajouter la Freebox comme un objet connecté dans l'application Google Home. J'aurais souhaité utiliser ce système à la place de IFTTT qui est laborieux à configurer....

Malheureusement Google limite énormément les possibilités actuellement... il y a peu [d'actions proposées/documentées](https://github.com/actions-on-google/smart-home-nodejs/issues/253) en rapport avec la TV.

Pour le moment, ce que j'ai réussi à faire : 
  - [x] Ajouter une Freebox dans l'interface Google Home
  - [x] Allumer / éteindre la Freebox
  - [x] Augmenter / baisser le volume / couper le son de la Freebox
  - [x] Passer à la chaine suivante / chaine précédente
  - [x] Mettre sur pause / mettre en lecture

Ce que je n'ai pas réussi à faire : 

  - [ ] Zapper sur une chaine précise... J'y arrive en anglais (si je donne un numéro de chaine), mais impossible de trouver la commande en français (qui n'existe peut-être pas encore ?!)

**Comment by ppicppic** [comment]
intéressant !

**Comment by bmackiwi** [comment]
Bonjour, j'ai suivi les instructions sur "Assistant Cloud" pour allumer la Freebox, et ca marche, mais j'arrive sur le menu de Freebox et pas sur le TV. Il manque donc une étape (appuyer sur ok par ex.)pour arriver à la télé. Aussi quand j'ai essayé de créer un trigger "allume la Freebox et zappe sur $" dans IFTTT, il me répond "This recipe is for number (#) not text ($) ingredients." et je ne peux pas poursuivre.

**Comment by Aymkdn** [comment]
Mise à jour du premier message avec ajout des actions que j'ai réussi à produire via Google Home.

**Comment by Aymkdn** [comment]
En date du 29 mars 2020, on ne peut toujours pas changer de chaine en français :( Si je lui dis « mets la chaine M6 sur Freebox » il va lancer la chaine M6 de Youtube sur mon Android TV…

Par contre en anglais un « go to channel M6 on TV » va bien me mettre M6 sur la Freebox.

Du coup, ça reste en attente jusqu'à ce que Google fasse le nécessaire :(

**Comment by Aymkdn** [comment]
Google vient de lancer officiellement le _trait Channel_ 🎉🎉🎉

Je vais essayer de tester ce week-end…

**Comment by ppicppic** [comment]
Intéressant ! Faut que je reviennes vers toi, j'ai déménagé, du coup changé
d'ip...

Bon courage et bonne journée

**Comment by Aymkdn** [comment]
Ça fonctionne !!!!! 🎉

Maintenant il faut que je fasse des tests plus poussés puis que je mette à jour le site et que je publie / que je sois validé par Google :-)

**Comment by ppicppic** [comment]
Bonne nouvelle !
Bravo
