### ISSUE TITLE
Noms des chaines

### ISSUE THREAD

**Issue by collicalex** [Aymkdn/assistant-freebox-cloud#6]
Bonjour,

Je viens de lire votre commentaire:

>  J'ai rajouté les chaines suivantes : 
>   - `la une` qui zappe sur `TF1`
>   - `BFM` qui zappe sur `BFM TV`
>   - `Polar +` qui zappe sur la 55

_Originally posted by @Aymkdn in https://github.com/Aymkdn/assistant-freebox-cloud/issues/1#issuecomment-472388706_

Est ce que vous créez une action IFTTT par nom de chaine?
En effet, il est possible de récupérer la liste des chaines disponible sur les freeplayers + leur numéro associé. Ensuite il suffit de comparer le nom prononcé avec les éléments de la liste pour retrouver le numéro de la chaine et zapper (une petite normalisation des noms dans la liste et du nom prononcé, ainsi qu'une distance de Levenshtein normalisée; et ca marche à merveille).

Du coup je ne comprends pas comment vous rajoutez une chaine".. soit elles sont toutes prises en compte, soit aucune... non?
Sinon ca serait une bonne idée d'amélioration de votre contrôle de freeplayer dans le "cloud" :)

**Comment by Aymkdn** [comment]
J'ai récupéré toutes les chaînes de Free et leur numéro. J'ai normalisé les noms, mais parfois y'a des loupés que je n'ai pas vu (car y'a beaucoup de chaînes, par exemple j'avais "Polar Plus" au lieu de "Polar +" dans ma base).

Aussi des gens n'utilisent pas le nom complet. Par exemple j'ai rajouté "BFM" en plus du vraie nom (qui est "BFM TV"), ou "la Une" qui n'est pas le vrai nom de TF1.

Et je ne parle pas des chaînes qui ont des caractères/noms farfelues... 

Donc quand on demande une chaîne, le système la compare avec la base pour trouver le numéro associé.

**Comment by collicalex** [comment]
Ok, parfait :)
Je vais tester tout ca du coup =)
