### ISSUE TITLE
Pbm avec Google Home

### ISSUE THREAD

**Issue by dirqf** [Aymkdn/assistant-freebox-cloud#60]
Bonjour,

J'ai installé l'app sur la free cfg quelques commandes tout fonctionnait. J'éteins la box et qd j'ai voulu rallumer ca ne marchait plus. Aucune commande ne fonctionnait. J'ai testé toutes les étapes avant de vous contacter et la box réagit aux test et a l'extinction grâce à l'adresse url .

**Comment by Aymkdn** [comment]
Bonjour,

As-tu suivi toutes les étapes décrites là : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#8-lassistant-me-r%C3%A9pond-mais-rien-ne-se-passe ?

Car je miserais sur l'adresse IP publique qui a changé, ou l'adresse IP du Freebox Player qui a changé.

**Comment by dirqf** [comment]
J'ai tout fait l'ip locale diffère sur whatismyip ca finit par 10 et sur free par 11

**Comment by Aymkdn** [comment]
Sur WhatisMyIP tu ne peux pas voir l'IP locale, mais seulement ton IP Publique. Tu as essayé de relancer l'application du Freestore pour reconfigurer ton compte ?

**Comment by dirqf** [comment]
Oui avec un nouveau code d'activation.

**Comment by Aymkdn** [comment]
Envoie moi un email à aymeric@kodono.info avec l'email utilisé pour ton compte .

Ensuite, reprends chaque étape de https://github.com/Aymkdn/assistant-freebox-cloud/wiki#8-lassistant-me-r%C3%A9pond-mais-rien-ne-se-passe et dis moi le résultat de chacune d'elle.

**Comment by Aymkdn** [comment]
Alors, un gars sur Twitter m'a prévenu que ça remarchait pour lui, et chez moi ça remarche également !
