### ISSUE TITLE
Bonjour et merci j ai un problème assistant cloud 

### ISSUE THREAD

**Issue by duch974** [Aymkdn/assistant-freebox-cloud#61]
Depuis plusieurs jour plus rien ne marche !. J ai supprimé mes applet. Pour ensuite en refaire quelques une pour voir mais rien. Je me suis reconnecter à kono.. Qui m'as reloué. J ai donc eu un nouveau code d activation que j ai essayé sur assistant cloud en supprimant mes données afin de mettre mon nouveau code. Mais j ai une erreur à la fin du processus. (erreur" exist "). A tu une idée je suis perdu. Merci d avant et grand merci pour tout ton travail !!

**Comment by Aymkdn** [comment]
Salut,

Depuis ce matin il y a un problème entre les services de Google et IFTTT. Le problème vient donc d'eux (mais ça ne fonctionne plus que depuis ce matin). Donc même si tu reconfigures ton compte, ça ne fonctionnera pas pour le moment !

Il faut attendre qu'ils corrigent le problème de leur côté.

**Comment by duch974** [comment]
Merci beaucoup pour ta réponse aussi rapide. J aurai du te consulté avant mdrr. Sa fait 2 h que je tourne en carré avec mon problème lol. OK je patiente ! Et je vais reprendre mes télécommandes en attendant. Merci beaucoup !

**Comment by duch974** [comment]
Je ferme le sujet !?

**Comment by Aymkdn** [comment]
Je le fermerai quand je constaterai que ça refonctionne si tu veux :)

Là je suis en train de mettre un message sur le site pour que ce soit visible

**Comment by duch974** [comment]
👍

**Comment by Aymkdn** [comment]
Alors, un gars sur Twitter m'a prévenu que ça remarchait pour lui, et chez moi ça remarche également ! J'attends un peu pour enlever le message sur le site web.

**Comment by duch974** [comment]
Parfait tout remarche me reste plus qu à refaire toute mes commandes. Merci !!
