### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#62]
Bonjour, j'ai suivi les instructions sur "Assistant Cloud" pour allumer la Freebox, et ca marche, mais j'arrive sur le menu de Freebox et pas sur le TV. Il manque donc une étape (appuyer sur ok par ex.)pour arriver à la télé. Aussi quand j'ai essayé de créer un trigger "allume la Freebox et zappe sur $" dans IFTTT, il me répond "This recipe is for number (#) not text ($) ingredients." et je ne peux pas poursuivre.

_Originally posted by @bmackiwi in https://github.com/Aymkdn/assistant-freebox-cloud/issues/59#issuecomment-520356680_

**Comment by Aymkdn** [comment]
Je déplace ta question ici car elle n'a rien à faire dans l'autre threat @bmackiwi

> j'arrive sur le menu de Freebox et pas sur le TV

Oui, c'est normal. `Allume la Freebox` va juste l'allumer. Il faut dire `Allume la TV et zappe sur $` pour que la fonction entre dans le menu TV puis zappe sur la chaine demandée.

Il est possible de modifier l'action "allume la Freebox" en y rajoutant l'action `OK` (donc au lieu de `https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=on` tu auras `https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=power,wait7000,tv`)

> Aussi quand j'ai essayé de créer un trigger "allume la Freebox et zappe sur $" dans IFTTT, il me répond "This recipe is for number (#) not text ($) ingredients." et je ne peux pas poursuivre.

Tu n'as pas lu les instructions correctement. Il est indiqué : **`Cliquez sur la boite qui s'intitule "Say a phrase with a text ingredient"`**, toi tu as cliqué sur l'autre box (qui dit `Say a phrase with a number ingredient`)

**Comment by bmackiwi** [comment]
Merci !! La sequence n'a pas marché, mais en utilisant la version dans le tutoriel et en ajoutant la fin ...(wait7000.tv) il a démarré sur le TV (https://assistant-api.kodono.info/fbx/NzM2ODsjNWQ1MTIzMzhkNjEyMA__/?c=on,wait7000,tv)


________________________________

**Comment by Aymkdn** [comment]
J'ai effacé ton commentaire car tu as donné ton CODE_SECRET dans l'URL.... Ce que tu ne dois pas faire, sinon n'importe qui peut commenter ta Freebox !

Je ferme l'issue puisque c'est réglé.
