### ISSUE TITLE
Remerciement à Aymeric

### ISSUE THREAD

**Issue by rasamy9** [Aymkdn/assistant-freebox-cloud#63]
Bonjour,

Je tiens absolument à vous dire merci. Vous m'avez donné un sens à mon achat de mon Google Home il y a 1 an. (J'ai fait le don ;-) )

Penseriez-vous à faire d'autres tutos sur le google home et le cloud ? Car c'est vraiment génial. C'est le seul tutorial à la portée des analphabètes :-D.

Encore merci. Bien à vous

**Comment by rasamy9** [comment]
Aymkdn !!! ;-)

**Comment by Aymkdn** [comment]
Héhé merci :-)

Pas d'autres vidéos de prévu. Par contre je travaille sur un moyen de pouvoir contrôler la Freebox directement via Google Home, et donc sans passer par IFTTT, pour simplifier la configuration. À voir ces prochains mois selon le temps que j'arrive à y consacrer :-)
