### ISSUE TITLE
url

### ISSUE THREAD

**Issue by 19madpo** [Aymkdn/assistant-freebox-cloud#64]
comment envoyer une url un lien video

**Comment by Aymkdn** [comment]
Euh ... ?! `assistant-freebox-cloud` sert à piloter la Freebox **par la voix**, pour changer de chaine ou modifier le volume .... Ta question n'a donc pas de sens....

**Comment by 19madpo** [comment]
peut on envoyer une URL via une requête ifttt du genre https://assistant-api.kodono.info/fbx/xxxxxxxxxxxxxxxxxxxx/?c=URL

**Comment by Aymkdn** [comment]
Non, on ne peut pas...

**Comment by 19madpo** [comment]
merci
