### ISSUE TITLE
Bug sur les fonctions "allume la Freebox et zappe sur $" et "mets la télé"

### ISSUE THREAD

**Issue by Benohit** [Aymkdn/assistant-freebox-cloud#65]
Copie d'un message adressé sur : https://www.universfreebox.com/article/51344/Le-saviez-vous-vous-pouvez-piloter-votre-Freebox-Revolution-avec-Google-Assistant

Bonjour,

@Aymeric, je viens de l'installer et de le tester.

C'est sûr que c'est un peu fastidieux de devoir entrer toutes les commandes et il faudrait prévoir des variantes de phrase pour une même commande (car dans la vraie vie on n'utilise pas toujours les mêmes mots) mais merci pour le développement qui m'a permis de découvrir au passage le site IFTTT. 

Un petit retour utilisateur : tout fonctionne sauf : 

-If You say "allume la Freebox et zappe sur $", then Make a web request => Cela allume juste la Freebox mais ne zappe pas sur la chaîne. Et chose bizarre le menu va sur "éjecter le disque"

- If You say "mets la télé", then Make a web request => Elle sert à quoi exactement cette commande ? Quand la box est déjà allumée c'est censé aller sur la TV ? 

- La commande "zappe sur $" fonctionne uniquement quand on est déjà dans l'espace télé. Alors qu'effectivement le but premier c'est de pouvoir mettre une chaîne de télé à distance.

Merci,

Ben

PS : j'ai bien sûr vérifié les lignes de code si j'avais fait le bon copier/coller et j'ai bien mis "Say a phrase with a text ingredient" pour ces commandes.

**Comment by Benohit** [comment]
Je pense que je vais déjà tester la solution décrite ici : https://github.com/Aymkdn/assistant-freebox-cloud/issues/62#issuecomment-520364130
"Il est possible de modifier l'action "allume la Freebox" en y rajoutant l'action OK (donc au lieu de https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=on tu auras https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=power,wait7000,tv)"

Mais est ce que ça ne devrait pas fonctionner sans cette modif ?

**Comment by Benohit** [comment]
Bon et bien après avoir copier/coller la ligne de code https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=power,wait7000,tv et en mettant mon code de secret dedans, toujours le même résultat : ça allume la télé mais ça ne va pas sur l'espace  Freebox TV directement.

**Comment by Aymkdn** [comment]
Peut-être que ta Freebox est trop lente ou bien c'est ta connexion ? Et donc des commandes se perdent...

C'est bien une Freebox Révolution que tu utilises?

Sur https://assistant.kodono.info/freebox tu trouveras une section pour créer tes propres commandes. Tu peux essayer de voir si en mettant des délais supplémentaires entre chaque appui télécommande tu arrives à l'endroit souhaité... Tu vois ce que je veux dire ?

**Comment by Aymkdn** [comment]
(Maintenant que je suis sur l'ordi je peux mieux te répondre)

Essaie une commande du genre : https://assistant-api.kodono.info/fbx/TON_CODE_SECRET/?c=power,wait10000,home,wait4000,red,wait2000,ok

Cela va allumer la Freebox, attendre 10s (au lieu de 7), puis appuyer sur la touche `rouge`, attendre 2s puis la touche `OK`.
Vois si ta Freebox réagit bien ?

**Comment by Benohit** [comment]
Bonjour,

C'est bien une Révolution. J'ai la Fibre et mes box sont reliées en ethernet. 
Je vais essayer avec la nouvelle ligne de commande. 

Bonne journée,

Ben

**Comment by Benohit** [comment]
Et ok ça marche. 
Dans l'ordre :
1. J'allume la box
2. La box va sans que je ne sache pourquoi sur "éjecter le disque"
3. grâce au "bouton rouge" (fonction que je ne connaissais pas) cela retourne sur la TV
4. bouton ok et TV
Je vais donc à partir de cette commande tenter la même chose avec la chaîne de TV en plus.
Mais le premier but est atteint : allumer la télé sur une chaîne. Et ensuite le zapping vocal fonctionne. 
Merci pour le retour et le développement.
Ben

**Comment by Aymkdn** [comment]
Il est donc possible que ta Freebox soit "lente" et donc mette trop de temps à répondre à certaines commandes !

Comme tu peux le voir sur [la page des commandes personnalisée](https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-personnalis%C3%A9es), le raccourci  `tv` envoie en fait la séquence `home`, `wait2000`, `red`, `ok`, `wait4000`.

Je t'ai donc fait rajouter quelques `wait` en plus ;-)
