### ISSUE TITLE
freebox

### ISSUE THREAD

**Issue by ROGALINSKI** [Aymkdn/assistant-freebox-cloud#66]
assistant cloud
la commande allume la freebox est transformee en allume la freebox player mini et il ne m'allume le freebox player. je possede 2 player.

**Comment by ROGALINSKI** [comment]
player et non joueur
excuse
marci pour la reponse

**Comment by Aymkdn** [comment]
Tu as deux Freebox Player, donc tu as suivi ce passage de la documentation https://github.com/Aymkdn/assistant-freebox-cloud/wiki#2-puis-je-utiliser-le-syst%C3%A8me-avec-plusieurs-freebox-player- ?

Si je comprends, tu as donc créé 2 commandes vocales : 
1) `Allume la Freebox` qui va allumer la première Freebox
2) `Allume la Freebox Player` qui va allumer la deuxième Freebox

Mais la deuxième Freebox ne s'allume pas, tandis que ça marche avec la première ?

Désolé mais ta question n'est pas claire du tout et totalement imprécise... Du coup j'essaie de comprendre quel est ton problème précisément...

**Comment by ROGALINSKI** [comment]
Bonjour,

Excuse moi je n'ai pas été très clair, effectivement j'ai  2 freebox. Mais
j'ai fais des copier coller de tes commandes pour la freebox player et
lorsque je fais ok google allume la freebox  google assistant répond
j'allume la freebox player mini
J'espère avoir été clair cette fois
Merci
Patrick

**Comment by Aymkdn** [comment]
OK, donc pour le moment tu ne cherches qu'à allumer la première Freebox si je comprends bien.

Si Google te répond `j'allume la Freebox Player Mini` c'est probablement parce que tu as écrit ça dans ton applet IFTTT.
Va sur https://ifttt.com/my_applets et cherche l'applet qui te sert à allumer la Freebox. Clique dessus puis clique sur **Settings**. Tu devrais voir ça : 
![Capture](https://user-images.githubusercontent.com/946315/63591841-455ab800-c5b0-11e9-9444-d34fd3293ef7.JPG)

Est-ce le cas ?

(Je t'invite à répondre directement sur https://github.com/Aymkdn/assistant-freebox-cloud/issues/66 plutôt que de répondre à l'email automatique de Github)

**Comment by ROGALINSKI** [comment]
C'est ça l'apletest st bon

**Comment by Aymkdn** [comment]
Donc si ton Google Home te répond `j'allume la Freebox Player Mini`, c'est qu'il y a une autre commande vocale qui prend la priorité ici....

Aurais-tu nommé un de tes appareils chez toi avec le nom **"Freebox Player Mini"** dans l'application Google Home ?

**Comment by ROGALINSKI** [comment]
Non,

Je n'ai pa google home

**Comment by Aymkdn** [comment]
Ah ok, donc tu parles à ton téléphone via Google Assistant...

As-tu créé d'autres applets dans IFTTT et as-tu essayé de les lancer ? Car peut-être que ton compte IFTTT n'est pas correctement relié à ton compte Google, donc c'est pour voir si Google Assistant reconnait d'autres commandes vocales que tu as mises dans IFTTT, ou si aucune ne fonctionne.

**Comment by ROGALINSKI** [comment]
Aucun applet ne fonctionne en plus sur Google assistant zappe s'écrit zap

**Comment by Aymkdn** [comment]
Tu as dû merder dans un des applets que tu as créé.... Reprends tout un par un.

**Comment by ROGALINSKI** [comment]
Merci,
J'abandonné car je pense merder dans les URL

**Comment by ROGALINSKI** [comment]
Ok merci 
J'abandonné j'ai  du merder dans la fin des URL

**Comment by Aymkdn** [comment]
Oki

**Comment by ROGALINSKI** [comment]
Bonjour,
J'ai supprime tous mes applets et recrée l'applet allume la freebox google assistant me repond j'allume la freebox player mini comment puis je creer une URL allume la freebox du salon  car je ne vais me servir des commandes vocales de la freebox et non du mini.
Merci

**Comment by Aymkdn** [comment]
Essaie de supprimer l'applet IFTTT que tu viens de créer et redis "allume la Freebox" pour voir ce qu'il te répond.

**Comment by ROGALINSKI** [comment]
Bonjour,
J'ai supprimé l'applet IFTT "allume la freebox" et il me répond a nouveau "j'allume la freebox player mini.

**Comment by Aymkdn** [comment]
Donc le problème est extérieur à tout ça...

Es-tu sûr que tu utilises sur IFTTT le même compte Google que sur ton téléphone ?

**Comment by ROGALINSKI** [comment]
oui.

**Comment by Aymkdn** [comment]
Visiblement non, sinon c'est l'applet IFTTT qui prendrait le dessus... Ou alors tu as créé deux comptes IFTTT.... Bref, je suis désolé mais tu as une merde quelque part, non lié à mon service, et je ne peux donc malheureusement pas t'aider plus que ça....

**Comment by ROGALINSKI** [comment]
Ok

Merci pour ton aide, je vais continuer a chercher
Bon dimanche

**Comment by ROGALINSKI** [comment]
J'ai enfin compris je commande la mini 4k avec google assistant avec ce compte gmail  mais je n'ai pas créer de compte IFTT à ce moment là

**Comment by Aymkdn** [comment]
Tu as une Freebox Révolution et une Freebox 4k ?

**Comment by ROGALINSKI** [comment]
OUI

**Comment by Aymkdn** [comment]
Alors, créé une applet qui se déclenche sur "allume le système Kodono" puis vois si Google reconnaît la commande vocale. 

S'il ne reconnaît pas la commande vocale, essaie https://github.com/Aymkdn/assistant-freebox-cloud/wiki#5-mon-google-home-ne-r%C3%A9pond-%C3%A0-aucune-commande-
