### ISSUE TITLE
demande info chaine suivante et chaine precedente

### ISSUE THREAD

**Issue by EricGLT** [Aymkdn/assistant-freebox-cloud#67]
Demande info sur 
Ajout de la prise en charge des phrases clés suivantes :

    zappe sur la chaine suivante
    zappe sur la chaine précédente
je n'arrive pas à trouver les commandes pour valider ces 2 données.
j'ai essayé a la fin c=zappe+1 mais cela fonctionne pas
(https://assistant-api.kodono.info/fbx/NzgyMTsjNWQ1ZmYxNGY5YTc3Zg__/?c=zappe {{TextField}})
avez vous la solution ?
un grand merci pour votre réponse ainsi que votre travail

**Comment by EricGLT** [comment]
je viens de trouver ...
https://assistant-api.kodono.info/fbx/NzgyMTsjNWQ1ZmYxNGY5YTc3Zg__/?c=programUp

Merci ;-)

**Comment by EricGLT** [comment]
je viens de trouver :-))

**Comment by Aymkdn** [comment]
Cool 😁

**Comment by EricGLT** [comment]
un tres grand merci encore pour ton travail ! BRAVO !!!
