### ISSUE TITLE
Alias radio Assistant cloud pour Freebox

### ISSUE THREAD

**Issue by hervebdx** [Aymkdn/assistant-freebox-cloud#68]
Bonjour
Avez vous prévu des alias pour les radios?
Merci par avance

**Comment by Aymkdn** [comment]
Non pas pour le moment. Ça viendra peut-être mais c'est pas la priorité pour le moment !

**Comment by hervebdx** [comment]
Merci pour cette réponse rapide


Le 23 août 2019 19:34, Aymeric <notifications@github.com> a écrit :

Non pas pour le moment. Ça viendra peut-être mais c'est pas la priorité pour le moment !
