### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by demon57730** [Aymkdn/assistant-freebox-cloud#69]
bonjour voila je t'ecrit que tu as fait une erreur ou quelque chose ne fonctionne pas

pour la commande 
allume la Freebox et zappe sur $
tu as mis 
https://assistant-api.kodono.info/fbx/codesecret/?c=power,wait7000,tv,zappe {{TextField}}
sauf que la commande tv ne fonctionne pas donc ont reste comme si on avais juste allumé la freebox

voila ce que j'ai mis

https://assistant-api.kodono.info/fbx/codesecret/?c=power,wait7000,home,wait1000,ok,wait3000,zappe {{TextField}}

comme tu vois j'ai ajouté le home a la place du tv ( pour lui dire d'allez sur freebox tv au cas ou il est pas de base) puis j'ai mis 1 sec et après appuis sur ok après 3 sec ( logo freebox) puis la commande zappe

**Comment by Aymkdn** [comment]
Bonjour.

Attention de ne pas mettre ton code secret car n'importe qui peut ensuite piloter ta Freebox... 

Ensuite, il n'y a pas d'erreur. Cela fonctionne pour près de 8000 personnes. Cependant il y a deux possibilités qui pourraient expliquer que ça ne marche pas pour toi :
1) la liaison entre mon serveur et ta Freebox est trop mauvaise donnant ce problème (les commandes sont bien envoyées, mais n'arrivent pas à destination)
2) ta Freebox est plus lente que la moyenne et donc des temps de pause sont nécessaires entre chaque commande reçue. 

J'ai aussi récemment remarqué que parfois toutes les commandes n'étaient pas reçues. Je n'ai pas eu le temps de pousser les tests mais c'est peut être dû à ça également (trop de monde qui utilisent mon serveur ? Problème de réseau entre ovh et Free, autre ?) 

Bref, tout ça pour dire qu'il n'y a pas de bug et que `tv` fonctionne comme il le devrait.
