### ISSUE TITLE
probleme de commandes

### ISSUE THREAD

**Issue by legras44** [Aymkdn/assistant-freebox-cloud#71]
bonjour,
la commande "allume la freebox" fonctionne parfaitement
la commande "eteins la freebox ":ne fonctionne pas
google home me répond "jéteins le freebox", la freebox ne s'éteint pas
si je rentre directement l'url "off", la freebox s'éteint
les deux scripts ont l'air identiques ....
que faire?
d'avance merci et bravo pour votre tuto et votre travail !!!

**Comment by Aymkdn** [comment]
Bien étrange cela. J'imagine que tu as fait plusieurs tests pour voir si ce n'était pas un problème temporaire ?

Est-ce que tu peux me donner un bout de ton email afin que je puisse trouver ton compte et regarder si je trouve quelque chose ?

**Comment by legras44** [comment]
bien sûr
legras.patrick@gmail.com
mais comme j ai vu sur un post que pour l instant la commande on/off est en bistable je vais modifier la commande « allume la freebox « en »commandes le freebox « 
patrick

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Je n'ai pas vraiment compris ta réponse...

Mais sache que "on", "off" ou "power" sont la même chose. Le système n'étant pas capable de savoir si la Freebox est allumée, il va, dans tous les cas, envoyer la même commande "power" au Player. S'il est éteint, il va s'allumer, et s'il est allumé, il va s'éteindre.

**Comment by legras44** [comment]
je me suis mal exprimé!! au lieu d avoir deux commandes allumer et éteindre, je met une seule commande que j appelle « commande freebox «  c est plus clair pour toi !

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
OK. Ce qui n'a pas de sens, puisque comme je l'ai dit, peu importe "on" ou "off", cela fait la même chose. À mon avis, c'est ton applet pour éteindre la Freebox qui est mauvaise. Tu devrais essayer de la supprimer et de la recréer.

Bref, t'as trouvé une solution et si ça te convient, moi ça me va ! Donc je ferme cet "issue" :-)
