### ISSUE TITLE
Aucune communication entre Google home et freebox delta

### ISSUE THREAD

**Issue by stef49360** [Aymkdn/assistant-freebox-cloud#74]
Bonjour après avoir passé tout les tests et contrôles, j' ai un problème. Même en local la commande allumé/éteindre la freebox, elle ne réagit pas. J' ai vérifié le numéro de télécommande 10 fois et l'adresse local autant.
Merci de votre aide.

**Comment by Aymkdn** [comment]
Bonjour,

> Même en local la commande allumé/éteindre la freebox, elle ne réagit pas

Quand tu dis "en local", tu veux dire que tu as suivi ça https://github.com/Aymkdn/assistant-freebox-cloud/wiki#test-en-local mais que rien ne se passe ?
Quand tu ouvres cette page locale, est-ce que tu as une page vide / blanche ? Une page d'erreur ? Quelque chose qui s'affiche ?

**Comment by stef49360** [comment]
J'ai essayé avec
http://192.168.0.33/pub/remote_control?key=power&code=12345678 en
remplaçant l'adresse par la mienne et le numéro par celui de ma
télécommande.

**Comment by stef49360** [comment]
Oui c'est bien ça.

**Comment by stef49360** [comment]
J'ai un message d'erreur.

**Comment by stef49360** [comment]
Le message d'erreur s'ouvre sur une page freebox et me dit ressource non
trouvée.

Merci.

**Comment by Aymkdn** [comment]
Peux-tu répondre sur https://github.com/Aymkdn/assistant-freebox-cloud/issues/74 plutôt que par email ? Ce sera plus lisible pour moi :-)

> Le message d'erreur s'ouvre sur une page freebox et me dit ressource non
trouvée.

Peux-tu faire une capture d'écran et l'ajouter ici ?

**Comment by stef49360** [comment]
Je fais ça en fin d'après-midi car je suis au boulot.
En tout cas merci de traiter ma demande.
