### ISSUE TITLE
2 appels de allume la freebox, eteins la freebox

### ISSUE THREAD

**Issue by Herve-Epp** [Aymkdn/assistant-freebox-cloud#75]
Bonjour, 
J'ai constaté que si on appelle 2 fois l'applet allume la freebox (ou eteins la freebox), en fait la freebox s'allume et puis s'éteint la 2ème fois (ou s'éteins puis s'allume).

Y-a-t-il un moyen d'éviter cela?

Merci

**Comment by Aymkdn** [comment]
Non, pour le moment c'est la même commande qui allume et éteint la Freebox (cela simule l'appuie sur "Power" de la télécommande). Il n'existe (pour le moment) aucun moyen d'éviter ça.
