### ISSUE TITLE
Assistant Cloud et Freebox Delta

### ISSUE THREAD

**Issue by LudoFlorez** [Aymkdn/assistant-freebox-cloud#76]
Bonjour,
Ma Freebox Delta reste totalement stoïque à toute commande.
J'ai bien vérifié tous les paramètres, je n'ai pas d'erreurs sur ifttt, mon Google Home me dis bien "J'allume la freebox" tout à l'air de bien fonctionner... J'arrive à allumer / éteindre via la commande dans mon browser...
Je ne sais plus quoi faire...
Merci d'avance pour votre diagnostique...

**Comment by Aymkdn** [comment]
Mmhhh... As-tu une configuration réseau particulière ? Par contre un routeur supplémentaire ? Ou quelque chose du genre ?

**Comment by Aymkdn** [comment]
Ah, c'est peut être ça qui cause le problème ? Comment le Freebox player est-il relié à la Freebox Serveur ? Via le Google WiFi ?

**Comment by LudoFlorez** [comment]
Le player est connecté au server via les freeplugs... J'ai essayé en déconnectant les Google wifi, ça ne change rien...

**Comment by LudoFlorez** [comment]
![Connectivité](https://user-images.githubusercontent.com/56084784/66111656-96a39180-e5c9-11e9-8d7e-2e3434131e82.png)
![Redirections](https://user-images.githubusercontent.com/56084784/66111657-96a39180-e5c9-11e9-8f6d-078233bd502e.png)

**Comment by LudoFlorez** [comment]
J'ai modifié l'adresse de destination de la redirection vers mon ordi afin de faire une petite capture du trafic avec Wireshark, il ne se passe rien sur le port configuré... Le server bloquerait-il ce trafic ?

**Comment by Aymkdn** [comment]
Peut-être que ton IP est partagée avec d'autres Freenautes et que seule une *range* de ports est disponible pour toi, et que 57556 n'en fait pas parti ? Normalement ça ne devrait pas arriver... mais bon...

Deux choses que tu peux faire : 

1. Modifie le port de la redirection via FreeboxOS : si tu entres un mauvais port d'entrée (qui n'est pas dans ta range autorisée) il devrait te le souligner en rouge... pour voir si le port est bon ou non
2. Va dans ton interface abonnée : https://subscribe.free.fr/login/ puis dans "**Ma Freebox**" puis "**Demander une adresse IP fixe V4 full-stack**" et fait une demande... Cela devrait te donner une IP rien qu'à toi, et une fois fait, tu pourras relancer l'application du Freestore qui devrait mettre à jour ta nouvelle IP sur le serveur

En tout cas, les requêtes partent de mon serveur vers chez toi !
