### ISSUE TITLE
Conflit Google Home avec commande monter le son 

### ISSUE THREAD

**Issue by skyrail01** [Aymkdn/assistant-freebox-cloud#77]
Bonjour,
Je prononce l'expression "montes le son de la Freebox" devant Google Home pour augmenter le son de la freebox. Mais celui-ci essaie de monter le son de l'enceinte, pas celui de la Freebox.
Et peu importe que je mette le mot Freebox en premier après Ok Google.
Comment prendre en compte cette commande?
Merci.

**Comment by Aymkdn** [comment]
Vérifie que tu as bien créé l'applet **"Monte le son de la Freebox"** sur IFTTT. Une fois créée, cela prendra le dessus.
