### ISSUE TITLE
Commande "Mets la télé" laisse la freebox sur la page d'acceuil

### ISSUE THREAD

**Issue by skyrail01** [Aymkdn/assistant-freebox-cloud#78]
Bonjour,
Quand on demande "mets la télé" on arrive sur la page d'accueil et il faut cliquer sur FreeboxTV (sélectionné par défaut) pour afficher les chaînes.
Malgré tout, la commande "zappes sur $" change bien de chaîne, mais celle-ci ne s'affiche que lorsqu'on valide FreeboxTV.
Est-ce que c'est un bug?

**Comment by Aymkdn** [comment]
La commande `Mets la télé` permet, normalement, d'aller dans le menu "TV" de la Freebox lorsque celle-ci est **déjà allumée**.

Il ne devrait pas y avoir de bug. Cependant, les commandes transitant depuis Internet vers chez toi, il n'est pas impossible que certaines commandes "se perdent" (ou arrivent trop tôt) en chemin interrompant la suite des commandes.
