### ISSUE TITLE
Ok freebox/google, mets de la musique.

### ISSUE THREAD

**Issue by agenceblink** [Aymkdn/assistant-freebox-cloud#79]
Ok Freebox, mets de la musique lance Spotify sur la Devialet. J'aimerai configurer une routine Google assistant pour qu'il puisse reconnaître Ok Google met de la musique et réaliser la même action... 
Je ne suis pas encore sur du processus ni même si c'est possible.. 

Merci!

**Comment by Aymkdn** [comment]
Si cela est possible, ça ne sera pas avec ce module, qui ne sert pas à ça...
