### ISSUE TITLE
Code télécommande pour assistant freebox

### ISSUE THREAD

**Issue by nesta59** [Aymkdn/assistant-freebox-cloud#8]
Bonjour 
Il faut rentrer un code télécommande à 8 chiffres mais moi je n en ai que 7 
Y as t il une solution à mon problème ?
Merci d avance

**Comment by Aymkdn** [comment]
Essaie avec un 0 au début.

Je corrigerai ça à mon retour de week-end !

**Comment by nesta59** [comment]
Bonsoir
J ai fait l essai avec un 0 au début mais cela ne fonctionne pas
Si il était possible de faire quelque chose ça serai vraiment bien car j
aimerai vraiment pouvoir utiliser ce plugin

Merci d avance
Cordialement

**Comment by Aymkdn** [comment]
Je m'en occupe demain !

**Comment by Aymkdn** [comment]
Je viens de modifier et cela devrait maintenant prendre un code à 7 chiffres !

**Comment by nesta59** [comment]
Bonjour
Ok merci je vois ça en rentrant du boulot si ça fonctionne
En tout cas merci pour la réactivité
Bonne journée
Cordialement

**Comment by nesta59** [comment]
Merci encore
J ai tout paramétrer et ça fonctionne nickel
Bravo pour ton boulot 🙏👏🏼
