### ISSUE TITLE
Freebox Delta / pas de réponse 

### ISSUE THREAD

**Issue by djerem5** [Aymkdn/assistant-freebox-cloud#80]
Bonjour,

Je me permets de vous écrire suite à des difficultés que je rencontre pour le paramétrage de la Freebox Delta. J'ai lu entièrement vos préconisations, j'ai tout réglé plusieurs fois pour être sûr de ne pas me tromper, mais rien n'y fait.  Google assistant me répond bien ce qu'il faut, mais aucunes actions ne se passent... j'ai fais les tests avec tout votre tuto et le seul qui fonctionne, c'est le lien qui permet d'éteindre ou d'allumer la free via le navigateur.

Pourriez- vous m'indiquer quelques pistes pour débloquer cela.

Je vous remercie. Cordialement. Jérémy

**Comment by Aymkdn** [comment]
> j'ai fais les tests avec tout votre tuto et le seul qui fonctionne, c'est le lien qui permet d'éteindre ou d'allumer la free via le navigateur.

Il me faut plus d'informations.... 

Quand tu donnes une commande à ton Google, il te répond quoi ? Genre "allume la Freebox"?

S'il dit qu'il ne comprend pas, c'est que le problème vient de la liaison avec IFTTT. 

S'il te répond, alors qu'indique cette étape https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ifttt ?

Si l'action est bien exécutée par IFTTT, alors qu'elle est la configuration de ton réseau ? Qu'as-tu dans Freebox OS ? As-tu du matériel particulier sur ton réseau comme ton propre routeur ?

Je n'ai pas assez d'éléments pour pouvoir t'aider...

**Comment by djerem5** [comment]
Merci pour votre réponse. En effet quand je donne l'ordre a Google il me réponds, j'allume la Freebox ou j'éteins la Freebox...  Dans la liste de gestion des ports de redirection, il y a bien le player actif avec tous les éléments qui correspondent avec mon compte sur l'assistant. Il n'y a pas d'erreur avec ifttt et j'ai refait les étapes une par une pour être Sûr. Mes périphériques réseaux sont : caméra Arlo avec un routeur relié au server, un smart IR qui permet de contrôler la clim. Google home mini et chromecast et mon téléphone. Je viens de tout revérifier, mais ça ne veut pas. A savoir que je viens juste d'avoir la Delta et je n'ai pas encore mis de DD à l'intérieur.

**Comment by Aymkdn** [comment]
> routeur relié au server

Quand tu dis "routeur", c'est juste un appareil qui permet à la caméra de se connecter au Wifi ? Ou alors le routeur en question a un rôle dans ton réseau ?

Essaie de voir la discussion que j'ai eu avec un autre utilisateur (qui ne m'a jamais répondu) : https://github.com/Aymkdn/assistant-freebox-cloud/issues/76 ... si ça peut te donner des pistes.

N'hésite pas à fournir des captures d'écran et des explications approfondies.

**Comment by djerem5** [comment]
Oui c'est "routeur NETGEAR" qui fait le lien avec les caméras pour wifi. Il n'a pas de rôle dans le réseau. Pour te dire j'ai réinitialisé la Freebox avec les paramètres d'usine sans rien re régler. Et j'ai refait la configuration. Oui j'avais déjà lu la discussion. Je vais continuer de chercher ce qui peut causer ce problème. Je reviens vers toi. Merci beaucoup en tous cas.

**Comment by djerem5** [comment]
Enfin ! J'ai réussi 👍 dans un premier temps, je tenais à te remercier pour ta réactivité. Voici la manip : 
1: remise à zéro de la Freebox Delta ( paramètres d'usine)
2: Si déjà essayé de configurer avec Assistant Cloud sans succès, Fermer le compte.
3 : Aller dans Freebox Os et supprimer les accès  dans la gestion des accès.
4: Dans Freebox Os, supprimer La redirection dans la gestion des ports.
5: Dans Freebox Os DHCP, supprimer les baux statiques si déjà configuré avec Assistant Cloud. Si pas configuré, supprimer le périphérique Freebox Player, puis rebooter la free.
6 : Toutes ces étapes réalisées, il y a une chose essentielle à avoir. Il s'agit d'un disque dur à insérer dans la Freebox. Lors de la migration, ou de l'abonnement, Free propose l'achat d'une disque dur. Pas mal de personne ne le prenne pas. Du coup il en en faut absolument un (2,5).
7 installer le disque dur dans la Freebox Serveur.
8: Dans Freebox Os, se rendre dans le menu partage de fichier / disque. 
9 Formater le disque dur ( récupérer les données avant s'il y en a ) et l'activer dans le menu du bas.
10: redémarrer le Free Server et Player.
11: Suivre les étapes une par une du Tuto d'Aymerick et respecter l'ordre. ( Bien vérifier que le compte Google soit identique à IFTTT)

12 : après une nuit de sommeil de deux heures à cogiter, je vais enfin pouvoir configurer les commandes. 

Merci beaucoup.

**Comment by Aymkdn** [comment]
Ah cool ! Bizarre qu'il faille un disque dur pour que ça fonctionne 🤔 Mais au moins je pourrai suggérer ça si d'autres ont le problème.

Merci d'avoir pris le temps d'avoir donné la solution. Les gens qui le font sont rares malheureusement !
