### ISSUE TITLE
Paramétrage

### ISSUE THREAD

**Issue by Waldo80** [Aymkdn/assistant-freebox-cloud#81]
Bonjour
Je suis un nouvel utilisateur
Je viens de mettre en place le contrôle vocal avec google assistant sur ma Freebox révolution 
Tout se passe correctement. J'allume, j'éteins, j'augmente ou baisse le volume etc......
Je rencontre un problème pour effectuer le changement des chaines.
Pouvez-vous me dire ce que l'on doit entrer derrière cette commande: zappe sur $ ?
Comment dois-je renseigner la chaîne?
Pouvez-vous me donner un exemple complet

Cordialement

**Comment by Aymkdn** [comment]
Il suffit de cliquer sur le bouton COPIER du tutoriel, puis de coller le résultat dans la zone de IFTTT. Sinon, si tu souhaites le faire manuellement, après le `?zappe` tu mets un espace, puis tu cliques sur "add ingredient" pour ajouter `{TextField}`.

Au final, ton lien resemblera à ça dans IFTTT pour l'applet `zappe sur` : 
![Capture](https://user-images.githubusercontent.com/946315/67688724-91541f80-f99a-11e9-9010-fd105484c1cc.JPG)

Dis moi si tu as besoin de plus de détails (et sur quelle partie exactement). Et n'hésite pas à joindre des copies d'écran de ton applet (en cachant/modifiant l'URL afin que tu ne dévoiles pas ton code secret, comme je l'ai fait ici en mettant un faux code dans l'URL)

**Comment by Waldo80** [comment]
Merci pour ta réponse Aymeric

Voici un exemple pour la chaine TF1
Je fais un copier coller des boites de dialogues et voilà le message

   - Cette recette concerne le nombre (#) et non le texte ($) des
   ingrédients.

   Entrez un # où vous dites l'ingrédient numéro
   - zappe sur $ TF1
   - Cette recette concerne le nombre (#) et non le texte ($) des
   ingrédients.
   - Je zappe $ TF1

Cordialement.

Di Giulio orlando

**Comment by Aymkdn** [comment]
L'applet est de type "Say a phrase with a text ingredient" (et non pas "number and text"), et il ne faut pas indiquer une chaine (genre "TF1" ou autre)... Tout est géré automatiquement.

J'attire ton attention sur ce que dit le tutoriel : 
![Capture](https://user-images.githubusercontent.com/946315/67693365-db8ccf00-f9a1-11e9-8d24-0d252a7ef1ad.JPG)

Ensuite, comme indiqué dans le tutoriel, ton applet va ressembler à ça : 
![Capture](https://user-images.githubusercontent.com/946315/67693551-2c042c80-f9a2-11e9-893c-4ddf62f29c19.JPG)

**Comment by Waldo80** [comment]
Aymeric
Un grand merci a toi tout fonctionne parfaitement.
Je te mets 5 étoiles ✴✴✴✴✴
Cordialement.

Di Giulio orlando

**Comment by Aymkdn** [comment]
Cool! 😊
