### ISSUE TITLE
ne fonctionne plus

### ISSUE THREAD

**Issue by jcb52200** [Aymkdn/assistant-freebox-cloud#82]
bjr,
j'ai installé assistant cloud sur ma révolution la semaine dernière, cela fonctionnait super bien et je vous en remercie, mais j'ai été obliger de reconfigurer mon wifi et depuis cela ne fonctionne plus.

j'ai regarder les FAQ et essayer mais rien ne fonctionne, ma commande avec google home fonctionne nikel, mais assistant cloud sur la box ne fonctionne plus et m'affiche "erreur inval" au moment de la configuration …

pouvez vous m'aider s'il vous plait.

**Comment by Aymkdn** [comment]
Regarde ce qui est expliqué là https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player

**Comment by jcb52200** [comment]
oui merci, déjà fait et ca ne change rien

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Aymkdn** [comment]
Va sur https://github.com/Aymkdn/assistant-freebox-cloud/issues/82 puis partage des captures d'écran de ta gestion des ports, ainsi qu'un maximum de détails...

Ne connaissant pas ta configuration, les machines sur ton réseau, leurs IP, le changement que tu as fait, il m'est difficile de t'aider.

**Comment by jcb52200** [comment]
oui bien sur je comprend très bien et te remercie

**Comment by jcb52200** [comment]
![Annotation 2019-10-29 134946](https://user-images.githubusercontent.com/57138045/67768534-0aaf4900-fa53-11e9-95b3-c53f60553b99.png)

**Comment by jcb52200** [comment]
![75233517_605762616629427_5591272143435333632_n](https://user-images.githubusercontent.com/57138045/67768970-e9029180-fa53-11e9-9a89-d0ede2378335.jpg)

**Comment by jcb52200** [comment]
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Aymkdn** [comment]
Merci d'utiliser la page https://github.com/Aymkdn/assistant-freebox-cloud/issues/82 pour commenter, et de ne pas répondre par email

**Comment by jcb52200** [comment]
![Annotation 2019-10-29 134946](https://user-images.githubusercontent.com/57138045/67787749-625cad00-fa71-11e9-8634-c4fdaf32e2ef.png)
![75233517_605762616629427_5591272143435333632_n](https://user-images.githubusercontent.com/57138045/67787779-6dafd880-fa71-11e9-9177-89eb2bcbdf27.jpg)

**Comment by jcb52200** [comment]
ok c'est fait mais ca ne fonctionne tjrs pas, je n'ai pas la meme IP source que toi, je dois la changer aussi ?

pour le message d'erreur sur la box, je pense avoir trouvé car derriere la fenetre d'erreur je vois le numero de port et il change a chaque fois

**Comment by Aymkdn** [comment]
Tout est expliqué là : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox-

**Comment by jcb52200** [comment]
ok merci, j'ai changé et je vines de t'envoyer le mail comme demandé

**Comment by Aymkdn** [comment]
Tu n'as pas besoin de m'envoyer d'email. Tes informations sur Kodono n'ont pas changé. Tant que tu as laissé **15990** comme port, ça devrait déjà fonctionner.

**Comment by jcb52200** [comment]
ouiiiiii merci tout plein et je vais faire la pub pour vous !!!

vous n'avez pas trouvez comment faire avec alexa ?

**Comment by Aymkdn** [comment]
Pour Alexa, ça arrive très bientôt. J'ai commencé à faire une nouvelle version du site, mais ça va me demander une bonne centaine d'heures de travail encore...

**Comment by jcb52200** [comment]
ok, bon courage et merci pour tout ...
bonne soirée
