### ISSUE TITLE
IP compte assistant Cloud

### ISSUE THREAD

**Issue by triclic** [Aymkdn/assistant-freebox-cloud#83]
Salut,
je suis passé en fibre et j'ai donc changer d'adresse IP.
comment faire pour la changer dans mon compte  Assistant Cloud ?
Dois je supprimer le compte et en recréer une nouveau ?
Merci de votre aide 
Cdt

**Comment by Aymkdn** [comment]
Envoie moi ta nouvelle IP : assistant@kodono.info

**Comment by Aymkdn** [comment]
Sinon en relançant l'application du Freestore cela devrait mettre à jour tes info aussi

**Comment by triclic** [comment]
je t ai envoyer ma nouvelle IP
