### ISSUE TITLE
 freebox player non  détectée

### ISSUE THREAD

**Issue by Phil68-40** [Aymkdn/assistant-freebox-cloud#84]
bonjour 
j'essaye de configurer assistant cloud  mais je suis face a un problème :
 l'assistant pour la freebox nombre de freebox player détectée=0.
je précise je suis avec une  freebox delta.
merci pour vos réponse

**Comment by Aymkdn** [comment]
Dans ce cas tu dois configurer manuellement ta box : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox-
