### ISSUE TITLE
assistant cloud token

### ISSUE THREAD

**Issue by frsch06** [Aymkdn/assistant-freebox-cloud#85]
ou trouver le token a saisir sur la freebox pour assistant cloud.

**Comment by Aymkdn** [comment]
Il est sur https://assistant.kodono.info/freebox/

Il apparait à deux moments :
  1. Lorsque tu t'inscris, il apparait dès le début après avoir confirmé ton email
  2. Si ta Freebox est déjà configurée, il apparait en te loguant sur le site web https://assistant.kodono.info/freebox/

Il est plutôt bien visible :-)
