### ISSUE TITLE
bonjour

### ISSUE THREAD

**Issue by petrus55** [Aymkdn/assistant-freebox-cloud#86]

**Comment by petrus55** [comment]
suis-je obliger de refaire toute la configuration de l appli assistant pour rajouter des commande j ai déjà configurer le changement de chaine ,voila plus d un an .
merci

**Comment by Aymkdn** [comment]
Bonjour.

Pour essayer de bien comprendre : tu as déjà Assistant Cloud qui fonctionne, et tu souhaites rajouter de nouvelles applets (par exemple pour augmenter le volume) ? 

Si c'est bien ça, tu peux simplement rajouter les nouvelles applets. Depuis https://assistant.kodono.info/freebox/ vérifie que tu es bien connecté, puis va dans la section **"Commandes vocales"** et clique sur **"Cliquez ici pour afficher la suite..."**.

Tu verras toutes les applets disponibles. Il suffit alors de suivre la procédure pour celle que tu souhaites ajouter.

Si tu souhaites ajouter une commande personnalisée (donc non prédéfinie), alors tu peux t'aider de la section **"Créer mes propres actions"**.
