### ISSUE TITLE
impossible de valider le code d'activation

### ISSUE THREAD

**Issue by thie74** [Aymkdn/assistant-freebox-cloud#87]
Bonjour, lorsque je renseigne le code d'activation sur la box, il n'y a pas moyen de valider ce choix.
Merci pour votre réponse.
Cordialement
Thierry Majcher

**Comment by Aymkdn** [comment]
Vous parlez de l'application du Freestore ? Elle ne fonctionne pas ? Dans ce cas, suivre cette procédure : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#7-comment-configurer-moi-m%C3%AAme-ma-freebox-
