### ISSUE TITLE
Je cherche des possesseurs de Freebox Delta ou Freebox One

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-freebox-cloud#88]
Bonjour,

Tu as une Freebox Delta ou une Freebox One ? Alors j'ai besoin de ton aide... seulement si tu n'as pas modifié l'interface de la box !

J'aimerais savoir les touches de la télécommande sur lesquelles il faut taper pour accéder à différentes parties de l'interface.

Questions :
1. Que se passe-t-il quand on appuie sur la touche "Free" deux fois ?
2. Comment accéder à la télévision ?
3. Comment accéder aux enregistrements ?
4. Comment accéder au replay ?
5. Comment accéder à Netflix ?
6. Comment accéder aux vidéos (celles stockées sur le disque dur) ?
7. Comment accéder aux photos (si cela existe comme sur la Révolution) ?
8. Comment accéder à ses musiques (si cela existe comme sur la Révolution) ?
9. Peut-on mettre ses chaines en favoris et accéder à celles-ci uniquement ? Il me semble que oui (représenté par un écran avec une étoile à l'intérieur dans l'interface)
10. Comment accéder à l'univers Canal ? J'ai vu un logo "Canal" donc j'imagine que c'est ça ?

J'ai vu une vidéo de l'interface de la Freebox One (qui semble être la même que la Delta) et j'en ai déduit les choses suivantes  : 
1. 2 × <kbd>Free</kbd> : j'imagine que cela ramène tout en haut, au premier menu
2. La télévision : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>OK</kbd>
3. Les enregistrements : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Droite</kbd>+<kbd>Bas</kbd>+<kbd>Droite</kbd>+<kbd>OK</kbd>+<kbd>OK</kbd>
4. Le replay : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Bas</kbd>+<kbd>OK</kbd>
5. Netflix : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Bas</kbd>+<kbd>Bas</kbd>+<kbd>Droite</kbd>+<kbd>Bas</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>OK</kbd>
6. Les vidéos (celles stockées sur le disque dur) : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Bas</kbd>+<kbd>Bas</kbd>+<kbd>Bas</kbd>+<kbd>Bas</kbd>+<kbd>OK</kbd>
7. _je n'ai pas trouvé_
8. _je n'ai pas trouvé_
9. Chaines favorites : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Droite</kbd>+<kbd>Bas</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>OK</kbd>
10. Univers Canal : <kbd>Free</kbd>+<kbd>Free</kbd>+<kbd>Droite</kbd>+<kbd>Bas</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>Droite</kbd>+<kbd>OK</kbd>

Si on peut me confirmer ?

Merci

**Comment by denis26380** [comment]
bonjour,
j'ai essayé ces commande sur mon player Delta. 
Aucune commande ne correspond. car de n'importe quelle rubrique  si l'on fait 2 x free on reviens sur la meme rubrique.
Denis

**Comment by Aymkdn** [comment]
Et si on fait 2 appuis sur la touche retour (rouge), est-ce qu'on revient au tout premier menu ?

**Comment by denis26380** [comment]
on revient deux fois en arrière, mais pas sur le menu 
Pas de touche rouge sur la telecommande de la delta
un seul appui sur FREE ramène de n'importe quelle rubrique sur le menu principal, mais pas au meme niveau

**Comment by Aymkdn** [comment]
Donc si tu es dans n'importe quelle section (les enregistrements, ou Netflix, ou autre) et que tu appuies sur la touche Free, ça te ramène à l'écran principal et ça place le "curseur" sur le tout premier menu (qui est la TV il me semble)?

**Comment by denis26380** [comment]
Oui on revient au menu, mais pas sur une position fixe.
si on regarde une FREE ramène au menu sur l'onglet TV
si on est dans une rubrique du disque dur , FREE ramène au  menu sur l'onglet Multimedia
etc

**Comment by Aymkdn** [comment]
J'ai besoin de trouver la combinaison qui permet de retourner sur l'onglet TV à tous les coups... Par exemple <kbd>Free</kbd> suivi de la touche <kbd>retour</kdn> peut-être?

**Comment by denis26380** [comment]
je regarde je pense que si l'on fait FREE + RETOUR+RETOUR cela ramène à l'onglet television, je continu a tester

**Comment by denis26380** [comment]
Par contre si l'on commande la delta à la voix c'est moins evident. 
Ex je suis sur Television je commande "ok Freebox va sur YouTube" une fois sur YouTube FREE+RETOUR+RETOUR  ramène sur YouTube (donc faire une fois retour), si je suis sur le disque dur  je donne la même commande : FREE + retour ramène à la télévision …..

**Comment by Aymkdn** [comment]
Et  <kbd>Free</kbd> + <kbd>retour</kbd> + <kbd>Free</kbd>?

Sinon, j'utiliserai juste <kbd>Free</kbd> + <kbd>retour</kbd> et tant pis pour les exceptions😅

**Comment by Aymkdn** [comment]
@denis26380 as-tu pu faire des tests supplémentaires pour trouver la bonne combinaison ? Si je peux avoir ça avant samedi, ce serait cool !

Il y a forcément une combinaison qui permet de revenir au premier menu…

Merci

**Comment by Ancel1** [comment]
Effectivement je viens de tester aussi et il n'y a pas de combinaison qui semble fonctionner : 
"Free + retour" Ne fonctionne pas si je regarde la Télévision car reviens sur la chaîne télé.
"Free + retour + retour" fonctionne parfois mais pas dans tous les cas 
mais suivant si on est sur Netflix / dans Replay ou dans d"autre menu 
--> il faut parfois faire "Free" ou "free+retour" ou "Free + retour + retour"

En effet la touche "free" ne ferme pas le programme ouvert et donc se comporte difficilement.
(si on regarde la télé ou Netflix ou autre et que l'on fait free le menu n'est jamais identique)

**La seul chose qui semble fonctionnel tout le temps** est "appuis long sur free" ce qui réinitialise le menu de la télé et ferme toute les application ouverte mais prend quelque seconde car il redémarre le launcher applicatif et réinitialise le menu ouvert précédemment. On se retrouve donc au menu et aver 2 fois retour on reviendra systématiquement à l'icone de la télé.

--> La seule solution viable serai **"appuis long sur free + retour + retour"** (mais prend un peu plus de temps)

**Comment by Aymkdn** [comment]
Génial @Ancel1 merci d'avoir regardé ! Faut que je me penche sur cet appui long Free alors... Tu estimes à combien de secondes l'attente après un long Free et avant le premier retour ?

Y'a moyen de me faire une vidéo de ce que ça donne ?

**Comment by denis26380** [comment]
Bonjour, dsl je n'ai pu répondre à vos questions avant. Difficile de determiner la meilleur façon de revenir au point voulu. Mais l'appui long 10 secondes permet de fermer les appli par contre on ne se retrouve pas forcément sur la television un ou deux appuis sur retour sont necessaires

**Comment by Ancel1** [comment]
Je t'ai fais une vidéo, je dirais donc moins de 4 secondes au total (c'est pas 10 secondes ;-) --≥ ça se fait un 2 temps , appuis long sur free revient au menu so on est sur la télé et il faut maintenir pour réinitialiser, puis 2 fois retour. 

Par contre si je lance la télé juste derrière il me dit " trop de flux en simultané" , ça semble être un bug. Il suffit de lancer n'importe quoi d'autre pour corriger comme Netflix ou Replay (workaround)

**Comment by Aymkdn** [comment]
> Par contre si je lance la télé juste derrière il me dit " trop de flux en simultané 

Ah c'est ennuyeux ça 😕

**Comment by denis26380** [comment]
je maintiens le processus de reboot prends 10 secondes, on peut maintenir la touche 4 ou 5 seconde, mais ecran noir et retour a la normal au bout de 10 secondes .

**Comment by Ancel1** [comment]
@denis26380 Tu es en connexion wifi ou cpl entre tes 2 freebox (player/serveur)?
puisque pour moi ça ne prend pas autant de temps. 

Après il dois bien y avoir des api spécifique puisque via la voix on peut mettre la télé ou netflix depuis n'importe quel menu, si seulement free voulait bien partager...

**Comment by Ancel1** [comment]
Bon j'ai essayé de configurer ma freebox delta avec assistant google mais rien ne fonctionne... @Aymkdn Veux tu que je te contact plutôt par email ou j'ouvre une nouvelle issue?

**Comment by Aymkdn** [comment]
Comme tu préfères Ancel1.

**Comment by Ancel1** [comment]
Bon je viens de tester tout les numéros et c'est plutôt pas mal (hormis les 2 fois free du départ)

Par contre pour le 6 "accéder aux vidéos" il faut rajouter "bas + ok" à la fin. En faite il y a un sous menu après ce que te permettra de corriger 7 et 8 pour les photos et musiques... Je te fais une photo.

Mes vidéos (6) "Free+Free"+Bas+Bas+Bas+Bas+OK+Bas+Ok

Mes disques
"Free+Free"+Bas+Bas+Bas+Bas+OK+Ok

Mes photos (7)
"Free+Free"+Bas+Bas+Bas+Bas+OK+Bas+Bas+Bas+Ok

Mes musiques (8)
"Free+Free"+Bas+Bas+Bas+Bas+OK+Bas+Bas+Ok

Pour l'univers canal tu parles de canal+ ?
Je ne sais pas si tu veux que je fasse plus de test...

**Comment by Ancel1** [comment]
![IMG_20200205_221446](https://user-images.githubusercontent.com/37238875/73884903-189d1300-4867-11ea-8c1a-06b5eed6163c.jpg)
![IMG_20200205_221435](https://user-images.githubusercontent.com/37238875/73884925-20f54e00-4867-11ea-89e8-34bdd7c458e5.jpg)

**Comment by Aymkdn** [comment]
En fait, je ne fais pas <kbd>Free</kbd> + <kbd>Free</kbd>, mais <kbd>Free</kbd> + <kbd>Attente de 2 secondes</kbd> + <kbd>Retour</kbd> + <kbd>Retour</kbd> ! J'ai testé avec une copine qui a la One et ça semblait le plus efficace.

Merci pour `video`, `disques`, `photos` et `musiques` : je viens de mettre à jour le code donc tu peux tester :-)

> Pour l'univers canal tu parles de canal+ ?

En quelques sortes… Au niveau du menu TV tu as une box "Canal+" qui correspond à l'accès à l'univers Canal (avec toutes les chaines proposées dans ce bouquet).

> Je ne sais pas si tu veux que je fasse plus de test...

Si tu peux tester les modifications que je viens de faire du coup ?

**Comment by Aymkdn** [comment]
Une chose encore : quand tu regardes la TV et que tu mets sur `pause`, puis en `lecture`, alors qu'elles vont être les commandes pour remettre le direct ? Sur la Freebox Révolution on fait <kbd>Green</kbd> + <kbd>OK</kbd>

**Comment by Ancel1** [comment]
Je testerai les commandes ce soir. 
Pour le direct ça a changé c'est maintenant "information + ok" de mémoire. La touche informations est beaucoup plus utilisée sur la Delta

**Comment by FlorentPeltot** [comment]
Bonjour,

Super boulot, merci à toi.
J'ai une freebox one et les commandes replay et netflix ne fonctionnent pas. Je suis en train d'essayer là :)
Si tu regardes une chaine et que tu fais `free` +`retour `+ "retour" tu reviens sur la chaine que tu regardais.
Je pense que la solution serait de faire un appui long sur `free `car ça te permet de toujours revenir au menu free (ça fait un écran noir pendant 2-5 secondes et ça revient sur le menu free), à partir de là "retour" + "retour" semble bien te ramener toujours au menu "freebox TV".

Ca serait cool de l'ajouter comme fonction de "base", comme ça on pourrait faire nos propres scripts.
Par exemple, on peut utiliser les raccourcis :
Raccourcis X : `base`, `haut`, `droite* (X-1)`, `ok`
Exemple :
Raccourcis 1 : `free long`, attente 5 sec, `haut`, `droite*0`, `ok`
Raccourcis 3 : `free long`, attente 5 sec, `haut`, `droite*2`, `ok`

Merci encore à toi 👍

**Comment by Aymkdn** [comment]
> un appui long sur free car ça te permet de toujours revenir au menu free (ça fait un écran noir pendant 2-5 secondes et ça revient sur le menu free), à partir de là "retour" + "retour" semble bien te ramener toujours au menu "freebox TV".

Ouais mais je trouve ça gênant quand même car cela crée un écran noir et réinitialise l'interface… Donc niveau expérience utilisateur, je ne suis pas sûr que ce soit top ?! Moi, en soit, je veux bien, mais 5 secondes d'écran noir c'est un peu flippant, non ?

Je viens de rajouter `freeLong` comme commande, et je viens de switcher toutes les commandes vers <kbd>Free Long</kbd> + <kbd>Wait 5sec</kbd>. Si tu peux tout tester et me dire ce que tu en penses ?

> Ca serait cool de l'ajouter comme fonction de "base", comme ça on pourrait faire nos propres scripts.

C'est déjà le cas, avec la commande `home` qui va faire <kbd>Free Long</kbd> + <kbd>Wait 5sec</kbd>.
Et je viens de rajouter une commande `freeLong` qui simule un appui long sur la touche <kbd>Free</kbd>

Au passage, si vous ne l'avez pas encore fait, je vous invite à rajouter des commentaires dans le bugtracker de Free : https://dev.freebox.fr/bugs/task/28353 … en l'occurrence je pourrais utiliser cette technique pour mettre une chaine, puis faire un <kbd>Free</kbd> + <kbd>Retour</kbd>, et on serait au bon endroit :-)

Dernière chose @FlorentPeltot : peux-tu me confirmer que pour revenir au direct on doit faire <kbd>Jaune</kbd> + <kbd>Retour</kbd> ?

**Comment by Ancel1** [comment]
C'est bien information puis retour sur la Delta. (Il n'y a plus de touche
jaune). Sur la one je ne sais pas

**Comment by Ancel1** [comment]
Information + Ok (pas retour)

Le ven. 7 févr. 2020 à 11:18, Ancelin Kurtz <ancelin.kurtz@gmail.com> a
écrit :

> C'est bien information puis retour sur la Delta. (Il n'y a plus de touche
> jaune). Sur la one je ne sais pas
>

**Comment by Aymkdn** [comment]
Il n'y a pas de touche `information` dans l'API, mais l'équivalent est `yellow` ;-)

Et l'interface de la Delta est la même que la One !

Je viens de modifier le raccourci `direct` pour <kbd>Jaune</kbd> + <kbd>OK</kbd>

**Comment by FlorentPeltot** [comment]
> Ouais mais je trouve ça gênant quand même car cela crée un écran noir et réinitialise l'interface… Donc niveau expérience utilisateur, je ne suis pas sûr que ce soit top ?! Moi, en soit, je veux bien, mais 5 secondes d'écran noir c'est un peu flippant, non ?
Je suis d'accord avec toi, mais j'ai pas trouvé autre chose pour revenir à coup sûr sur le menu.
Après si tu le mets dans la FAQ ça peut rassurer les utilisateurs.

> Je viens de rajouter `freeLong` comme commande, et je viens de switcher toutes les commandes vers Free Long + Wait 5sec. Si tu peux tout tester et me dire ce que tu en penses ?
Ca ne marche pas du tout, je suis sur France 5 et ça me met sur canal+ au bout de plusieurs secondes.
Pour netflix je pense qu'il faut faire `freeLong` + `bas*2` +  `droite*3` + `bas` + `ok`
Sur la télécomande on a une touche directe netflix sinon... je ne sais pas s'ils l'ont documentée.
J'ai fait une commande qui ne fait que `freeLong` et ça ne fait pas un appui long, juste un appui normal

> > Ca serait cool de l'ajouter comme fonction de "base", comme ça on pourrait faire nos propres scripts.
> 
> C'est déjà le cas, avec la commande `home` qui va faire Free Long + Wait 5sec.
> Et je viens de rajouter une commande `freeLong` qui simule un appui long sur la touche Free
Super ! Merci

> Au passage, si vous ne l'avez pas encore fait, je vous invite à rajouter des commentaires dans le bugtracker de Free : https://dev.freebox.fr/bugs/task/28353 … en l'occurrence je pourrais utiliser cette technique pour mettre une chaine, puis faire un Free + Retour, et on serait au bon endroit :-)
Je vais y mettre un petit mot

> Dernière chose @FlorentPeltot : peux-tu me confirmer que pour revenir au direct on doit faire Jaune + Retour ?
Je n'ai pas de disque dur de branché sur la box donc je ne peux pas tester. Mais effectivement, pas de touche jaune.

**Comment by Aymkdn** [comment]
> Ca ne marche pas du tout

Arf… Bon je viens de rebasculer sur la précédente solution alors… J'ai fait l'appui long sur la touche Free comme je le faisais pour les autres touches. Je vois que ça fonctionne sur la Révolution donc je vais faire quelques tests supplémentaires.

**Comment by Aymkdn** [comment]
Je confirme que l'appui long sur la touche Free avec l'API ne fait rien, contrairement aux autres commandes :-(

Je vais fouiller le Web pour voir si je trouve quelque chose mais c'est pas gagné ! Il resterait sinon la solution de https://dev.freebox.fr/bugs/task/28353

**Comment by Aymkdn** [comment]
@FlorentPeltot et @Ancel1 je viens de penser à quelque chose.... Qu'est-ce qui se passe si vous faites <kbd>Free</kbd> + <kbd>autre touche</kbd> (comme <kbd>Bas</kbd> par exemple) + <kbd>Retour</kbd> + <kbd>Retour</kbd> ?
Ou <kbd>Free</kbd> +  <kbd>Retour</kbd> + <kbd>autre touche</kbd> (comme <kbd>Bas</kbd> par exemple) +<kbd>Free</kbd> +  <kbd>Retour</kbd> + <kbd>Retour</kbd> ?

Ou similaire.... 

L'idée étant d'empêcher de retourner sur la chaîne de TV qu'on était en train de regarder, donc peut être que si on le déplace dans un autre endroit il va alors nous ramener au début ? Vous voyez ce que je veux dire ?

**Comment by Ancel1** [comment]
Je comprend l'idée, j'ai paramètre toute les commence en ifttt mais pas encore eu le temps de trop tester. Ce week-end ça sera plus facile ;-) et je te fait un retour. Après je me suis même dis qu'on pourrait faire "eteindre + wait + allumer + retour +retour" en guise de "home" , c'est peux être lourd mais pour le moment je n'ai pas mieux. Je ferai aussi des essais avec une autre touche, voir peux être jouer avec les favoris pour retourner sur un menu précis... Je te tiens au courant

**Comment by Aymkdn** [comment]
Vous avez pu tester ça un peu ce week-end ?

**Comment by Ancel1** [comment]
Alors c'est toujours pas évident mais ce qui marche pour le menu "home" serai de faire : 

> Free + bas x10 + haut x8

Par contre ça marche sur tout les menus : télé, Netflix, YouTube ... **Mais pas sur le menu home (le comble)**

En faite le bouton "Free" se comporte comme le bouton "retour" si on est déjà sur home. Du coup si on fait Free depuis la home ça revient sur l'application ouverte précédemment et la patatra.... Donc à l'allumage de la télé ça fonctionne car aucune application n'est lancée mais si on lance n'importe quoi ça va marcher uniquement si on n'est pas sur le menu home. Une solution serai d'avoir 2 jeu de commande si on est sur l'accueil ou pas mais ça devient plus complexe.

**Comment by Ancel1** [comment]
> Free + bas + Retour


Semble fonctionner aussi et moins lourd mais c'est pareil il ne faut pas être sur Home. --> tu peux mettre ça plutôt que free + retour si ne fonctionne pas sur certain menu.

**Comment by Ancel1** [comment]
Donc "Free + bas + bas + retour" meilleur combinaison pour le moment

**Comment by Ancel1** [comment]
Je viens de trouver un truc qui marche à coup sûr et même sur le menu home : 

> Netflix + Free + retour + Retour

Le fait d'appuyer sur la touche "Netflix" ferme l'application en cours et du coup ça marche peu importe le menu où l'on est. Mais je ne sais pas si tu sais simuler la touche "Netflix" ?

**Comment by Aymkdn** [comment]
Non, Free n'a fourni aucune information sur cette API depuis la Freebox v5, donc une dizaine d'années... Tu penses bien que Netflix n'existait même pas à l'époque... Donc ce n'est malheureusement pas une solution 🙁

**Comment by Ancel1** [comment]
Donc 

> Free + bas + bas + Retour

 Pour le moment je n'ai pas mieux

**Comment by Aymkdn** [comment]
> Donc
> 
> > Free + bas + bas + Retour
> 
> Pour le moment je n'ai pas mieux

Très bien, merci @Ancel1 pour les tests. Je viens de le mettre en place !

**Comment by Aymkdn** [comment]
Pour le moment je n'ai pas reçu de retour négatif… !

Les choses seront un peu simplifiées quand on passera sur l'utilisation de l'API Player (voir https://github.com/Aymkdn/assistant-freebox-cloud/issues/70).

Je ferme ce thread. Merci à vous :-)
