### ISSUE TITLE
Changement de chaînes

### ISSUE THREAD

**Issue by Dav-76** [Aymkdn/assistant-freebox-cloud#89]
Bonjour,
tout fonctionne bien "allumer/éteindre" ; "volume +/-"... a part le changement de chaînes.
J'ai essayé sur Assitant Cloud en utilisant la liste des raccourcis et tous fonctionnent.
"Prog+/Prog-" fonctionnent mais si c'est un numéro de chaîne cela me dit "commande envoyé" mais ça ne fonctionne pas.

**Comment by Aymkdn** [comment]
Google Home ou Alexa?

**Comment by Dav-76** [comment]
Alexa

**Comment by Aymkdn** [comment]
Si tu utilises la Skill, elle doit répondre "D'accord" (c'est ce qu'elle dit chez moi).

Tu as une Freebox Révolution je suppose ? Tu lui dis quoi précisément ? Ce qui doit marcher :
> Alexa, mets la chaîne M6 sur Freebox

**Comment by Dav-76** [comment]
Ça fonctionne 👍, sur ma révolution 😉
Je lui disais pas la bonne phrase...
Par contre elle ne dit pas "D'accord" car j'ai 
activé le "mode bref"

**Comment by Aymkdn** [comment]
La liste des commandes : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-vocales#pour-alexa
