### ISSUE TITLE
parametrage freebox assistant cloud

### ISSUE THREAD

**Issue by mannone14** [Aymkdn/assistant-freebox-cloud#9]
bonjour; 
je galère pour faire en sorte que ce soit mon google mini qui déclenche l'action de l'applet, car pour l'instant c'est mon tel qui répond et envoi l'ordre à la freebox 
le google mini me repete : je ne comprends pas !

**Comment by Aymkdn** [comment]
Il faut s'assurer que le compte Google du Google Mini soit celui utilisé sur IFTTT

**Comment by mannone14** [comment]
vous aviez raison ,l'erreur venait de làcependant j'ai des soucis avec la commande : zappe sur x chaine je continue à chercher !
    Le samedi 16 mars 2019 à 22:21:27 UTC+1, Aymeric <notifications@github.com> a écrit :  
 
 
Il faut s'assurer que le compte Google du Google Mini soit celui utilisé sur IFTTT

**Comment by Aymkdn** [comment]
Quel genre de problème ?

**Comment by mannone14** [comment]
je mets d'abord dans say a phrase with a text ingredient : mais il y a un sigle à rajouter et là je sèche ! ça ne fonctionne pas apres on m'a dit va sur simple phrase mais rien url non valide
    Le dimanche 17 mars 2019 à 12:54:16 UTC+1, Aymeric <notifications@github.com> a écrit :  
 
 
Quel genre de problème ?

**Comment by mannone14** [comment]
je viens de réussir! en changeant dans l'adresse url la fin j'ai mis zappe sur 15 et ouf ça marche!
    Le dimanche 17 mars 2019 à 12:54:16 UTC+1, Aymeric <notifications@github.com> a écrit :  
 
 
Quel genre de problème ?

**Comment by Aymkdn** [comment]
Pas besoin de mettre de chiffre. Ça marche avec toutes les chaînes. Regarde la vidéo sur le site qui explique comment faire.

**Comment by mannone14** [comment]
Merci, et est ce qu'il y a moyen de naviguer dans les menus de la Freebox ? Replay, etc..?Et bravo pour votre travail !

Envoyé depuis Yahoo Mail pour Android 
 
  Le dim., mars 17, 2019 à 13:05, Aymeric<notifications@github.com> a écrit :   
Pas besoin de mettre de chiffre. Ça marche avec toutes les chaînes. Regarde la vidéo sur le site qui explique comment faire.

**Comment by Aymkdn** [comment]
Oui, tu peux créer l'enchainement de commandes que tu souhaites avec la partie **Commandes personnalisées** du site Web. Je vais aussi rajouter quelques commandes pré-définies sur le site Web (comme pour aller dans Mes Enregistrements, Ma Musique, Mes Photos, Mes Vidéos, le Replay, etc)

**Comment by mannone14** [comment]
Super ! merci pour ton retour

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., mars 18, 2019 à 9:08, Aymeric<notifications@github.com> a écrit :   
Oui, tu peux créer l'enchainement de commandes que tu souhaites avec la partie Commandes personnalisées du site Web. Je vais aussi rajouter quelques commandes pré-définies sur le site Web (comme pour aller dans Mes Enregistrements, Ma Musique, Mes Photos, Mes Vidéos, le Replay, etc)

**Comment by Xanderyuku** [comment]
Bonjour, tout d'abord félicitations au développeur c'est un sacré boulot! Si j'ai bien compris ceci n'est pas compatible Alexa et les avec les Amazon Écho etc... Est il possible d'aider de quelque manière pour ce projet ? Xander

**Comment by Aymkdn** [comment]
J'ai publié 6 nouvelles commandes que tu peux retrouver sur https://assistant.kodono.info/freebox/ dans la section "Commandes Vocales" : 

- remettre le direct
- aller dans "Mes Enregistrements"
- aller dans "Mes Vidéos"
- aller dans "Mes Musiques"
- aller dans "Mes Photos"
- aller dans le Freebox Replay

**Comment by mannone14** [comment]
Merci !

Envoyé depuis Yahoo Mail pour Android 
 
  Le mar., mars 19, 2019 à 12:11, Aymeric<notifications@github.com> a écrit :   
J'ai publié 6 nouvelles commandes que tu peux retrouver sur https://assistant.kodono.info/freebox/ dans la section "Commandes Vocales" :
   
   - remettre le direct
   - aller dans "Mes Enregistrements"
   - aller dans "Mes Vidéos"
   - aller dans "Mes Musiques"
   - aller dans "Mes Photos"
   - aller dans le Freebox Replay

**Comment by BenCath** [comment]
Bonjour et merci pour le boulot effectué.
Je ne comprends car j'ai bien tout paramétré comme indiqué (a priori) mais rien ne se passe sur la Freebox pour aucune des commandes.
Mon Google Home me confirme bien la commande avec la phrase choisie mais aucune action n'est effectivement réalisée. J'ai pourtant installé l'app via le Freestore et fait la procédure d’association avec le code à saisir... J en vois pas où le problème se pose.
Mon compte Google est bien le même utilisé pour mon inscription et pour mon Google Home.

**Comment by mannone14** [comment]
Bonjour, je me permets de revenir vers toi car depuis hier , aucune commande ne répond . Ex: allume /éteins la freebox, zappe sur , bref, je n'ai plus rien. Quand je lance une commande , ceux cités plus haut ou alors pour le volume, il me dit ok , j'allume la freebox  et rien ne se passe .Compte vérifié , RAS de ce côté
    Le mardi 19 mars 2019 à 12:11:15 UTC+1, Aymeric <notifications@github.com> a écrit :  
 
 
J'ai publié 6 nouvelles commandes que tu peux retrouver sur https://assistant.kodono.info/freebox/ dans la section "Commandes Vocales" :
   
   - remettre le direct
   - aller dans "Mes Enregistrements"
   - aller dans "Mes Vidéos"
   - aller dans "Mes Musiques"
   - aller dans "Mes Photos"
   - aller dans le Freebox Replay

**Comment by Aymkdn** [comment]
il se peut que votre box ait changé d'adresse : 
     1. Aller sur http://mafreebox.freebox.fr/ depuis son réseau local et se connecter (afin d'accéder à l'interface Web de la Freebox)  
     2. Aller dans **Paramètres de la Freebox**, onglet **Mode avancé**
     3. Aller dans **Gestion des ports**
     4. Repérer la section qui induque les informations ci-dessous : 
      ![Capture](https://user-images.githubusercontent.com/946315/55190715-aff1fe00-51a0-11e9-8e2f-d03840661a0a.PNG)
     5. Vérifier que la redirection est bien faite en direction de votre Freebox Player, sinon éditer l'entrée et choisir le Freebox Player dans la liste déroulante

**Comment by mannone14** [comment]
j'arrive à ça , dites moi ce que je dois faire après
    Le jeudi 28 mars 2019 à 21:38:03 UTC+1, Aymeric <notifications@github.com> a écrit :  
 
 
il se peut que votre box ait changé d'adresse :
1. Aller sur http://mafreebox.freebox.fr/ depuis son réseau local et se connecter (afin d'accéder à l'interface Web de la Freebox)
2. Aller dans Paramètres de la Freebox, onglet Mode avancé
3. Aller dans Gestion des ports
4. Repérer la section qui induque les informations ci-dessous :

5. Vérifier que la redirection est bien faite en direction de votre Freebox Player, sinon éditer l'entrée et choisir le Freebox Player dans la liste déroulante

**Comment by Aymkdn** [comment]
C'est quoi "ça"?

Merci de ne pas répondre à l'email mais d'utiliser ce lien : https://github.com/Aymkdn/assistant-freebox-cloud/issues/9

**Comment by mannone14** [comment]
dsl, voici donc la capture d'image de la ou j'arrive
![Capture d’écran (1)](https://user-images.githubusercontent.com/48632940/55217968-10b12300-5201-11e9-85d5-06253b633128.png)

**Comment by Aymkdn** [comment]
Comme je l'ai dit dans mon message, édite l'entrée en cliquant sur l'icône à droite, puis choisis Freebox Player dans la liste déroulante, puis enregistre

**Comment by mannone14** [comment]
Dsl suis un peu boulet en la matière. Mais à ma place de Android je vais chercher Freebox player c ça ?

**Comment by Aymkdn** [comment]
C'est bien ça

**Comment by mannone14** [comment]
merci! ça fonctionne mais saais tu pourquoi ça avait changer cette redirection ?

**Comment by Aymkdn** [comment]
Je soupçonne certaines box de changer d'adresse IP. Je regarderai ça de plus près quand je rentre de vacances

**Comment by Aymkdn** [comment]
C'est parce que tu n'as pas de bail statique pour ta Freebox Player. J'ai ajouté une section sur comment rendre le bail statique : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player

Je t'invite à lire et à suivre la procédure pour éviter ce problème dans le futur !

**Comment by mannone14** [comment]
Je te remercie beaucoup

Envoyé depuis Yahoo Mail pour Android 
 
  Le lun., avr. 1, 2019 à 9:17, Aymeric<notifications@github.com> a écrit :   
C'est parce que tu n'as pas de bail statique pour ta Freebox Player. J'ai ajouté une section sur comment rendre le bail statique : https://github.com/Aymkdn/assistant-freebox-cloud/wiki#v%C3%A9rification-de-ladresse-ip-du-freebox-player

Je t'invite à lire et à suivre la procédure pour éviter ce problème dans le futur !
