### ISSUE TITLE
Probleme avec commande Allume et zappe

### ISSUE THREAD

**Issue by NicolasP93** [Aymkdn/assistant-freebox-cloud#90]
Hello,
Déjà merci pour ton travail remarquable !
99% des apelets fonctionnent et ca me facilite grandement la vie
Par contre j'ai un petit souci
La commande "allume la Freebox et zappe sur" ne fonctionne pas, car en fait la Freebox s'allume bien mais reste sur le menu Home
J'ai pourtant bien choisi Freebox TV dans ton utilitaire/formulaire de configuration.
Quand je valide avec la touche OK de la télécommande, je peut ensuite changer de chaine sans problème avec la commande vocale "Zappe sur $"
Aurais tu une solution ? Est ce un problème connu ? Puis je faire quelque chose ?
Ou aurait tu la commande pour valider la touche OK a la voix avec Google Assistant ?
Merci d'avance pour ton aide et encore merci pour ce super boulot !
Cordialement
Nico

**Comment by Aymkdn** [comment]
Comme indiqué dans mon email, vérifie que tu as créé l'applet _"allume la Freebox et zappe sur"_. C'est une applet dédiée qui va allumer la Freebox, puis aller dans l'univers TV, puis zapper sur la chaine demandée.

Il est possible que tu l'aies oublié ou que tu ne l'aies pas correctement configuré. Si tu l'as créée, supprime-la puis recommence en suivant les instructions : 
![Capture](https://user-images.githubusercontent.com/946315/73132704-c403c780-401e-11ea-84d0-e35e3014d797.JPG)

Et ensuite :
![Capture](https://user-images.githubusercontent.com/946315/73132725-ef86b200-401e-11ea-946c-b828e96de46d.JPG)

**Comment by NicolasP93** [comment]
Yes je l'ai bien fait, plusieurs fois
Je te met le screen
[Image][Image]

________________________________

**Comment by Aymkdn** [comment]
Je ferme ici puisqu'on discute par email déjà.

**Comment by NicolasP93** [comment]
Je viens par contre de réussir pour la touche OK
________________________________
