### ISSUE TITLE
Commande OK 

### ISSUE THREAD

**Issue by Laurentvv360** [Aymkdn/assistant-freebox-cloud#91]
Bonjour,
J'ai fait la commande afin d'afficher le programme pour la soirée.
Voici la commande.(google home)
https://assistant...................../?c=green,down,right,ok&f=......
Tous ce passe bien jusqu'a "right" mais la commande "ok" ne valide pas.
Une idée ?
Merci

**Comment by Aymkdn** [comment]
Essaie d'ajouter un temps d'attente peut-être ? Ci-dessous je rajoute un délai de 2 secondes avant le OK
> green,down,right,wait2000,ok

**Comment by Laurentvv360** [comment]
Super, ça fonctionne,
merci Aymeric
