### ISSUE TITLE
Freebox delta ne réagit pas aux commandes vocales.

### ISSUE THREAD

**Issue by BARNINI** [Aymkdn/assistant-freebox-cloud#92]
Bonjour,
Suis heureux de découvrir que l’application Cloud Assistant que j’utilisais avec plaisir avec la box Révolution est maintenant disponible pour la Delta.
Malheureusement, alors que je pense l’avoir paramétrée correctement pour la Delta, elle ne réagit pas aux commandes.
Exemple : Ok Google, allume la Freebox - Réponse “J’allume la Freebox” et rien ne se passe.
Avez-vous une explication.
Avec mes remerciement.

**Comment by Aymkdn** [comment]
Je t'invite à tester tout ce qui est indiqué sur la page d'aide : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Trouver-pourquoi-cela-ne-fonctionne-pas

Puis à m'indiquer ce qui marche/ne marche pas, en fournissant des captures d'écran !

**Comment by BARNINI** [comment]
Mille excuses pour la non réponse, ce n’est pas du désintéressement mais je galère beaucoup pour paramétrer ton assistant que je maitrisais pourtant parfaitement avec la Révolution.

 

J’ai fait des copies écran qui t’aideront peut-être à me dire ce qui ne va pas.

 

Je dois te préciser que j’utilise le Player avec une télé Samsung et que j’ai des difficultés pour synchroniser le player et la télé. Suis contrait d’appuer au moins 4 fois sur la télécommande avant d’avoir l’image sur le téléviseur. Assistance Free contactée à plusieurs reprises attribue ce phénomène à une incompatibilité de mon téléviseur.

 

Avec mes remerciements.

 

     Yves Barnini

 

 

 

De : no-response[bot] <notifications@github.com> 
Envoyé : jeudi 30 janvier 2020 15:36
À : Aymkdn/assistant-freebox-cloud <assistant-freebox-cloud@noreply.github.com>
Cc : BARNINI <Yves.barnini@laposte.net>; Author <author@noreply.github.com>
Objet : Re: [Aymkdn/assistant-freebox-cloud] Freebox delta ne réagit pas aux commandes vocales. (#92)

 

Cette issue a été automatiquement fermée car il n'y a eu aucune réponse complémentaire de la part de l'auteur. N'hésite pas à reposter ici si tu as d'autres questions.

**Comment by Aymkdn** [comment]
Il faut te rendre sur https://github.com/Aymkdn/assistant-freebox-cloud/issues/92 pour y joindre tes captures d'écran, ou bien me contacter par email (assistant@kodono,info), car je ne vois rien sinon.

Je viens de regarder ton compte, et aucune commande n'est arrivée jusqu'à mon serveur depuis mars 2019, ce qui signifie que le problème vient de Google <-> IFTTT.

Est-ce que ton Google comprend quand tu lui dis une commande vocale, du genre "Allume la Freebox" : quelle est sa réponse ?

Encore une fois, je t'invite à voir https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Trouver-pourquoi-cela-ne-fonctionne-pas

> Suis contrait d’appuer au moins 4 fois sur la télécommande avant d’avoir l’image sur le téléviseur

Je ne comprends pas cette phrase. Tu parles du fait que si l'écran est éteint et que tu appuies sur le bouton Power de ta télécommande, cela n'allume pas ta TV ? Même si tu patientes quelques secondes ?
Si c'est le cas, je ne pourrai rien y faire non plus :-) Mais l'assistant cloud permet de zapper, augmenter le son, etc… Donc à la limite, ce n'est pas bien grave que tu n'arrives pas à allumer ou éteindre !

**Comment by Aymkdn** [comment]
Je ferme ici pour poursuivre par email et éviter toute confusion
