### ISSUE TITLE
freebox

### ISSUE THREAD

**Issue by ROGALINSKI** [Aymkdn/assistant-freebox-cloud#93]
Bonjour,

Lorsque je lance la commande allume la freebox et zappe sur la 2 il me propose systematique la freebox player mini et pas la revolution. meme si je modifie la commande vocale en lui disant freebox revolution. J'utilise google assistant.

Merci d'avance pour votre réponse
Patrick ROGALINSKI

**Comment by Aymkdn** [comment]
> il me propose systematique la freebox player mini

Que veux-tu dire ? Tu as une Freebox Mini en plus d'une Freebox Révolution ?

Google va gérer nativement la 4K comme c'est une box Android… Tu as eu le bon réflexe en mettant "Allume la Freebox Révolution et zappe…" dans ton applet, mais il semblerait que Google passe outre la commande à cause du mot-clé "Freebox".

Du coup, essaie de plutôt mettre **"Allume la Révolution et zappe…"**, comme ça Google n'entend plus le mot "Freebox" et il devrait rediriger la requête vers IFTTT.

**Comment by ROGALINSKI** [comment]
Re

Je te remercie ca fonctionne je passe aux autres commandes.

Patrick

Le 29/01/2020 à 11:16, Aymeric a écrit :

**Comment by Aymkdn** [comment]
@ROGALINSKI : est-ce que tu t'y connais en Linux ? Est-ce que tu as un serveur Linux ? Je travaille sur une version d'Assistant Cloud qui va fonctionner avec la Freebox Pop, et ça devrait aussi marcher avec la Freebox Mini 4K… Si tu as encore la Mini 4K, j'aurais besoin d'une personne pour effectuer quelques tests pour moi… Si t'es intéressé, dis le moi. Merci

**Comment by ROGALINSKI** [comment]
Bonjour,
Je n'ai plus le mini 4k je l'ai échangée par une pop. Je n'ai pas de
serveur Linux.

**Comment by Aymkdn** [comment]
Ok! Tu as la Pop en plus de la Freebox Révolution ? Ou tu as rendu la Freebox Révolution et es passé à la Delta + player Pop? Ou autre configuration?

**Comment by ROGALINSKI** [comment]
Jai la pop avec la révolution. Jai deux players.

Patrick

**Comment by Aymkdn** [comment]
@ROGALINSKI  est-ce que tu peux m'envoyer un email sur aymeric@kodono.info que je puisse d'expliquer comment tu peux tester la nouvelle version du site. Merci

**Comment by ROGALINSKI** [comment]
C'est fait.

Patrick
