### ISSUE TITLE
freebox via Alexa manque des chaines

### ISSUE THREAD

**Issue by DamienH35** [Aymkdn/assistant-freebox-cloud#94]
Bonjour,
Il me manque l'acces à beaucoup de chaine, de 22 à 230 en gros!

Comment résoudre le soucis?

Cordialement.

**Comment by Aymkdn** [comment]
Que veux-tu dire par "il me manque l'accès" ?

C'est Alexa qui gère la reconnaissance du nom d'une chaine. J'en ai essayé pas mal (les plus communes) et Alexa a toujours reconnu leurs noms.

Peux-tu me donner des exemples précis de ce que tu dis à Alexa et de sa réponse ?

**Comment by DamienH35** [comment]
ben en fait, si je lui dit:"Alexa met la 22, 24(ou chaine 22, 24, ...)",

Elle me dit: 
"Je n'ai trouvé aucune skill vidéo activé qui puisse faire ce que vous voulez,..."

Par contre, si je demande:
"Alexa met 6ter ou RMC Découverte"

Là, c'est bon!

Autre chose, si je dis: "Met M6" elle repond comme audessus ! Mais si je lui dis: "Zappe sur M6", c'est bon !

Y-a-t-il la possibilité de savoir tout les lien de chaine soit par N° ou par nom ?

**Comment by Aymkdn** [comment]
Quand elle dit "Je n'ai trouvé aucune skill vidéo activé qui puisse faire ce que vous voulez,...", essaie de rajouter "Freebox" dans ta phrase.

Par exemple "mets M6 sur Freebox". De temps en temps elle a besoin qu'on la dirige vers l'appareil connecté

**Comment by DamienH35** [comment]
Re !

Alors, en poussant un peu plus loin, j'ai l'impression qu'en fait Alexa à du mal à la reconnaissance vocale, il faut bien articulé et lentement pour réussir à avoir la chaine désirer soit par son numéro ou par son nom!

**Comment by Aymkdn** [comment]
J'utilise Alexa sur mon téléphone (j'ai un Google Home à la maison), et elle me reconnaît toujours bien...

Comme je t'ai dit, essaie d'ajouter "Freebox" dans ta phrase te quelle comprenne à qui elle doit s'adresser

**Comment by Aymkdn** [comment]
Les commandes vocales testées chez moi et qui fonctionnent : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Commandes-vocales#pour-alexa

**Comment by DamienH35** [comment]
Yep, ça marche un peu mieux avec le "forçage" "sur Freebox".

C'est une Echo Dot que j'ai.

Bon maintenant, il faut que je trouve comment eteindre ma TV en même temps que la freebox!
Mais là, c'est je pense plus un soucis de compatibilité HDMI CEC entre ma tv LG et la Freebox, car quand les 2 sont éteintes, l'allumage de la freebox (via Alexa ou télécommande free) allume bien la TV, mais pas l'arrêt!
Par contre quand j'éteinds la TV avec sa télécommande, cela arrête aussi la Freebox!

Faut que je cherche !!!

Et MERCI pour ton Skill/Protocole/applis pour Alexa/Freebox !!!

**Comment by Aymkdn** [comment]
> plus un soucis de compatibilité HDMI CEC entre ma tv LG et la Freebox

Oui, j'avais le même problème sur ma LG, mais depuis j'ai changé de TV et ça marche 😉
