### ISSUE TITLE
Freebox Delta

### ISSUE THREAD

**Issue by Ancel1** [Aymkdn/assistant-freebox-cloud#95]
Hello,

J'avais avant une Freebox révolution et je suis passé à la Delta. Je n'ai pas recréer de compte assistant Freebox (cloud) --> j'ai juste reparamétré.
J'ai tout vérifié  ip public/port/code/... Réinstallé l'application...
Google lance bien les commandes et ifttt lance bien les applets mais rien ne se passe. 

Si je paramètre une commande "Manuelle" via ton site et la télécommande virtuelle, le bouton "test" ne lance rien. 

La seule chose qui fonctionne c'est le test en local pour éteindre/allumer via http IP player +code télécommande.

Je suis en peu dans l'impasse et je ne sais plus quoi faire.

Merci pour ton aide

**Comment by Aymkdn** [comment]
Ton réseau local présente-t-il une particularité ? Comme un routeur different de la Freebox?

**Comment by Ancel1** [comment]
Non j'utilise le Freebox Serveur, je n'ais pas de routeur autre.

**Comment by Aymkdn** [comment]
L'autre jour quelqu'un a eu ce problème avec la Delta. Il l'a redémarré et ça a fonctionné... Peut être que tu peux essayer ? Sinon je ne vois pas....

**Comment by Ancel1** [comment]
Je viens de redémarrer le serveur et le player mais ça ne change rien. Questions : si je lance une commande via https://assistant-api.kodono.info/."ID"../?c=unmute depuis mon navigateur ça m'affiche "ok", c'est sensé lancer lacommande ? Cet ID est lié au paramètre du compte assistant Google ? En gros si je change de port ou de code télécommande j'aurai toujours le même id sans avoir besoin de changer les web hooks?

**Comment by Aymkdn** [comment]
Tout à fait, l'id est lié à ton compte, donc peu importe si tu changes d'IP ou de port.
Si tu me donnes un bout de ton e-mail, je peux regarder ce que mon serveur a reçu.

**Comment by BARNINI** [comment]
J’ai exactement le même problème et j’ai échangé à ce sujet avec Aymeric. J’ai suivi toutes ses indications sans résultat.
Le Google Home répond bien “j’allume la Delta”, preuve qu’Ifttt fait son travail, mais rien ne se passe avec le player.
Par contre, voyant la réponse de ce jour d’Aymeric, je précise que mon player est relié au serveur Delta en Ethernet et que la liaison transite par un hub. Est-ce que le problème pourrait venir de là ?
Merci et mille excuses pour m’être introduit dans votre conversation.

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Barnini, oui ça pourrait venir de là en effet.

**Comment by BARNINI** [comment]
Merci pour la rapidité de ta réponse, je ferai des essais en squizant le Hub et je te donnerai la réponse.


Envoyé de mon iPhone

**Comment by Ancel1** [comment]
Si j'ai écrit sur le git c'est pour en faire profiter tout le monde ;-), je crois que moi aussi depuis le boîtier cpl du player je vais vers un Switch puis je retourne au player. Il y 2 ports réseau maintenant je regarderai comment je suis connecté

**Comment by BARNINI** [comment]
Malheureusement, même un branchement direct (ethernet sans hub intermédiaire) ou en WIFI, ne règle le problème.
Désolé il va nous falloir continuer à chercher.

Envoyé de mon iPhone

**Comment by BARNINI** [comment]
J’ai aussi désactivé les freeplugs pour éviter toute interférence entre le CPL et le câble Ethernet, mais rien n’y fait.

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Une personne m'a dit un jour avoir fait une redirection UDP en plus (à la place ?) de la redirection TCP du port. À tester peut être ? Même si je ne vois pas pourquoi ça marcherait mieux... 

Au niveau des IP du réseau local, le Serveur et Player sont sur le même masque ? Par exemple 192.168.0.x pour le serveur et 192.168.0.y pour le player ?

Si tous les deux vous pouvez me donner un bout de votre email afin que je jette un œil à votre compte?

**Comment by Aymkdn** [comment]
Barnini c'est bon j'ai ton email

**Comment by BARNINI** [comment]
OK

Envoyé de mon iPhone

**Comment by Ancel1** [comment]
Je ne suis pas chez moi, j'essayerai en udp de soir. Normalement tu as du recevoir mon mail.

**Comment by Aymkdn** [comment]
J'ai scanné vos 2 machines sur les ports prévus, et les ports sont fermés… Quand je fais la même chose avec mon IP et le port associé j'obtiens bien un port ouvert : 
> PORT     STATE         SERVICE    VERSION
> xxxx/tcp open          http       nginx

Nginx étant le serveur utilisé par le Freebox Player.

Pouvez-vous vérifier cela : 
1. Aller sur http://mafreebox.freebox.fr/login.php
2. Se connecter
3. Double-cliquer sur **"État de la Freebox"**
4. Cliquer sur l'onglet **"État Internet"**
5. Dans **"Adresse IPv4"** vous devez avoir votre IP suivie par une information concernant les **ports disponibles** : pouvez-vous vérifier que le port que vous avez indiqué pour Assistant Cloud se trouve dans la plage de ports disponibles ?

**Comment by BARNINI** [comment]
De ce côté-là, tout parait normal.

 

De : Aymeric <notifications@github.com> 
Envoyé : mercredi 5 février 2020 14:56
À : Aymkdn/assistant-freebox-cloud <assistant-freebox-cloud@noreply.github.com>
Cc : BARNINI <Yves.barnini@laposte.net>; Comment <comment@noreply.github.com>
Objet : Re: [Aymkdn/assistant-freebox-cloud] Freebox Delta (#95)

 

J'ai scanné vos 2 machines sur les ports prévus, et les ports sont fermés… Quand je fais la même chose avec mon IP et le port associé j'obtiens bien un port ouvert :

PORT STATE SERVICE VERSION
xxxx/tcp open http nginx

Nginx étant le serveur utilisé par le Freebox Player.

Pouvez-vous vérifier cela :

1.	Aller sur http://mafreebox.freebox.fr/login.php
2.	Se connecter
3.	Double-cliquer sur "État de la Freebox"
4.	Cliquer sur l'onglet "État Internet"
5.	Dans "Adresse IPv4" vous devez avoir votre IP suivie par une information concernant les ports disponibles : pouvez-vous vérifier que le port que vous avez indiqué pour Assistant Cloud se trouve dans la plage de ports disponibles ?

**Comment by Ancel1** [comment]
HAHA j'ai trouvé pour ma part !

En faite j'ai pris mon adresse ip v4 public via ton site https://ip.lafibre.info/ mais en faite ça ne correspond pas du tout. L'adresse via le site est toujours identique mais mon adresse IP v4 de la box dans  "État de la Freebox" / "État Internet"/ "Adresse IPv4" est différente --> j'ai utilisé celle de la box et les premières commandes fonctionnent ! 
--> je pense que le mieux dans ton tuto et de faire vérifier l'ip V4 directement dans l'interface de la freebox

**Comment by BARNINI** [comment]
Youpi, j’ai suivi les indications d’Ancel1 et ça fonctionne très bien. Il ne me reste qu’à faire les autres commandes. Si vous en êtes d’accord, je vous propose de partager les procédures.
Merci à tous les deux.


Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Bizarre... Vous utilisez un vpn peut-être ?!

**Comment by Ancel1** [comment]
Non pas de vpn, par contre j'ai activé la puce 4g. Je ne sais pas trop comment il fait l'agrégation du débit, si il un hsrp ou autre...

**Comment by BARNINI** [comment]
Pas de VPN pour moi non plus.

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Et https://ipv4.kodono.info vous donne également une mauvaise IP ?

**Comment by BARNINI** [comment]
Oui, effectivement, pour moi aussi l’adresse IP n’était pas la bonne. 

Envoyé de mon iPhone

**Comment by Aymkdn** [comment]
Merci les gars ! J'ai mis à jour la doc et je vais modifier l'application du Freestore également pour tenir compte de ce problème !
