### ISSUE TITLE
Actions double

### ISSUE THREAD

**Issue by Eurst** [Aymkdn/assistant-freebox-cloud#96]
Bonjour,

Quand j'éteins la freebox avec google, ma tv reste allumée. 
Y'a t'il un moyen d'associer deux commandes de deux services sur une même instruction ?

Cordialement.

**Comment by Aymkdn** [comment]
Bonjour,

Assistant Cloud va simuler l'appui sur le bouton "power" de la télécommande Freebox. L'action qui en résulte doit être la même que si tu le fais chez toi. Quand tu éteins la Freebox, est-ce que ça éteint ta TV ? Si non, alors active le HDMI CEC https://www.universfreebox.com/article/18200/Freebox-Revolution-Parametrez-la-fonction-HDMI-CEC

> Y'a t'il un moyen d'associer deux commandes de deux services sur une même instruction ?

Oui. Pour cela il faut créer une "applet private" via https://platform.ifttt.com/ qui permet de créer plusieurs actions. Si tu es débrouillard tu verras que ce n'est pas très compliqué, sinon dis le moi et je peux faire un tutoriel.

**Comment by Eurst** [comment]
Merci pour votre réponse rapide.
J'arrive à créer un applet personnalisé, mais impossible de l'associer à une instriction Google Assistant.
Je dois mal m'y prendre :/

**Comment by Aymkdn** [comment]
Je vais faire un tuto. Cela pourrait servir à d'autres :-)

**Comment by Eurst** [comment]
Ceci dit, la solution du HDMI-CEC pourrait être intéressante, cependant, entre ma Freebox Delta et ma Samsung TV, le résultat est très aléatoire. Ca marche quand ca veut.

**Comment by Aymkdn** [comment]
Voilà : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Ex%C3%A9cuter-plusieurs-actions-avec-IFTTT
