### ISSUE TITLE
Ouverture d'une vidéo Youtube ou Netflix

### ISSUE THREAD

**Issue by Eurst** [Aymkdn/assistant-freebox-cloud#97]
Bonjour, 
Je risque d'avoir pas mal de questions à soumettre, j'aime beaucoup ce que vous avez fait, ça fonctionne même mieux que OK Freebox (qui me lance la radio quand je veux remettre en lecture par exemple) 
En voici donc une autre : Est-il possible de faire ouvrir un programme Netflix ou une vidéo Youtube par une instruction Google ?

**Comment by Aymkdn** [comment]
Oui c'est possible : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Cr%C3%A9er-une-applet-IFTTT-pour-Google

**Comment by Eurst** [comment]
Bien vu votre tuto. Mais aucun applet ne me permettrait de dire : "met The Big Bang Theory sur la Freebox via Netflix" ?

**Comment by Aymkdn** [comment]
Ah ça par contre, non, ce n'est pas (techniquement) possible. Vous pouvez seulement lancer Netflix ou lancer l'application YouTube.

**Comment by Eurst** [comment]
Je vois, la solution serais de faire une commande pour chaque touche de la télécommande et réciter les actions a réaliser .. (Ce qui serait plus long que chercher la télécommande)
Merci pour votre réponse. En tout cas, votre tuto m'a bien aidé pour exécuter plusieurs actions en une seule commande. Merci à vous
