### ISSUE TITLE
Alexa: commande "zappe sur XXX" non reconnue

### ISSUE THREAD

**Issue by Vinsyl33** [Aymkdn/assistant-freebox-cloud#98]
Bonsoir Aymeric,
J'ai bien réussi à configurer Alexa et Google Home mais j'ai un soucis avec Alexa car quand je dis "zappe sur XXX", Alexa me dit : "Je n'ai trouvé aucune skill vidéo...". Et pourtant cela a fonctionné tout au début. Que puis-je faire?
Merci d'avance pour ton aide.
Sylvain.
PS: bravo pour le boulot accompli:-).

**Comment by Aymkdn** [comment]
Cela devrait t'aider : https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Questions-Fr%C3%A9quentes#alexa-me-dit---je-nai-trouv%C3%A9-aucune-skill-vid%C3%A9o-activ%C3%A9e-qui-puisse-faire-ce-que-vous-voulez-

**Comment by Vinsyl33** [comment]
Effectivement cela fonctionne mais j'aurai voulu pouvoir dire la version courte. Mais merci pour ton aide et rapide réponse.

**Comment by Aymkdn** [comment]
La version courte fonctionne aussi. Si tu lui dis le mot Freebox de temps en temps elle devrait être capable de savoir à quel dispositif elle doit s'adresser. En gros, quand elle ne comprend plus tu you dis "Freebox" et les commandes suivantes devraient fonctionner.

**Comment by Vinsyl33** [comment]
Trop fort et effectivement cela fonctionne. Merci beaucoup. Bonne soirée.

**Comment by Vinsyl33** [comment]
Re,
Désolé de t'ennuyer mais j'ai une autre petite demande:-): quand je baisse le son à l'aide de la commande vocale (HDMI CEC), le volume baisse de 5 en 5. Comment puis-je modifier ce réglage?
Merci d'avance.

**Comment by Aymkdn** [comment]
Tu peux essayer de changer l'option de volume sur Assistant Cloud pour voir si ça change quelque chose ?

**Comment by Vinsyl33** [comment]
Désolé mais tu parles sur ton site?

**Comment by Aymkdn** [comment]
Oui

**Comment by Vinsyl33** [comment]
Je trouve pas cette option. Aurais-tu le lien? Est-ce https://assistant.kodono.info/freebox/?

**Comment by Aymkdn** [comment]
Oui.

![Screenshot_20200218-234258__01](https://user-images.githubusercontent.com/946315/74784571-80f8e500-52a8-11ea-8d96-924a126daa0e.jpg)

**Comment by Aymkdn** [comment]
Essaie de repasser en mode normal si l'autre mode ne marche pas.

**Comment by Vinsyl33** [comment]
Ah oui j'ai déjà activé cette option et je viens de tester en mode "normal" et effectivement le volume baisse ou augmente de 1 en 1 mais une fois sur 4 ou 5. Le reste du temps le niveau reste le même.

**Comment by Aymkdn** [comment]
Bizarre... T'es le premier à me rapporter un tel problème. Va falloir que je regarde ce que je peux faire pour ton cas particulier. Peux-tu m'envoyer un mail sur assistant@kodono.info à partir de l'email utilisé pour ton compte ? Et je regarde ça dès que j'ai un moment.
