### ISSUE TITLE
La commande "Allume la Freebox" ne fonctionne pas

### ISSUE THREAD

**Issue by cgardiennet** [Aymkdn/assistant-freebox-cloud#99]
Freebox : Révolution
Toutes les commandes vocales que j'ai configuré fonctionnent sauf la commande "Allume la freebox".
Pour éviter tout souci de paramétrage ou autre j'ai lancé la commande directement via le navigateur.
Cette commande éteint bien la freebox mais ne parvient jamais à l'allumer.
Y aurait il un problème avec la version de ma freebox ou autre ?

Merci d'avance.

**Comment by Aymkdn** [comment]
T'as essayé ça https://github.com/Aymkdn/assistant-freebox-cloud/wiki/Questions-Fr%C3%A9quentes#je-peux-%C3%A9teindre-mais-pas-allumer-ma-freebox ?

**Comment by cgardiennet** [comment]
Ah non je n'avais pas assez cherché. Ca fonctionne parfaitement. Merci de ta réponse rapide. J'adore ton app Freebox ;-)
